extends:
  - plugin:react/recommended
  - standard

plugins:
  - standard
  - promise
  - react
  - prettier

rules:
  prettier/prettier:
    - error
    - printWidth: 80
      singleQuote: true
      trailingComma: es5
      bracketSpacing: true
      jsxBracketSameLine: false
      parser: babylon
      semi: false

  no-return-assign: off
  max-len:
    - 2
    - 80
    - 2

  comma-dangle:
    - error
    - only-multiline

  space-before-function-paren:
    - error
    - never
