processes = new (require 'processes')
option '-c', '--config [CONFIG]', 'Which config file to use.'

task 'run', ({config}) ->
  KONFIG = require('koding-config-manager').load("main.#{config}")
  
  processes.fork
    name  : "libratoWorker"
    cmd   : "./index -c #{config}"
    restart : yes
    restartInterval : 1000

  return