{fork} = require 'child_process'
# KodingLogger = require 'koding-logger'
os = require 'os'
processes = new (require 'processes')
option '-c', '--configPath [CONFIG]', 'Which config file to use.'

task 'run', ({configPath}) ->
  configPath ?= '../../config/dev'
  processes.fork
    name  : "libratoWorker"
    cmd   : "./index -c #{configPath}"
    restart : yes
    restartInterval : 1000

  return