require './statemachine.test'
require '../lib/react/test'
require '../lib/flux/test'
require './applicationmanager.test'
# require './searchcontroller.test'
require './kodinglistcontroller.test'
require './kodinglistview.test'
require './commonviews/bannernotificationview.test'
require './util/stripHTMLtoText.test'
require './util/proxifier.test'
require '../lib/components/codeblock/test'
