package kloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// KloudMigrateReader is a Reader for the KloudMigrate structure.
type KloudMigrateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *KloudMigrateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewKloudMigrateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewKloudMigrateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewKloudMigrateOK creates a KloudMigrateOK with default headers values
func NewKloudMigrateOK() *KloudMigrateOK {
	return &KloudMigrateOK{}
}

/*KloudMigrateOK handles this case with default header values.

Request processed successfully
*/
type KloudMigrateOK struct {
	Payload *models.DefaultResponse
}

func (o *KloudMigrateOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/Kloud.migrate][%d] kloudMigrateOK  %+v", 200, o.Payload)
}

func (o *KloudMigrateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewKloudMigrateUnauthorized creates a KloudMigrateUnauthorized with default headers values
func NewKloudMigrateUnauthorized() *KloudMigrateUnauthorized {
	return &KloudMigrateUnauthorized{}
}

/*KloudMigrateUnauthorized handles this case with default header values.

Unauthorized request
*/
type KloudMigrateUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *KloudMigrateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/Kloud.migrate][%d] kloudMigrateUnauthorized  %+v", 401, o.Payload)
}

func (o *KloudMigrateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
