package kloud

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIKloudCheckTemplateReader is a Reader for the PostRemoteAPIKloudCheckTemplate structure.
type PostRemoteAPIKloudCheckTemplateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIKloudCheckTemplateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIKloudCheckTemplateOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIKloudCheckTemplateUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIKloudCheckTemplateOK creates a PostRemoteAPIKloudCheckTemplateOK with default headers values
func NewPostRemoteAPIKloudCheckTemplateOK() *PostRemoteAPIKloudCheckTemplateOK {
	return &PostRemoteAPIKloudCheckTemplateOK{}
}

/*PostRemoteAPIKloudCheckTemplateOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIKloudCheckTemplateOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIKloudCheckTemplateOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/Kloud.checkTemplate][%d] postRemoteApiKloudCheckTemplateOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIKloudCheckTemplateOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIKloudCheckTemplateUnauthorized creates a PostRemoteAPIKloudCheckTemplateUnauthorized with default headers values
func NewPostRemoteAPIKloudCheckTemplateUnauthorized() *PostRemoteAPIKloudCheckTemplateUnauthorized {
	return &PostRemoteAPIKloudCheckTemplateUnauthorized{}
}

/*PostRemoteAPIKloudCheckTemplateUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIKloudCheckTemplateUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIKloudCheckTemplateUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/Kloud.checkTemplate][%d] postRemoteApiKloudCheckTemplateUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIKloudCheckTemplateUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
