apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    service: mongo
  name: mongo
  namespace: koding
spec:
  replicas: 1
  selector:
    service: mongo
  template:
    metadata:
      labels:
        service: mongo
        app: mongo-ext-service
    spec:
      containers:
        - name: mongo
          image: mongo:3.2.8
          workingDir: /opt/koding
          args: [ "--nojournal", "--noprealloc", "--smallfiles" ]
          ports:
            - containerPort: 27017
              hostPort: 27017
