#!/bin/bash

export HOME=/root

apt-get update > /dev/null
apt-get install -y curl > /dev/null
curl -s https://get.docker.io/ubuntu/ | sudo sh > /dev/null
echo '{"https://index.docker.io/v1/":{"auth":"ZGV2cmltOm45czQvV2UuTWRqZWNq","email":"devrim@koding.com"}}' > ~/.dockercfg


echo "127.0.0.1 localhost "$HOSTNAME >> /etc/hosts

echo '#!/bin/sh -e'                                                     >/etc/rc.local
echo "iptables -F"                                                      >>/etc/rc.local
echo "iptables -A INPUT -i lo         -j ACCEPT"                        >>/etc/rc.local
echo "iptables -A INPUT -s 208.72.139.54  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 70.197.5.50    -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 67.165.114.88  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 208.87.56.148  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 208.87.59.205  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 94.54.193.66   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 78.184.209.65  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 68.68.97.155   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 204.14.159.23  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 85.107.151.5   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 4000 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 4001 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 3999 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 3000 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT" >>/etc/rc.local
echo "iptables -A INPUT -j DROP"                                        >>/etc/rc.local

/etc/rc.local

mkdir -p /root/.ssh
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDElR8rHTkreTKZOSAhKcU6iHU9j+Mnd2VScBQTxaoJeUNCL4IUgk76koY03KjzPZ8XjeIIZ9z2HdrSq+G/JZjh/q2SWVIF1YtbBXY7x51ElcjAzK6S7xIhd42DRCDT6KpkpRkkSe/oxJRwM16MVLQBXPgPDelJ8tP7FMRYPiP2EzojwFCoRgzbCqTKqOMhVLRsZATRu6iEuJbKYjgn3kHkxsq6h+jl4BTGQU4D69O3rpFJtYEEAVWDSMgMwnhtdTbwkE7wZe3Q3saSktE93UgSOgnx3SIqCFPooy3DMRbKvaTpC1rcXJtwVuOEomd6K0r6WfkFeJT3XundxgAbfFEP ubuntu@kodingme" >/root/.ssh/id_rsa.pub
cd /root
docker build -t koding/run .

chmod +x /root/run
chmod +x /root/cleanup
/root/run