#!/bin/bash

export HOME=/root

apt-get update > /dev/null
apt-get install -y curl > /dev/null
curl -s https://get.docker.io/ubuntu/ | sudo sh > /dev/null
echo '{"https://index.docker.io/v1/":{"auth":"ZGV2cmltOm45czQvV2UuTWRqZWNq","email":"devrim@koding.com"}}' > ~/.dockercfg


echo "127.0.0.1 localhost "$HOSTNAME >> /etc/hosts

echo '#!/bin/sh -e'                                                     >/etc/rc.local
echo "iptables -F"                                                      >>/etc/rc.local
echo "iptables -A INPUT -i lo         -j ACCEPT"                        >>/etc/rc.local
echo "iptables -A INPUT -s 208.72.139.54  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 70.197.5.50    -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 67.165.114.88  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 208.87.56.148  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 208.87.59.205  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 94.54.193.66   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 78.184.209.65  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 68.68.97.155   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 204.14.159.23  -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -s 85.107.151.5   -j ACCEPT"                    >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 4000 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 3999 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -p tcp --dport 3000 -j ACCEPT"                  >>/etc/rc.local
echo "iptables -A INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT" >>/etc/rc.local
echo "iptables -A INPUT -j DROP"                                        >>/etc/rc.local

/etc/rc.local


cd /root


docker build -t koding/run .

chmod +x /root/prepare
/root/prepare

chmod +x /root/run
chmod +x /root/cleanup
/root/run