#!/bin/bash

trap ctrl_c INT TERM KILL
function ctrl_c() { kill -KILL $pid $$; }

path=$@
watchfolder=$(dirname $1)
command="node $path"

# echo
# echo if you want to understand what this script is doing, un-comment the line below.
# echo [watch-node $$] running $command and daemonizing, watching folder $watchfolder every 2 secs.
# echo

$command &
pid=$!
while [[ true ]]; do

	files=$(find -L $watchfolder -type f -newermt '2 seconds ago' | grep -v "\.test\." | grep -v "models\.json")

	if [[ $files != "" ]]; then
		echo [watch-node $$] files changed [$files] killing $pid $command
		kill -KILL $pid >/dev/null
		echo [watch-node $$] new pid is $pid
	fi
	if ! (ps -p $pid >/dev/null); then
		$command &
		pid=$!
		echo "[watch-node $$] process (re)started new pid $pid cmd: $command"
	fi
	sleep 2
done
