option '-c', '--config [CONFIG]', 'select a config file (default is prod)'


processes = new(require 'processes')


task "install", 'install packages',(options)->
  processes.run
    cmd : "npm i ldapjs@0.4.8"
    log : yes

task "build",'builds sharedhosting client',(options)->
  console.log "run npm i ldapjs@0.4.8"


task 'run','run sharedHosting',(options)->

  options.config ?= "config-dev"

  processes.run
    name    : "sharedhosting kite"
    cmd     : "coffee index.coffee -c #{options.config} --sharedHosting"
    restart : yes
    stdout  : process.stdout
    stderr  : process.stderr
    



