package j_reward_campaign

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJRewardCampaignIsValidReader is a Reader for the PostRemoteAPIJRewardCampaignIsValid structure.
type PostRemoteAPIJRewardCampaignIsValidReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJRewardCampaignIsValidReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJRewardCampaignIsValidOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIJRewardCampaignIsValidUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJRewardCampaignIsValidOK creates a PostRemoteAPIJRewardCampaignIsValidOK with default headers values
func NewPostRemoteAPIJRewardCampaignIsValidOK() *PostRemoteAPIJRewardCampaignIsValidOK {
	return &PostRemoteAPIJRewardCampaignIsValidOK{}
}

/*PostRemoteAPIJRewardCampaignIsValidOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIJRewardCampaignIsValidOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIJRewardCampaignIsValidOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JRewardCampaign.isValid][%d] postRemoteApiJRewardCampaignIsValidOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJRewardCampaignIsValidOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIJRewardCampaignIsValidUnauthorized creates a PostRemoteAPIJRewardCampaignIsValidUnauthorized with default headers values
func NewPostRemoteAPIJRewardCampaignIsValidUnauthorized() *PostRemoteAPIJRewardCampaignIsValidUnauthorized {
	return &PostRemoteAPIJRewardCampaignIsValidUnauthorized{}
}

/*PostRemoteAPIJRewardCampaignIsValidUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIJRewardCampaignIsValidUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIJRewardCampaignIsValidUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JRewardCampaign.isValid][%d] postRemoteApiJRewardCampaignIsValidUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIJRewardCampaignIsValidUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
