package j_reward_campaign

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJRewardCampaignUpdateIDReader is a Reader for the PostRemoteAPIJRewardCampaignUpdateID structure.
type PostRemoteAPIJRewardCampaignUpdateIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJRewardCampaignUpdateIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJRewardCampaignUpdateIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJRewardCampaignUpdateIDOK creates a PostRemoteAPIJRewardCampaignUpdateIDOK with default headers values
func NewPostRemoteAPIJRewardCampaignUpdateIDOK() *PostRemoteAPIJRewardCampaignUpdateIDOK {
	return &PostRemoteAPIJRewardCampaignUpdateIDOK{}
}

/*PostRemoteAPIJRewardCampaignUpdateIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJRewardCampaignUpdateIDOK struct {
	Payload *models.JRewardCampaign
}

func (o *PostRemoteAPIJRewardCampaignUpdateIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JRewardCampaign.update/{id}][%d] postRemoteApiJRewardCampaignUpdateIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJRewardCampaignUpdateIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JRewardCampaign)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
