package social_notification

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPISocialNotificationFetchReader is a Reader for the PostRemoteAPISocialNotificationFetch structure.
type PostRemoteAPISocialNotificationFetchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPISocialNotificationFetchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPISocialNotificationFetchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPISocialNotificationFetchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPISocialNotificationFetchOK creates a PostRemoteAPISocialNotificationFetchOK with default headers values
func NewPostRemoteAPISocialNotificationFetchOK() *PostRemoteAPISocialNotificationFetchOK {
	return &PostRemoteAPISocialNotificationFetchOK{}
}

/*PostRemoteAPISocialNotificationFetchOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPISocialNotificationFetchOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPISocialNotificationFetchOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialNotification.fetch][%d] postRemoteApiSocialNotificationFetchOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPISocialNotificationFetchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPISocialNotificationFetchUnauthorized creates a PostRemoteAPISocialNotificationFetchUnauthorized with default headers values
func NewPostRemoteAPISocialNotificationFetchUnauthorized() *PostRemoteAPISocialNotificationFetchUnauthorized {
	return &PostRemoteAPISocialNotificationFetchUnauthorized{}
}

/*PostRemoteAPISocialNotificationFetchUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPISocialNotificationFetchUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPISocialNotificationFetchUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialNotification.fetch][%d] postRemoteApiSocialNotificationFetchUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPISocialNotificationFetchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
