package j_team_invitation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJTeamInvitationByCodeParams creates a new JTeamInvitationByCodeParams object
// with the default values initialized.
func NewJTeamInvitationByCodeParams() *JTeamInvitationByCodeParams {
	var ()
	return &JTeamInvitationByCodeParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJTeamInvitationByCodeParamsWithTimeout creates a new JTeamInvitationByCodeParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJTeamInvitationByCodeParamsWithTimeout(timeout time.Duration) *JTeamInvitationByCodeParams {
	var ()
	return &JTeamInvitationByCodeParams{

		timeout: timeout,
	}
}

// NewJTeamInvitationByCodeParamsWithContext creates a new JTeamInvitationByCodeParams object
// with the default values initialized, and the ability to set a context for a request
func NewJTeamInvitationByCodeParamsWithContext(ctx context.Context) *JTeamInvitationByCodeParams {
	var ()
	return &JTeamInvitationByCodeParams{

		Context: ctx,
	}
}

/*JTeamInvitationByCodeParams contains all the parameters to send to the API endpoint
for the j team invitation by code operation typically these are written to a http.Request
*/
type JTeamInvitationByCodeParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) WithTimeout(timeout time.Duration) *JTeamInvitationByCodeParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) WithContext(ctx context.Context) *JTeamInvitationByCodeParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) WithBody(body models.DefaultSelector) *JTeamInvitationByCodeParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j team invitation by code params
func (o *JTeamInvitationByCodeParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JTeamInvitationByCodeParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
