package j_team_invitation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJTeamInvitationRemoveParams creates a new JTeamInvitationRemoveParams object
// with the default values initialized.
func NewJTeamInvitationRemoveParams() *JTeamInvitationRemoveParams {
	var ()
	return &JTeamInvitationRemoveParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJTeamInvitationRemoveParamsWithTimeout creates a new JTeamInvitationRemoveParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJTeamInvitationRemoveParamsWithTimeout(timeout time.Duration) *JTeamInvitationRemoveParams {
	var ()
	return &JTeamInvitationRemoveParams{

		timeout: timeout,
	}
}

// NewJTeamInvitationRemoveParamsWithContext creates a new JTeamInvitationRemoveParams object
// with the default values initialized, and the ability to set a context for a request
func NewJTeamInvitationRemoveParamsWithContext(ctx context.Context) *JTeamInvitationRemoveParams {
	var ()
	return &JTeamInvitationRemoveParams{

		Context: ctx,
	}
}

/*JTeamInvitationRemoveParams contains all the parameters to send to the API endpoint
for the j team invitation remove operation typically these are written to a http.Request
*/
type JTeamInvitationRemoveParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) WithTimeout(timeout time.Duration) *JTeamInvitationRemoveParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) WithContext(ctx context.Context) *JTeamInvitationRemoveParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) WithBody(body models.DefaultSelector) *JTeamInvitationRemoveParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) WithID(id string) *JTeamInvitationRemoveParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the j team invitation remove params
func (o *JTeamInvitationRemoveParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JTeamInvitationRemoveParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
