machine:
  koding_always_on: true
  koding_mounts:
    default: "/var/lib/koding/app"
variable:
- name: web_port
  default: 8080
cloudinit:
  write_files:
  - path: "/var/lib/koding/run"
    permissions: 0755
    owner: "${var.koding_account_profile_nickname}:${var.koding_account_profile_nickname}"
    content: |-
      #!/bin/bash
      set -euo pipefail
      docker run     \
        --rm         \
        --name app   \
        -p ${var.userInput_web_port}:${var.userInput_web_port} \
        -e PORT=${var.userInput_web_port} \
        -v /var/lib/koding/app:/app \
        rjeczalik/buildstep:latest  \
        /bin/bash -c '/build/builder && /start web'
  package_update: true
  packages:
  - docker
  - docker.io
  - git
  - git-core
  runcmd:
  - usermod -a -G docker ${var.koding_account_profile_nickname}
  - mkdir -p /var/lib/koding/app
  - chown -R ${var.koding_account_profile_nickname}:${var.koding_account_profile_nickname}
    /var/lib/koding/app
  - docker pull rjeczalik/buildstep:latest
  - echo
  - echo Your application stack is ready to use!
  - echo
