module.exports =
  PARTICIPANT_STATUS_OFFLINE    : 'PARTICIPANT_STATUS_OFFLINE'
  PARTICIPANT_STATUS_CONNECTED  : 'PARTICIPANT_STATUS_CONNECTED'
  PARTICIPANT_STATUS_PUBLISHING : 'PARTICIPANT_STATUS_PUBLISHING'

