package j_provisioner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJProvisionerSetAccessParams creates a new JProvisionerSetAccessParams object
// with the default values initialized.
func NewJProvisionerSetAccessParams() *JProvisionerSetAccessParams {
	var ()
	return &JProvisionerSetAccessParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJProvisionerSetAccessParamsWithTimeout creates a new JProvisionerSetAccessParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJProvisionerSetAccessParamsWithTimeout(timeout time.Duration) *JProvisionerSetAccessParams {
	var ()
	return &JProvisionerSetAccessParams{

		timeout: timeout,
	}
}

// NewJProvisionerSetAccessParamsWithContext creates a new JProvisionerSetAccessParams object
// with the default values initialized, and the ability to set a context for a request
func NewJProvisionerSetAccessParamsWithContext(ctx context.Context) *JProvisionerSetAccessParams {
	var ()
	return &JProvisionerSetAccessParams{

		Context: ctx,
	}
}

/*JProvisionerSetAccessParams contains all the parameters to send to the API endpoint
for the j provisioner set access operation typically these are written to a http.Request
*/
type JProvisionerSetAccessParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j provisioner set access params
func (o *JProvisionerSetAccessParams) WithTimeout(timeout time.Duration) *JProvisionerSetAccessParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j provisioner set access params
func (o *JProvisionerSetAccessParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j provisioner set access params
func (o *JProvisionerSetAccessParams) WithContext(ctx context.Context) *JProvisionerSetAccessParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j provisioner set access params
func (o *JProvisionerSetAccessParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j provisioner set access params
func (o *JProvisionerSetAccessParams) WithBody(body models.DefaultSelector) *JProvisionerSetAccessParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j provisioner set access params
func (o *JProvisionerSetAccessParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the j provisioner set access params
func (o *JProvisionerSetAccessParams) WithID(id string) *JProvisionerSetAccessParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the j provisioner set access params
func (o *JProvisionerSetAccessParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JProvisionerSetAccessParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
