package j_provisioner

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJProvisionerDeleteIDReader is a Reader for the PostRemoteAPIJProvisionerDeleteID structure.
type PostRemoteAPIJProvisionerDeleteIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJProvisionerDeleteIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJProvisionerDeleteIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJProvisionerDeleteIDOK creates a PostRemoteAPIJProvisionerDeleteIDOK with default headers values
func NewPostRemoteAPIJProvisionerDeleteIDOK() *PostRemoteAPIJProvisionerDeleteIDOK {
	return &PostRemoteAPIJProvisionerDeleteIDOK{}
}

/*PostRemoteAPIJProvisionerDeleteIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJProvisionerDeleteIDOK struct {
	Payload PostRemoteAPIJProvisionerDeleteIDOKBody
}

func (o *PostRemoteAPIJProvisionerDeleteIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JProvisioner.delete/{id}][%d] postRemoteApiJProvisionerDeleteIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJProvisionerDeleteIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJProvisionerDeleteIDOKBody post remote API j provisioner delete ID o k body
swagger:model PostRemoteAPIJProvisionerDeleteIDOKBody
*/
type PostRemoteAPIJProvisionerDeleteIDOKBody struct {
	models.JProvisioner

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJProvisionerDeleteIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJProvisionerDeleteIDOKBodyAO0 models.JProvisioner
	if err := swag.ReadJSON(raw, &postRemoteAPIJProvisionerDeleteIDOKBodyAO0); err != nil {
		return err
	}
	o.JProvisioner = postRemoteAPIJProvisionerDeleteIDOKBodyAO0

	var postRemoteAPIJProvisionerDeleteIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJProvisionerDeleteIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJProvisionerDeleteIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJProvisionerDeleteIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJProvisionerDeleteIDOKBodyAO0, err := swag.WriteJSON(o.JProvisioner)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJProvisionerDeleteIDOKBodyAO0)

	postRemoteAPIJProvisionerDeleteIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJProvisionerDeleteIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j provisioner delete ID o k body
func (o *PostRemoteAPIJProvisionerDeleteIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JProvisioner.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
