require './messagesstore'
require './selectedchannelthreadidstore'
require './selectedmessagethreadidstore'
require './channelthreadsstore'
require './messagethreadsstore'
require './channelsstore'
require './channelflagsstore'
require './messageflagsstore'
require './followedpublicchannelidsstore'
require './followedprivatechannelidsstore'
require './popularchannelidsstore'
require './channelparticipantidsstore'
require './channelpopularmessageidsstore'
require './suggestions/suggestionsquerystore'
require './suggestions/suggestionsflagsstore'
require './suggestions/suggestionsstore'
require './suggestions/suggestionsselectedindexstore'
require './suggestions/suggestionsgetters'
require './messagelikersstore'
require './chatinput/chatinputchannelsquerystore'
require './chatinput/chatinputchannelsselectedindexstore'
require './chatinput/chatinputchannelsvisibilitystore'
require './chatinput/chatinputusersquerystore'
require './chatinput/chatinputusersselectedindexstore'
require './chatinput/chatinputusersvisibilitystore'
require './chatinput/chatinputsearchquerystore'
require './chatinput/chatinputsearchselectedindexstore'
require './chatinput/chatinputsearchvisibilitystore'
require './chatinput/chatinputsearchstore'
require './chatinput/chatinputsearchgetters'

# module tests
require 'activity/flux/chatinput/tests'

