module.exports = [
  'IDELoaded'
  #'CollaborationStarted'
  #'ChangelogChannelViewed'
  #'OtherChannelViewed'
  #'NewPrivateMessageOpened'
  #'PrivateMessagesViewed'
  #'VMSettingsOpened'
  #'WorkspaceSettingsOpened'
  'IDESettingsOpened'
  'StacksViewed'
  'VMsViewed'
  'CredentialsViewed'
  'MyTeamViewed'
  'TeamBillingViewed'
  'KodingUtilitiesViewed'
  'MyAccountViewed'
]
