module.exports = {
  'LOAD_SIDEBAR_ITEM_VISIBILITIES_BEGIN'
  'LOAD_SIDEBAR_ITEM_VISIBILITIES_SUCCESS'

  'MAKE_SIDEBAR_ITEM_VISIBLE_BEGIN'
  'MAKE_SIDEBAR_ITEM_VISIBLE_SUCCESS'

  'MAKE_SIDEBAR_ITEM_HIDDEN_BEGIN'
  'MAKE_SIDEBAR_ITEM_HIDDEN_SUCCESS'
}
