package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRemoteAPIPaymentFetchGroupCreditCardParams creates a new PostRemoteAPIPaymentFetchGroupCreditCardParams object
// with the default values initialized.
func NewPostRemoteAPIPaymentFetchGroupCreditCardParams() *PostRemoteAPIPaymentFetchGroupCreditCardParams {

	return &PostRemoteAPIPaymentFetchGroupCreditCardParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIPaymentFetchGroupCreditCardParamsWithTimeout creates a new PostRemoteAPIPaymentFetchGroupCreditCardParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIPaymentFetchGroupCreditCardParamsWithTimeout(timeout time.Duration) *PostRemoteAPIPaymentFetchGroupCreditCardParams {

	return &PostRemoteAPIPaymentFetchGroupCreditCardParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIPaymentFetchGroupCreditCardParamsWithContext creates a new PostRemoteAPIPaymentFetchGroupCreditCardParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIPaymentFetchGroupCreditCardParamsWithContext(ctx context.Context) *PostRemoteAPIPaymentFetchGroupCreditCardParams {

	return &PostRemoteAPIPaymentFetchGroupCreditCardParams{

		Context: ctx,
	}
}

/*PostRemoteAPIPaymentFetchGroupCreditCardParams contains all the parameters to send to the API endpoint
for the post remote API payment fetch group credit card operation typically these are written to a http.Request
*/
type PostRemoteAPIPaymentFetchGroupCreditCardParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post remote API payment fetch group credit card params
func (o *PostRemoteAPIPaymentFetchGroupCreditCardParams) WithTimeout(timeout time.Duration) *PostRemoteAPIPaymentFetchGroupCreditCardParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API payment fetch group credit card params
func (o *PostRemoteAPIPaymentFetchGroupCreditCardParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API payment fetch group credit card params
func (o *PostRemoteAPIPaymentFetchGroupCreditCardParams) WithContext(ctx context.Context) *PostRemoteAPIPaymentFetchGroupCreditCardParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API payment fetch group credit card params
func (o *PostRemoteAPIPaymentFetchGroupCreditCardParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIPaymentFetchGroupCreditCardParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
