package payment

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRemoteAPIPaymentFetchGroupInvoicesParams creates a new PostRemoteAPIPaymentFetchGroupInvoicesParams object
// with the default values initialized.
func NewPostRemoteAPIPaymentFetchGroupInvoicesParams() *PostRemoteAPIPaymentFetchGroupInvoicesParams {

	return &PostRemoteAPIPaymentFetchGroupInvoicesParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIPaymentFetchGroupInvoicesParamsWithTimeout creates a new PostRemoteAPIPaymentFetchGroupInvoicesParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIPaymentFetchGroupInvoicesParamsWithTimeout(timeout time.Duration) *PostRemoteAPIPaymentFetchGroupInvoicesParams {

	return &PostRemoteAPIPaymentFetchGroupInvoicesParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIPaymentFetchGroupInvoicesParamsWithContext creates a new PostRemoteAPIPaymentFetchGroupInvoicesParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIPaymentFetchGroupInvoicesParamsWithContext(ctx context.Context) *PostRemoteAPIPaymentFetchGroupInvoicesParams {

	return &PostRemoteAPIPaymentFetchGroupInvoicesParams{

		Context: ctx,
	}
}

/*PostRemoteAPIPaymentFetchGroupInvoicesParams contains all the parameters to send to the API endpoint
for the post remote API payment fetch group invoices operation typically these are written to a http.Request
*/
type PostRemoteAPIPaymentFetchGroupInvoicesParams struct {
	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post remote API payment fetch group invoices params
func (o *PostRemoteAPIPaymentFetchGroupInvoicesParams) WithTimeout(timeout time.Duration) *PostRemoteAPIPaymentFetchGroupInvoicesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API payment fetch group invoices params
func (o *PostRemoteAPIPaymentFetchGroupInvoicesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API payment fetch group invoices params
func (o *PostRemoteAPIPaymentFetchGroupInvoicesParams) WithContext(ctx context.Context) *PostRemoteAPIPaymentFetchGroupInvoicesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API payment fetch group invoices params
func (o *PostRemoteAPIPaymentFetchGroupInvoicesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIPaymentFetchGroupInvoicesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
