#!/bin/bash

cd $(dirname $0)

MAX_TRY_COUNT=3

runTests() {
  a=$1

  if [ ! "$a" ]; then
    for i in ./output/*;do
      if [ -d "$i" ];then
          if [ "$i" == "./output/helpers" ] || [ "$i" == "./output/utils" ]; then
            echo "skipping $i"
          else
            echo "running $i test"
            command="nightwatch --group $i"

            counter=0
            until $command
            do
              counter=$((counter + 1))
              if [ $counter -eq $MAX_TRY_COUNT ]
              then
                exit 1
              fi
            done
          fi
      fi
    done
  else
    echo "running single test: $a"
    command="nightwatch --group ./output/$a"
    counter=0
    until $command
    do
      counter=$((counter + 1))
      if [ $counter -eq $MAX_TRY_COUNT ]
      then
        exit 1
      fi
    done
  fi
}

echo 'deleting output folder'
rm -rf ./output

echo 'compiling coffee files'
gulp

echo 'running tests'

runTests $1
