#!/bin/bash

cd $(dirname $0)

MAX_TRY_COUNT=3

runTests() {
  SUITE=$1
  SUBSUITE=$2

  if [ ! "$SUITE" ]; then
    for i in ./output/*;do
      if [ -d "$i" ];then
          if [ "$i" == "./output/helpers" ] || [ "$i" == "./output/utils" ]; then
            echo "skipping $i"
          else
            echo "running $i test suite"
            command="nightwatch --group $i"

            counter=0
            until $command
            do
              counter=$((counter + 1))
              if [ $counter -eq $MAX_TRY_COUNT ]
              then
                exit 1
              fi
            done
          fi
      fi
    done
  else
    echo "running single test suite: $SUITE $SUBSUITE"

    if [ ! "$SUBSUITE" ]; then
      command="nightwatch --group ./output/$SUITE"
    else
      command="nightwatch --group ./output/$SUITE/$SUBSUITE.js"
    fi

    counter=0
    until $command
    do
      counter=$((counter + 1))
      if [ $counter -eq $MAX_TRY_COUNT ]
      then
        exit 1
      fi
    done
  fi
}

echo 'deleting output folder'
rm -rf ./output

echo 'compiling coffee files'
gulp

echo 'running tests'

runTests $1 $2
