module.exports = {
  'LOAD_USER_ENVIRONMENT_BEGIN'
  'LOAD_USER_ENVIRONMENT_FAIL'
  'LOAD_USER_ENVIRONMENT_SUCCESS'

  'LOAD_USER_STACKS_BEGIN'
  'LOAD_USER_STACKS_FAIL'
  'LOAD_USER_STACKS_SUCCESS'

  'MACHINE_UPDATED'
  'STACK_UPDATED'
  'REINIT_STACK'

  'INVITATION_ACCEPTED'
  'COLLABORATION_INVITATION_REJECTED'
  'SHARED_VM_INVITATION_REJECTED'

  'SHOW_MANAGED_MACHINE_ADDED_MODAL'
  'HIDE_MANAGED_MACHINE_ADDED_MODAL'

  'WORKSPACE_CREATED'
  'WORKSPACE_DELETED'
  'WORKSPACE_SELECTED'
  'SHOW_ADD_WORKSPACE_VIEW'
  'HIDE_ADD_WORKSPACE_VIEW'
  'WORKSPACE_DELETED_FAIL'
  'WORKSPACE_COULD_NOT_CREATE'
  'SHOW_DELETE_WORKSPACE_WIDGET'
  'HIDE_DELETE_WORKSPACE_WIDGET'
  'UPDATE_WORKSPACE_CHANNEL_ID'

  'MACHINE_SELECTED'

  'MACHINE_LIST_ITEM_CREATED'
  'MACHINE_LIST_ITEM_DELETED'

  'SET_ACTIVE_INVITATION_MACHINE_ID'
  'SET_ACTIVE_LEAVING_SHARED_MACHINE_ID'

  'GROUP_STACKS_INCONSISTENT'
  'GROUP_STACKS_CONSISTENT'
}
