module.exports = {
  'LOAD_USER_ENVIRONMENT_BEGIN'
  'LOAD_USER_ENVIRONMENT_FAIL'
  'LOAD_USER_ENVIRONMENT_SUCCESS'

  'LOAD_USER_STACKS_BEGIN'
  'LOAD_USER_STACKS_FAIL'
  'LOAD_USER_STACKS_SUCCESS'

  'MACHINE_UPDATED'
  'STACK_UPDATED'

  'INVITATION_ACCEPTED'
  'COLLABORATION_INVITATION_REJECTED'
  'SHARED_VM_INVITATION_REJECTED'
}
