module.exports = [
  "AppController.coffee"
  "AppView.coffee"
  "messageeventhelper.coffee"
  "activitylistcontroller.coffee"
  "pinnedactivitylistcontroller.coffee"

  "sidebar/activitysidebar.coffee"
  "sidebar/sidebaritem.coffee"
  "sidebar/memberitem.coffee"
  "sidebar/messageitem.coffee"
  "sidebar/chatmemberitem.coffee"
  "sidebar/topicitem.coffee"
  "sidebar/pinneditem.coffee"

  "views/messagepane.coffee"

  # Activity commons
  "views/feedcoverphotoview.coffee"
  "views/likecount.coffee"
  "views/likesummaryview.coffee"
  "views/likeview.coffee"
  "views/likelink.coffee"
  "views/activityactions.coffee"
  "views/activitylistheader.coffee"
  "views/sharepopup.coffee"
  "views/activitytickeritem.coffee"
  "views/referalbox.coffee"
  "views/filterwarning.coffee"
  "views/activitymenuitem.coffee"

  "views/embedbox.coffee"
  "views/embedboxwidget.coffee"

  "views/embedbox/embedboxobjectview.coffee"
  "views/embedbox/embedboximageview.coffee"
  "views/embedbox/embedboxlinkviewdescription.coffee"
  "views/embedbox/embedboxlinkdisplayview.coffee"
  "views/embedbox/embedboxlinkviewimage.coffee"
  "views/embedbox/embedboxlinksview.coffee"
  "views/embedbox/embedboxlinkviewimageswitch.coffee"
  "views/embedbox/embedboxlinksviewitem.coffee"
  "views/embedbox/embedboxlinkviewprovider.coffee"
  "views/embedbox/embedboxlinkview.coffee"
  "views/embedbox/embedboxlinkviewtitle.coffee"
  "views/embedbox/embedboxlinkviewauthor.coffee"
  "views/embedbox/embedboxlinkviewcontent.coffee"

  "views/tags/TagViews.coffee"
  "views/tags/TagAutoCompleteController.coffee"

  "views/comments/inputform.coffee"
  "views/comments/editform.coffee"
  "views/comments/count.coffee"
  "views/comments/likeview.coffee"
  "views/comments/listpreviouslink.coffee"
  "views/comments/view.coffee"
  "views/comments/listviewcontroller.coffee"
  "views/comments/settingsbutton.coffee"
  "views/comments/deletemodal.coffee"
  "views/comments/listitemview.coffee"

  "views/inputview.coffee"
  "views/inputwidget.coffee"
  "views/inputeditwidget.coffee"
  "views/settingsview.coffee"

  "widgets/widgetcontroller.coffee"
  "widgets/widgetview.coffee"
  "widgets/widgetbutton.coffee"
  "widgets/activitywidgetformview.coffee"
  "widgets/statuswidget.coffee"
  "widgets/codesnippetwidget.coffee"
  "widgets/tutorialwidget.coffee"
  "widgets/discussionwidget.coffee"
  "widgets/blogpostwidget.coffee"

  "ContentDisplays/activitycontentdisplay.coffee"
  "ContentDisplays/StatusUpdate.coffee"
  "ContentDisplays/activitysideviews.coffee"
  "ContentDisplays/ActivityTicker.coffee"

  # Activity content displays commons
  "ContentDisplays/ContentDisplayAuthorAvatar.coffee"
  "ContentDisplays/ContentDisplayMeta.coffee"
  "ContentDisplays/ContentDisplayTags.coffee"
  "ContentDisplays/ContentDisplayComments.coffee"
  "ContentDisplays/ContentDisplayScoreBoard.coffee"

  # Activity List Items
  "views/activitylistitem.coffee"

  "styl/activity.styl"
  "styl/activity.responsive.styl"
]
