module.exports = [
  "AppController.coffee"
  "AppView.coffee"
  "activitylistcontroller.coffee"
  "pinnedactivitylistcontroller.coffee"

  "sidebar/searchmodal.coffee"
  "sidebar/yourtopicsmodal.coffee"
  "sidebar/conversationsmodal.coffee"
  "sidebar/chatsearchmodal.coffee"
  "sidebar/activitysidebar.coffee"
  "sidebar/activitysideview.coffee"
  "sidebar/sidebaritem.coffee"
  "sidebar/memberitem.coffee"
  "sidebar/messageitemtext.coffee"
  "sidebar/messageitemicon.coffee"
  "sidebar/messageitem.coffee"
  "sidebar/topicitem.coffee"
  "sidebar/pinneditem.coffee"
  "sidebar/groupdescription.coffee"

  "views/basewidget.coffee"
  "views/guidewidget.coffee"
  "views/topicswidget.coffee"
  "views/universitywidget.coffee"
  "views/widgetsbar.coffee"

  "views/messagepane.coffee"
  "views/topicmessagepane.coffee"
  "views/activitypane.coffee"
  "views/announcementpane.coffee"

  "views/filterlinks.coffee"

  # Activity commons
  "views/feedcoverphotoview.coffee"
  "views/likelink.coffee"
  "views/replylikeview.coffee"
  "views/likecount.coffee"
  "views/likesummaryview.coffee"
  "views/likeview.coffee"
  "views/activityactions.coffee"
  "views/activitylistheader.coffee"
  "views/sharepopup.coffee"
  "views/filterwarning.coffee"
  "views/activitymenuitem.coffee"
  "views/chatheadautocompleteitem.coffee"
  "views/alltopicsmodal.coffee"
  "views/activityautocompleteuseritemview.coffee"
  "views/searchinputview.coffee"

  "views/embedbox.coffee"
  "views/embedboxwidget.coffee"

  "views/embedbox/embedboxobjectview.coffee"
  "views/embedbox/embedboximageview.coffee"
  "views/embedbox/embedboxlinkviewdescription.coffee"
  "views/embedbox/embedboxlinkdisplayview.coffee"
  "views/embedbox/embedboxlinkviewimage.coffee"
  "views/embedbox/embedboxlinksview.coffee"
  "views/embedbox/embedboxlinkviewimageswitch.coffee"
  "views/embedbox/embedboxlinksviewitem.coffee"
  "views/embedbox/embedboxlinkviewprovider.coffee"
  "views/embedbox/embedboxlinkview.coffee"
  "views/embedbox/embedboxlinkviewtitle.coffee"
  "views/embedbox/embedboxlinkviewauthor.coffee"
  "views/embedbox/embedboxlinkviewcontent.coffee"

  "views/tags/TagViews.coffee"
  "views/tags/TagAutoCompleteController.coffee"

  "views/inputview.coffee"
  "views/inputwidget.coffee"
  "views/inputhelperview.coffee"
  "views/inputeditwidget.coffee"
  "views/settingsview.coffee"

  "views/activitytabhandle.coffee"
  "views/activitycontentpane.coffee"
  "views/activitysearchresultspane.coffee"

  "ContentDisplays/activitycontentdisplay.coffee"
  "ContentDisplays/StatusUpdate.coffee"

  # Activity content displays commons
  "ContentDisplays/ContentDisplayAuthorAvatar.coffee"
  # "ContentDisplays/ContentDisplayMeta.coffee"
  # "ContentDisplays/ContentDisplayTags.coffee"
  "ContentDisplays/ContentDisplayComments.coffee"

  # Activity List Items
  "views/activitylistitem.coffee"

  "views/comments/inputview.coffee"
  "views/comments/inputwidget.coffee"
  "views/comments/inputeditwidget.coffee"
  "views/comments/count.coffee"
  "views/comments/likeview.coffee"
  "views/comments/listpreviouslink.coffee"
  "views/comments/view.coffee"
  "views/comments/replyview.coffee"
  "views/comments/listviewcontroller.coffee"
  "views/comments/replylistviewcontroller.coffee"
  "views/comments/settingsbutton.coffee"
  "views/comments/deletemodal.coffee"
  "views/comments/listitemview.coffee"
  "views/comments/replylistitemview.coffee"
  "views/comments/timeview.coffee"

  "views/privatemessage/listitem.coffee"
  "views/privatemessage/form.coffee"
  "views/privatemessage/kodingbot.coffee"
  "views/privatemessage/pane.coffee"
  "views/privatemessage/recipientmodal.coffee"
  "views/privatemessage/replypreviouslink.coffee"
  "views/privatemessage/replyinputview.coffee"
  "views/privatemessage/replyinputwidget.coffee"
  "views/privatemessage/inputwidget.coffee"
  "views/privatemessage/loadtest.coffee"
  "views/privatemessage/settingsview.coffee"

  "views/buymachinemodal.coffee"

  "styl/activity.styl"
  "styl/activity.responsive.styl"
]
