{exec} = require "child_process"
throw new Error "You are running this from wrong directory. (go to ./terminaljs-lite/)" unless __dirname.match "/terminaljs-lite"
  


task 'buildClient', 'just build js files and copy to node_modules',(options)->
  exec """rm -rf ../node_modules/terminaljs-lite/js/* && 
          coffee -b -c -o ../node_modules/terminaljs-lite/js/ src/"""
  ,(err,stdout,stderr)->
    unless err and stderr
      console.log "JS build complete",stdout
    else
      console.log err,stderr
  

task 'build', 'optimized version for deployment',(options)->
  

  exec """make -C src bin && rm -fR ../node_modules/terminaljs-lite && 
          cp -fR ../terminaljs-lite ../node_modules/ && 
          rm -rf ../node_modules/terminaljs-lite/js/* && 
          coffee -b -c -o ../node_modules/terminaljs-lite/js/ src/"""
  ,(err,stdout,stderr)->
    unless err and stderr
      console.log "Build complete",stdout
    else
      console.log err,stderr


