# -*- mode: ruby -*-
# vi: set ft=ruby :

hosts = {
        "koding.local"   => "10.5.5.2",
        "rabbitmq.local" => "10.5.5.2",
        "cl.local"       => "10.5.5.2",
        "ldap.local"     => "10.5.5.2",
        "cephClient.local" => "10.5.5.2",
}

workers = {
        "web0.local"     => "10.5.5.6",
        "web1.local"     => "10.5.5.7",
        "web3.local"     => "10.5.5.8",
        "web4.local"     => "10.5.5.9",
}

if ENV["WEB_WORKERS"]
    hosts.update(workers)
else
    puts "**** NOTE *****"
    puts "if you want to start additional NodeJS servers ( #{workers.keys.join(', ')} )"
    puts "set env variable with 'export WEB_WORKERS=true'"
    puts "*******"
end

count=0
File.open('/etc/hosts').each_line do |s|
    hosts.each_pair do |host,ip|
        host = host.gsub(".","\\.")
        ip = ip.gsub(".","\\.")
        if s.match(/^#{ip}\s+#{host}/)
            count += 1
        end
    end
end

unless count.eql?(hosts.length)
    puts "******************** WARNING !!! ****************\n\n"
    puts "please add the following hosts to the /etc/hosts:"
    hosts.each_pair do |host,ip|
        puts "#{ip} #{host}"
    end
    puts "\n******************** WARNING !!! ****************\n\n"
end


private_ssh_key = "vagrant.pem"
template_centos_url = "https://s3.amazonaws.com/koding-vagrant-Lti5bj61mVnfMkhX/centos64.box"
template_cloudlinux_url = "https://s3.amazonaws.com/koding-vagrant-Lti5bj61mVnfMkhX/cloudlinux64.box"
template_ubuntu121064_url = "https://s3.amazonaws.com/koding-vagrant-Lti5bj61mVnfMkhX/ubuntu1210-64-4.0.box"

koding_git_dir = ENV['PWD']
cookbooks_dir = "#{koding_git_dir}/vagrant/cookbooks"
roles_dir = "#{koding_git_dir}/vagrant/roles"


# start VMs only in the toplevel git directory
toplevel = `/usr/bin/git rev-parse --show-toplevel`.chop.downcase
unless toplevel.eql?(koding_git_dir.downcase)
    STDERR.puts "you have to change directory to the git toplevel first"
    exit 1
end

File.new(private_ssh_key).chmod(0600)

Vagrant::Config.run do |config|
    config.ssh.private_key_path = private_ssh_key

    # ---- All-in-one kodingServer configuration -------
    config.vm.define :kodingServer do |kodingServer_config|

          kodingServer_config.vm.box = "ubuntu1210-64-4.0"
          kodingServer_config.vm.box_url = template_ubuntu121064_url
          kodingServer_config.vm.network :hostonly, hosts["koding.local"]
          kodingServer_config.vm.host_name = "koding.local"
          kodingServer_config.vm.share_folder "koding", "/opt/koding", koding_git_dir , :create => true, :map_uid => 'root', :map_gid => 'root'
          kodingServer_config.vm.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/koding", "1" ]
          kodingServer_config.vm.customize [
                                    "modifyvm", :id,
                                    "--memory", 1024,
                                    "--cpus", 2,
                                    "--name", "koding_VM"
                                  ]

          kodingServer_config.vm.provision :chef_solo do |chef|
            chef.cookbooks_path = cookbooks_dir
            chef.roles_path = roles_dir
            chef.add_role("base_server")
            chef.add_role("web_server_vagrant")
            chef.add_role("ceph-client_vagrant")
            chef.add_role("rabbitmq_server")
          end
    end
    # ----- end of All-in-one kodingServer configuration -----

end

