require './generictoggler.test'
require './machinedetails.test'
require './listitem.test'
require './connectedmachineslist.test'
require './sharedmachineslist.test'
require './virtualmachineslist.test'
require './stores/sharingsearchstore.test'
