#!/bin/bash

set -o errexit

services="mongodb postgresql rabbitmq-server redis-server"

function start_services () {
  for name in $services; do
    service $name start
  done
}

function init_mongodb() {
  chown --recursive mongodb:mongodb /var/lib/mongodb
  local tarball_url="https://github.com/koding/koding/raw/master/install/docker-mongo/default-db-dump.tar.bz2"

  curl --silent --location $tarball_url |
    tar --extract --bzip2 --directory /tmp/

  service mongodb start
  /opt/koding/wait.sh mongo

  mongorestore /tmp/dump

  rm -rf /tmp/dump
}

function init_postgresql() {
  chown --recursive postgres:postgres /var/lib/postgresql
  su postgres -c "/usr/lib/postgresql/9.3/bin/initdb --pgdata /var/lib/postgresql/9.3/main"
  service postgresql start
  go/src/socialapi/db/sql/definition/create.sh
  ./run migrate up
}

function init_databases() {
  [ -z "`ls --almost-all /var/lib/mongodb/`" ] && init_mongodb || :
  [ -z "`ls --almost-all /var/lib/postgresql/`" ] && init_postgresql || :
}

function handle_interrupt() {
  ./run exec supervisorctl stop all || :
  ./run exec supervisorctl shutdown || :
  pkill mongod
  for name in $services; do
    service $name stop || :
  done
}

trap handle_interrupt INT TERM

function run_backend(){
  init_databases
  start_services
  sleep 20
  nginx -c $(pwd)/nginx.conf
  ./run migrate up
  ./run exec supervisord -c supervisord.conf
  sleep 2
  tail --follow --lines +0 --quiet .logs/*.log
}

if [[ -z "$*" ]]; then
  git fetch origin
  git checkout -fq $TEST_SHA
  ver=$(git rev-parse --short HEAD)
  echo $ver > VERSION
  npm install --unsafe-perm
  git clone https://$TEST_GITHUB_TOKEN:x-oauth-basic@github.com/koding/vault.git
  pushd /opt/koding/vault
  git checkout -f ${TEST_BRANCH_NAME:-master}
  popd
  ./configure --config dev --host $TEST_HOSTNAME --hostname $TEST_HOSTNAME --publicPort 80 --version $ver
  go/build.sh
  make -C client dist
  run_backend
elif [[ "${1:0:1}" = '-' ]]; then
  ./configure $*
  run_backend
elif [[ $1 = "simple" ]]; then
  ./configure --host localhost --hostname localhost --publicPort 80
  run_backend
else
  exec "$@"
fi
