module.exports = {
  'SET_EMOJI_SELECTBOX_QUERY'
  'UNSET_EMOJI_SELECTBOX_QUERY'
  'SET_EMOJI_SELECTBOX_SELECTED_INDEX'
  'RESET_EMOJI_SELECTBOX_SELECTED_INDEX'
  'SET_EMOJI_SELECTBOX_VISIBILITY'
  'SET_EMOJI_SELECTBOX_TAB_INDEX'

  'SET_EMOJI_USAGE_COUNT'
  'INCREMENT_EMOJI_USAGE_COUNT'

  'CHAT_INPUT_SEARCH_BEGIN'
  'CHAT_INPUT_SEARCH_SUCCESS'
  'CHAT_INPUT_SEARCH_FAIL'
  'CHAT_INPUT_SEARCH_RESET'

  'SET_CHAT_INPUT_VALUE'

  'SET_DROPBOX_QUERY_AND_CONFIG'
  'SET_DROPBOX_SELECTED_INDEX'
  'MOVE_TO_NEXT_DROPBOX_SELECTED_INDEX'
  'MOVE_TO_PREV_DROPBOX_SELECTED_INDEX'
  'RESET_DROPBOX_SELECTED_INDEX'
  'RESET_DROPBOX'
}
