module.exports = {
  'SET_FILTERED_EMOJI_LIST_QUERY'
  'UNSET_FILTERED_EMOJI_LIST_QUERY'
  'SET_FILTERED_EMOJI_LIST_SELECTED_INDEX'
  'MOVE_TO_NEXT_FILTERED_EMOJI_LIST_INDEX'
  'MOVE_TO_PREV_FILTERED_EMOJI_LIST_INDEX'
  'RESET_FILTERED_EMOJI_LIST_SELECTED_INDEX'

  'SET_COMMON_EMOJI_LIST_SELECTED_INDEX'
  'RESET_COMMON_EMOJI_LIST_SELECTED_INDEX'
  'SET_COMMON_EMOJI_LIST_VISIBILITY'

  'SET_CHAT_INPUT_CHANNELS_QUERY'
  'UNSET_CHAT_INPUT_CHANNELS_QUERY'
  'SET_CHAT_INPUT_CHANNELS_SELECTED_INDEX'
  'MOVE_TO_NEXT_CHAT_INPUT_CHANNELS_INDEX'
  'MOVE_TO_PREV_CHAT_INPUT_CHANNELS_INDEX'
  'RESET_CHAT_INPUT_CHANNELS_SELECTED_INDEX'
  'SET_CHAT_INPUT_CHANNELS_VISIBILITY'

  'SET_CHAT_INPUT_USERS_QUERY'
  'UNSET_CHAT_INPUT_USERS_QUERY'
  'SET_CHAT_INPUT_USERS_SELECTED_INDEX'
  'MOVE_TO_NEXT_CHAT_INPUT_USERS_INDEX'
  'MOVE_TO_PREV_CHAT_INPUT_USERS_INDEX'
  'RESET_CHAT_INPUT_USERS_SELECTED_INDEX'
  'SET_CHAT_INPUT_USERS_VISIBILITY'
}

