module.exports = {
  'SET_FILTERED_EMOJI_LIST_QUERY'
  'UNSET_FILTERED_EMOJI_LIST_QUERY'
  'SET_FILTERED_EMOJI_LIST_SELECTED_INDEX'
  'MOVE_TO_NEXT_FILTERED_EMOJI_LIST_INDEX'
  'MOVE_TO_PREV_FILTERED_EMOJI_LIST_INDEX'
  'RESET_FILTERED_EMOJI_LIST_SELECTED_INDEX'

  'SET_COMMON_EMOJI_LIST_SELECTED_INDEX'
  'RESET_COMMON_EMOJI_LIST_SELECTED_INDEX'
  'SET_COMMON_EMOJI_LIST_VISIBILITY'
}

