all: log terminal_lib htmlify_lib diff_lib nodejs

log::
	cd log&&$(MAKE) $(MAKEGOALS)

terminal_lib::
	cd terminal&&$(MAKE) $(MAKECMDGOALS)

htmlify_lib::
	cd htmlify&&$(MAKE) $(MAKECMDGOALS)

diff_lib::
	cd diff&&$(MAKE) $(MAKECMDGOALS)

nodejs::
	cd nodejs&&$(MAKE) $(MAKECMDGOALS)


