package social_message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewSocialMessageBySlugParams creates a new SocialMessageBySlugParams object
// with the default values initialized.
func NewSocialMessageBySlugParams() *SocialMessageBySlugParams {
	var ()
	return &SocialMessageBySlugParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSocialMessageBySlugParamsWithTimeout creates a new SocialMessageBySlugParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSocialMessageBySlugParamsWithTimeout(timeout time.Duration) *SocialMessageBySlugParams {
	var ()
	return &SocialMessageBySlugParams{

		timeout: timeout,
	}
}

// NewSocialMessageBySlugParamsWithContext creates a new SocialMessageBySlugParams object
// with the default values initialized, and the ability to set a context for a request
func NewSocialMessageBySlugParamsWithContext(ctx context.Context) *SocialMessageBySlugParams {
	var ()
	return &SocialMessageBySlugParams{

		Context: ctx,
	}
}

/*SocialMessageBySlugParams contains all the parameters to send to the API endpoint
for the social message by slug operation typically these are written to a http.Request
*/
type SocialMessageBySlugParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the social message by slug params
func (o *SocialMessageBySlugParams) WithTimeout(timeout time.Duration) *SocialMessageBySlugParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the social message by slug params
func (o *SocialMessageBySlugParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the social message by slug params
func (o *SocialMessageBySlugParams) WithContext(ctx context.Context) *SocialMessageBySlugParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the social message by slug params
func (o *SocialMessageBySlugParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the social message by slug params
func (o *SocialMessageBySlugParams) WithBody(body models.DefaultSelector) *SocialMessageBySlugParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the social message by slug params
func (o *SocialMessageBySlugParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SocialMessageBySlugParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
