module.exports = {
  'LOAD_USER_BEGIN'
  'LOAD_USER_FAIL'
  'LOAD_USER_SUCCESS'

  'SEARCH_USERS_BEGIN'
  'SEARCH_USERS_SUCCESS'
  'SEARCH_USERS_FAIL'

  'MARK_USER_AS_TROLL_BEGIN'
  'MARK_USER_AS_TROLL_SUCCESS'
  'MARK_USER_AS_TROLL_FAIL'

  'UNMARK_USER_AS_TROLL_BEGIN'
  'UNMARK_USER_AS_TROLL_SUCCESS'
  'UNMARK_USER_AS_TROLL_FAIL'

  'BLOCK_USER_BEGIN'
  'BLOCK_USER_SUCCESS'
  'BLOCK_USER_FAIL'

  'SET_CREATE_CHANNEL_PARTICIPANT_DELETE_FLAG'
  'UNSET_CREATE_CHANNEL_PARTICIPANT_DELETE_FLAG'

  'LOAD_TEAM_MEMBERS_BEGIN'
  'LOAD_TEAM_MEMBERS_FAIL'
  'LOAD_TEAM_MEMBERS_SUCCESS'

  'UPDATE_TEAM_MEMBER'
  'DELETE_TEAM_MEMBER'

  'LOAD_LOGGED_IN_USER_EMAIL_SUCCESS'
}
