KODING_CAKE = '../node_modules/koding-cake/bin/cake'
D = __dirname
processes = new(require 'processes')
require('fs').writeFileSync '/var/run/node/kiteCake.pid', process.pid, 'utf-8'

http = require 'http'
https = require 'https'



task 'cl3','runs dev kites',(options)->

  config = require '../config/dev'
  processes.fork
    name    : "sharedHosting cake"
    cmd     : "#{KODING_CAKE} ./sharedHosting -c config-dev-new run"
    restart : yes
    verbose : yes

  processes.fork
    name    : "applications cake"
    cmd     : "#{KODING_CAKE} ./applications -c config-dev-new run"
    restart : yes
    verbose : yes

  processes.spawn
    name    : 'webterm kite'
    cmd     : "#{__dirname}/webterm -c dev-new"
    restart : yes
    verbose : yes

  processes.fork
    name    : "databases cake"
    cmd     : "#{KODING_CAKE} ./databases -c config-dev-new run"
    restart : yes
    verbose : yes


task 'cl0', 'runs prod kites',(options)->
  config = require '../config/prod'
  
  processes.fork
    name    : "sharedHosting cake"
    cmd     : "#{KODING_CAKE} ./sharedHosting -c config-prod-new run"
    restart : yes
    verbose : yes

  processes.fork
    name    : "applications cake"
    cmd     : "#{KODING_CAKE} ./applications -c config-prod-new run"
    restart : yes
    verbose : yes

  processes.spawn
    name    : 'webterm'
    cmd     : "#{__dirname}/webterm -c prod-new"
    restart : yes
    verbose : yes

  processes.fork
    name    : "databases cake"
    cmd     : "#{KODING_CAKE} ./databases -c config-prod-new run"
    restart : yes
    verbose : yes



task 'vagrant', 'runs vagrant kites',(options)->
  config = require '../config/vagrant'
  
  processes.fork
    name    : "sharedHosting cake"
    cmd     : "#{KODING_CAKE} ./sharedHosting -c vagrant run"
    restart : yes
    verbose : yes


