EventExchangeName = "BrokerMessageBus"
Mongo             = "localhost:27017/koding"
Environment       = "test"
Region            = "aws"
Uri               = "http://dev.koding.com:3020"

[postgres]
Host       = "localhost"
Port       = 5432
# Username = "postgres"
# Password = "123123123"
Username   = "socialapplication"
Password   = "socialapplication"
DBName     = "social"

[mq]
Host     = "localhost"
Port     = 5672
Username = "PROD-k5it50s4676pO9O"
Password = "djfjfhgh4455__5"
Vhost    = "/"

[redis]
URL = "localhost:6379"
DB  = 2

[limits]
MessageBodyMinLen    = 5
PostThrottleDuration = "10s"
PostThrottleCount    = 100

[emailnotification]
TemplateRoot = "../templates/"

[sitemap]
RedisDB = 2
