package j_combined_app_storage

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJCombinedAppStorageUpsertIDReader is a Reader for the PostRemoteAPIJCombinedAppStorageUpsertID structure.
type PostRemoteAPIJCombinedAppStorageUpsertIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJCombinedAppStorageUpsertIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJCombinedAppStorageUpsertIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJCombinedAppStorageUpsertIDOK creates a PostRemoteAPIJCombinedAppStorageUpsertIDOK with default headers values
func NewPostRemoteAPIJCombinedAppStorageUpsertIDOK() *PostRemoteAPIJCombinedAppStorageUpsertIDOK {
	return &PostRemoteAPIJCombinedAppStorageUpsertIDOK{}
}

/*PostRemoteAPIJCombinedAppStorageUpsertIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJCombinedAppStorageUpsertIDOK struct {
	Payload *models.JCombinedAppStorage
}

func (o *PostRemoteAPIJCombinedAppStorageUpsertIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JCombinedAppStorage.upsert/{id}][%d] postRemoteApiJCombinedAppStorageUpsertIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJCombinedAppStorageUpsertIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JCombinedAppStorage)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
