package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJAccountCountParams creates a new JAccountCountParams object
// with the default values initialized.
func NewJAccountCountParams() *JAccountCountParams {
	var ()
	return &JAccountCountParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJAccountCountParamsWithTimeout creates a new JAccountCountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJAccountCountParamsWithTimeout(timeout time.Duration) *JAccountCountParams {
	var ()
	return &JAccountCountParams{

		timeout: timeout,
	}
}

// NewJAccountCountParamsWithContext creates a new JAccountCountParams object
// with the default values initialized, and the ability to set a context for a request
func NewJAccountCountParamsWithContext(ctx context.Context) *JAccountCountParams {
	var ()
	return &JAccountCountParams{

		Context: ctx,
	}
}

/*JAccountCountParams contains all the parameters to send to the API endpoint
for the j account count operation typically these are written to a http.Request
*/
type JAccountCountParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j account count params
func (o *JAccountCountParams) WithTimeout(timeout time.Duration) *JAccountCountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j account count params
func (o *JAccountCountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j account count params
func (o *JAccountCountParams) WithContext(ctx context.Context) *JAccountCountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j account count params
func (o *JAccountCountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j account count params
func (o *JAccountCountParams) WithBody(body models.DefaultSelector) *JAccountCountParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j account count params
func (o *JAccountCountParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JAccountCountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
