package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JAccountIsFollowingReader is a Reader for the JAccountIsFollowing structure.
type JAccountIsFollowingReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JAccountIsFollowingReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJAccountIsFollowingOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJAccountIsFollowingOK creates a JAccountIsFollowingOK with default headers values
func NewJAccountIsFollowingOK() *JAccountIsFollowingOK {
	return &JAccountIsFollowingOK{}
}

/*JAccountIsFollowingOK handles this case with default header values.

OK
*/
type JAccountIsFollowingOK struct {
	Payload JAccountIsFollowingOKBody
}

func (o *JAccountIsFollowingOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.isFollowing/{id}][%d] jAccountIsFollowingOK  %+v", 200, o.Payload)
}

func (o *JAccountIsFollowingOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JAccountIsFollowingOKBody j account is following o k body
swagger:model JAccountIsFollowingOKBody
*/
type JAccountIsFollowingOKBody struct {
	models.JAccount

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *JAccountIsFollowingOKBody) UnmarshalJSON(raw []byte) error {

	var jAccountIsFollowingOKBodyAO0 models.JAccount
	if err := swag.ReadJSON(raw, &jAccountIsFollowingOKBodyAO0); err != nil {
		return err
	}
	o.JAccount = jAccountIsFollowingOKBodyAO0

	var jAccountIsFollowingOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &jAccountIsFollowingOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = jAccountIsFollowingOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o JAccountIsFollowingOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	jAccountIsFollowingOKBodyAO0, err := swag.WriteJSON(o.JAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountIsFollowingOKBodyAO0)

	jAccountIsFollowingOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountIsFollowingOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this j account is following o k body
func (o *JAccountIsFollowingOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
