package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JAccountFetchEmailFrequencyReader is a Reader for the JAccountFetchEmailFrequency structure.
type JAccountFetchEmailFrequencyReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JAccountFetchEmailFrequencyReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJAccountFetchEmailFrequencyOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJAccountFetchEmailFrequencyOK creates a JAccountFetchEmailFrequencyOK with default headers values
func NewJAccountFetchEmailFrequencyOK() *JAccountFetchEmailFrequencyOK {
	return &JAccountFetchEmailFrequencyOK{}
}

/*JAccountFetchEmailFrequencyOK handles this case with default header values.

OK
*/
type JAccountFetchEmailFrequencyOK struct {
	Payload JAccountFetchEmailFrequencyOKBody
}

func (o *JAccountFetchEmailFrequencyOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.fetchEmailFrequency/{id}][%d] jAccountFetchEmailFrequencyOK  %+v", 200, o.Payload)
}

func (o *JAccountFetchEmailFrequencyOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JAccountFetchEmailFrequencyOKBody j account fetch email frequency o k body
swagger:model JAccountFetchEmailFrequencyOKBody
*/
type JAccountFetchEmailFrequencyOKBody struct {
	models.JAccount

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *JAccountFetchEmailFrequencyOKBody) UnmarshalJSON(raw []byte) error {

	var jAccountFetchEmailFrequencyOKBodyAO0 models.JAccount
	if err := swag.ReadJSON(raw, &jAccountFetchEmailFrequencyOKBodyAO0); err != nil {
		return err
	}
	o.JAccount = jAccountFetchEmailFrequencyOKBodyAO0

	var jAccountFetchEmailFrequencyOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &jAccountFetchEmailFrequencyOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = jAccountFetchEmailFrequencyOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o JAccountFetchEmailFrequencyOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	jAccountFetchEmailFrequencyOKBodyAO0, err := swag.WriteJSON(o.JAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountFetchEmailFrequencyOKBodyAO0)

	jAccountFetchEmailFrequencyOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountFetchEmailFrequencyOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this j account fetch email frequency o k body
func (o *JAccountFetchEmailFrequencyOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
