package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJAccountFetchAppStorageParams creates a new JAccountFetchAppStorageParams object
// with the default values initialized.
func NewJAccountFetchAppStorageParams() *JAccountFetchAppStorageParams {
	var ()
	return &JAccountFetchAppStorageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJAccountFetchAppStorageParamsWithTimeout creates a new JAccountFetchAppStorageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJAccountFetchAppStorageParamsWithTimeout(timeout time.Duration) *JAccountFetchAppStorageParams {
	var ()
	return &JAccountFetchAppStorageParams{

		timeout: timeout,
	}
}

// NewJAccountFetchAppStorageParamsWithContext creates a new JAccountFetchAppStorageParams object
// with the default values initialized, and the ability to set a context for a request
func NewJAccountFetchAppStorageParamsWithContext(ctx context.Context) *JAccountFetchAppStorageParams {
	var ()
	return &JAccountFetchAppStorageParams{

		Context: ctx,
	}
}

/*JAccountFetchAppStorageParams contains all the parameters to send to the API endpoint
for the j account fetch app storage operation typically these are written to a http.Request
*/
type JAccountFetchAppStorageParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) WithTimeout(timeout time.Duration) *JAccountFetchAppStorageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) WithContext(ctx context.Context) *JAccountFetchAppStorageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) WithBody(body models.DefaultSelector) *JAccountFetchAppStorageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) WithID(id string) *JAccountFetchAppStorageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the j account fetch app storage params
func (o *JAccountFetchAppStorageParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JAccountFetchAppStorageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
