package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JAccountUpdateFlagsReader is a Reader for the JAccountUpdateFlags structure.
type JAccountUpdateFlagsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JAccountUpdateFlagsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJAccountUpdateFlagsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJAccountUpdateFlagsOK creates a JAccountUpdateFlagsOK with default headers values
func NewJAccountUpdateFlagsOK() *JAccountUpdateFlagsOK {
	return &JAccountUpdateFlagsOK{}
}

/*JAccountUpdateFlagsOK handles this case with default header values.

OK
*/
type JAccountUpdateFlagsOK struct {
	Payload JAccountUpdateFlagsOKBody
}

func (o *JAccountUpdateFlagsOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.updateFlags/{id}][%d] jAccountUpdateFlagsOK  %+v", 200, o.Payload)
}

func (o *JAccountUpdateFlagsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JAccountUpdateFlagsOKBody j account update flags o k body
swagger:model JAccountUpdateFlagsOKBody
*/
type JAccountUpdateFlagsOKBody struct {
	models.JAccount

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *JAccountUpdateFlagsOKBody) UnmarshalJSON(raw []byte) error {

	var jAccountUpdateFlagsOKBodyAO0 models.JAccount
	if err := swag.ReadJSON(raw, &jAccountUpdateFlagsOKBodyAO0); err != nil {
		return err
	}
	o.JAccount = jAccountUpdateFlagsOKBodyAO0

	var jAccountUpdateFlagsOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &jAccountUpdateFlagsOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = jAccountUpdateFlagsOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o JAccountUpdateFlagsOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	jAccountUpdateFlagsOKBodyAO0, err := swag.WriteJSON(o.JAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountUpdateFlagsOKBodyAO0)

	jAccountUpdateFlagsOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jAccountUpdateFlagsOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this j account update flags o k body
func (o *JAccountUpdateFlagsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
