package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJAccountFetchEmailsByUsernameParams creates a new JAccountFetchEmailsByUsernameParams object
// with the default values initialized.
func NewJAccountFetchEmailsByUsernameParams() *JAccountFetchEmailsByUsernameParams {
	var ()
	return &JAccountFetchEmailsByUsernameParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJAccountFetchEmailsByUsernameParamsWithTimeout creates a new JAccountFetchEmailsByUsernameParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJAccountFetchEmailsByUsernameParamsWithTimeout(timeout time.Duration) *JAccountFetchEmailsByUsernameParams {
	var ()
	return &JAccountFetchEmailsByUsernameParams{

		timeout: timeout,
	}
}

// NewJAccountFetchEmailsByUsernameParamsWithContext creates a new JAccountFetchEmailsByUsernameParams object
// with the default values initialized, and the ability to set a context for a request
func NewJAccountFetchEmailsByUsernameParamsWithContext(ctx context.Context) *JAccountFetchEmailsByUsernameParams {
	var ()
	return &JAccountFetchEmailsByUsernameParams{

		Context: ctx,
	}
}

/*JAccountFetchEmailsByUsernameParams contains all the parameters to send to the API endpoint
for the j account fetch emails by username operation typically these are written to a http.Request
*/
type JAccountFetchEmailsByUsernameParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) WithTimeout(timeout time.Duration) *JAccountFetchEmailsByUsernameParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) WithContext(ctx context.Context) *JAccountFetchEmailsByUsernameParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) WithBody(body models.DefaultSelector) *JAccountFetchEmailsByUsernameParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j account fetch emails by username params
func (o *JAccountFetchEmailsByUsernameParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JAccountFetchEmailsByUsernameParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
