package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJAccountByRelevanceReader is a Reader for the PostRemoteAPIJAccountByRelevance structure.
type PostRemoteAPIJAccountByRelevanceReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJAccountByRelevanceReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJAccountByRelevanceOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIJAccountByRelevanceUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJAccountByRelevanceOK creates a PostRemoteAPIJAccountByRelevanceOK with default headers values
func NewPostRemoteAPIJAccountByRelevanceOK() *PostRemoteAPIJAccountByRelevanceOK {
	return &PostRemoteAPIJAccountByRelevanceOK{}
}

/*PostRemoteAPIJAccountByRelevanceOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIJAccountByRelevanceOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIJAccountByRelevanceOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.byRelevance][%d] postRemoteApiJAccountByRelevanceOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJAccountByRelevanceOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIJAccountByRelevanceUnauthorized creates a PostRemoteAPIJAccountByRelevanceUnauthorized with default headers values
func NewPostRemoteAPIJAccountByRelevanceUnauthorized() *PostRemoteAPIJAccountByRelevanceUnauthorized {
	return &PostRemoteAPIJAccountByRelevanceUnauthorized{}
}

/*PostRemoteAPIJAccountByRelevanceUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIJAccountByRelevanceUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIJAccountByRelevanceUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.byRelevance][%d] postRemoteApiJAccountByRelevanceUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIJAccountByRelevanceUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
