package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJAccountSetup2FactorAuthIDReader is a Reader for the PostRemoteAPIJAccountSetup2FactorAuthID structure.
type PostRemoteAPIJAccountSetup2FactorAuthIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJAccountSetup2FactorAuthIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJAccountSetup2FactorAuthIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJAccountSetup2FactorAuthIDOK creates a PostRemoteAPIJAccountSetup2FactorAuthIDOK with default headers values
func NewPostRemoteAPIJAccountSetup2FactorAuthIDOK() *PostRemoteAPIJAccountSetup2FactorAuthIDOK {
	return &PostRemoteAPIJAccountSetup2FactorAuthIDOK{}
}

/*PostRemoteAPIJAccountSetup2FactorAuthIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJAccountSetup2FactorAuthIDOK struct {
	Payload PostRemoteAPIJAccountSetup2FactorAuthIDOKBody
}

func (o *PostRemoteAPIJAccountSetup2FactorAuthIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.setup2FactorAuth/{id}][%d] postRemoteApiJAccountSetup2FactorAuthIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJAccountSetup2FactorAuthIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJAccountSetup2FactorAuthIDOKBody post remote API j account setup2 factor auth ID o k body
swagger:model PostRemoteAPIJAccountSetup2FactorAuthIDOKBody
*/
type PostRemoteAPIJAccountSetup2FactorAuthIDOKBody struct {
	models.JAccount

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJAccountSetup2FactorAuthIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO0 models.JAccount
	if err := swag.ReadJSON(raw, &postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO0); err != nil {
		return err
	}
	o.JAccount = postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO0

	var postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJAccountSetup2FactorAuthIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO0, err := swag.WriteJSON(o.JAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO0)

	postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJAccountSetup2FactorAuthIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j account setup2 factor auth ID o k body
func (o *PostRemoteAPIJAccountSetup2FactorAuthIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
