package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJAccountSetEmailPreferencesIDReader is a Reader for the PostRemoteAPIJAccountSetEmailPreferencesID structure.
type PostRemoteAPIJAccountSetEmailPreferencesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJAccountSetEmailPreferencesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJAccountSetEmailPreferencesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJAccountSetEmailPreferencesIDOK creates a PostRemoteAPIJAccountSetEmailPreferencesIDOK with default headers values
func NewPostRemoteAPIJAccountSetEmailPreferencesIDOK() *PostRemoteAPIJAccountSetEmailPreferencesIDOK {
	return &PostRemoteAPIJAccountSetEmailPreferencesIDOK{}
}

/*PostRemoteAPIJAccountSetEmailPreferencesIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJAccountSetEmailPreferencesIDOK struct {
	Payload PostRemoteAPIJAccountSetEmailPreferencesIDOKBody
}

func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.setEmailPreferences/{id}][%d] postRemoteApiJAccountSetEmailPreferencesIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJAccountSetEmailPreferencesIDOKBody post remote API j account set email preferences ID o k body
swagger:model PostRemoteAPIJAccountSetEmailPreferencesIDOKBody
*/
type PostRemoteAPIJAccountSetEmailPreferencesIDOKBody struct {
	models.JAccount

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO0 models.JAccount
	if err := swag.ReadJSON(raw, &postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO0); err != nil {
		return err
	}
	o.JAccount = postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO0

	var postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJAccountSetEmailPreferencesIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO0, err := swag.WriteJSON(o.JAccount)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO0)

	postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJAccountSetEmailPreferencesIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j account set email preferences ID o k body
func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JAccount.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
