package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJAccountExpireSubscriptionIDReader is a Reader for the PostRemoteAPIJAccountExpireSubscriptionID structure.
type PostRemoteAPIJAccountExpireSubscriptionIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJAccountExpireSubscriptionIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJAccountExpireSubscriptionIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJAccountExpireSubscriptionIDOK creates a PostRemoteAPIJAccountExpireSubscriptionIDOK with default headers values
func NewPostRemoteAPIJAccountExpireSubscriptionIDOK() *PostRemoteAPIJAccountExpireSubscriptionIDOK {
	return &PostRemoteAPIJAccountExpireSubscriptionIDOK{}
}

/*PostRemoteAPIJAccountExpireSubscriptionIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJAccountExpireSubscriptionIDOK struct {
	Payload *models.JAccount
}

func (o *PostRemoteAPIJAccountExpireSubscriptionIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.expireSubscription/{id}][%d] postRemoteApiJAccountExpireSubscriptionIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJAccountExpireSubscriptionIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
