package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJAccountSetEmailPreferencesIDReader is a Reader for the PostRemoteAPIJAccountSetEmailPreferencesID structure.
type PostRemoteAPIJAccountSetEmailPreferencesIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJAccountSetEmailPreferencesIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJAccountSetEmailPreferencesIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJAccountSetEmailPreferencesIDOK creates a PostRemoteAPIJAccountSetEmailPreferencesIDOK with default headers values
func NewPostRemoteAPIJAccountSetEmailPreferencesIDOK() *PostRemoteAPIJAccountSetEmailPreferencesIDOK {
	return &PostRemoteAPIJAccountSetEmailPreferencesIDOK{}
}

/*PostRemoteAPIJAccountSetEmailPreferencesIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJAccountSetEmailPreferencesIDOK struct {
	Payload *models.JAccount
}

func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JAccount.setEmailPreferences/{id}][%d] postRemoteApiJAccountSetEmailPreferencesIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJAccountSetEmailPreferencesIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JAccount)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
