package j_account

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams creates a new PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams object
// with the default values initialized.
func NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams() *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	var ()
	return &PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParamsWithTimeout creates a new PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	var ()
	return &PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParamsWithContext creates a new PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParamsWithContext(ctx context.Context) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	var ()
	return &PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams contains all the parameters to send to the API endpoint
for the post remote API j account fetch my permissions and roles ID operation typically these are written to a http.Request
*/
type PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) WithContext(ctx context.Context) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) WithBody(body models.DefaultSelector) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) WithID(id string) *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post remote API j account fetch my permissions and roles ID params
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJAccountFetchMyPermissionsAndRolesIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
