package j_compute_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJComputeStackCreateAdminMessageParams creates a new JComputeStackCreateAdminMessageParams object
// with the default values initialized.
func NewJComputeStackCreateAdminMessageParams() *JComputeStackCreateAdminMessageParams {
	var ()
	return &JComputeStackCreateAdminMessageParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJComputeStackCreateAdminMessageParamsWithTimeout creates a new JComputeStackCreateAdminMessageParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJComputeStackCreateAdminMessageParamsWithTimeout(timeout time.Duration) *JComputeStackCreateAdminMessageParams {
	var ()
	return &JComputeStackCreateAdminMessageParams{

		timeout: timeout,
	}
}

// NewJComputeStackCreateAdminMessageParamsWithContext creates a new JComputeStackCreateAdminMessageParams object
// with the default values initialized, and the ability to set a context for a request
func NewJComputeStackCreateAdminMessageParamsWithContext(ctx context.Context) *JComputeStackCreateAdminMessageParams {
	var ()
	return &JComputeStackCreateAdminMessageParams{

		Context: ctx,
	}
}

/*JComputeStackCreateAdminMessageParams contains all the parameters to send to the API endpoint
for the j compute stack create admin message operation typically these are written to a http.Request
*/
type JComputeStackCreateAdminMessageParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) WithTimeout(timeout time.Duration) *JComputeStackCreateAdminMessageParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) WithContext(ctx context.Context) *JComputeStackCreateAdminMessageParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) WithBody(body models.DefaultSelector) *JComputeStackCreateAdminMessageParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) WithID(id string) *JComputeStackCreateAdminMessageParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the j compute stack create admin message params
func (o *JComputeStackCreateAdminMessageParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JComputeStackCreateAdminMessageParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
