package j_compute_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJComputeStackSomeReader is a Reader for the PostRemoteAPIJComputeStackSome structure.
type PostRemoteAPIJComputeStackSomeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJComputeStackSomeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJComputeStackSomeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIJComputeStackSomeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJComputeStackSomeOK creates a PostRemoteAPIJComputeStackSomeOK with default headers values
func NewPostRemoteAPIJComputeStackSomeOK() *PostRemoteAPIJComputeStackSomeOK {
	return &PostRemoteAPIJComputeStackSomeOK{}
}

/*PostRemoteAPIJComputeStackSomeOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIJComputeStackSomeOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIJComputeStackSomeOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JComputeStack.some][%d] postRemoteApiJComputeStackSomeOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJComputeStackSomeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIJComputeStackSomeUnauthorized creates a PostRemoteAPIJComputeStackSomeUnauthorized with default headers values
func NewPostRemoteAPIJComputeStackSomeUnauthorized() *PostRemoteAPIJComputeStackSomeUnauthorized {
	return &PostRemoteAPIJComputeStackSomeUnauthorized{}
}

/*PostRemoteAPIJComputeStackSomeUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIJComputeStackSomeUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIJComputeStackSomeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JComputeStack.some][%d] postRemoteApiJComputeStackSomeUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIJComputeStackSomeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
