package j_compute_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJComputeStackDeleteIDReader is a Reader for the PostRemoteAPIJComputeStackDeleteID structure.
type PostRemoteAPIJComputeStackDeleteIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJComputeStackDeleteIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJComputeStackDeleteIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJComputeStackDeleteIDOK creates a PostRemoteAPIJComputeStackDeleteIDOK with default headers values
func NewPostRemoteAPIJComputeStackDeleteIDOK() *PostRemoteAPIJComputeStackDeleteIDOK {
	return &PostRemoteAPIJComputeStackDeleteIDOK{}
}

/*PostRemoteAPIJComputeStackDeleteIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJComputeStackDeleteIDOK struct {
	Payload PostRemoteAPIJComputeStackDeleteIDOKBody
}

func (o *PostRemoteAPIJComputeStackDeleteIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JComputeStack.delete/{id}][%d] postRemoteApiJComputeStackDeleteIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJComputeStackDeleteIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJComputeStackDeleteIDOKBody post remote API j compute stack delete ID o k body
swagger:model PostRemoteAPIJComputeStackDeleteIDOKBody
*/
type PostRemoteAPIJComputeStackDeleteIDOKBody struct {
	models.JComputeStack

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJComputeStackDeleteIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJComputeStackDeleteIDOKBodyAO0 models.JComputeStack
	if err := swag.ReadJSON(raw, &postRemoteAPIJComputeStackDeleteIDOKBodyAO0); err != nil {
		return err
	}
	o.JComputeStack = postRemoteAPIJComputeStackDeleteIDOKBodyAO0

	var postRemoteAPIJComputeStackDeleteIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJComputeStackDeleteIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJComputeStackDeleteIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJComputeStackDeleteIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJComputeStackDeleteIDOKBodyAO0, err := swag.WriteJSON(o.JComputeStack)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJComputeStackDeleteIDOKBodyAO0)

	postRemoteAPIJComputeStackDeleteIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJComputeStackDeleteIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j compute stack delete ID o k body
func (o *PostRemoteAPIJComputeStackDeleteIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JComputeStack.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
