package j_compute_stack

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJComputeStackModifyIDReader is a Reader for the PostRemoteAPIJComputeStackModifyID structure.
type PostRemoteAPIJComputeStackModifyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJComputeStackModifyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJComputeStackModifyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJComputeStackModifyIDOK creates a PostRemoteAPIJComputeStackModifyIDOK with default headers values
func NewPostRemoteAPIJComputeStackModifyIDOK() *PostRemoteAPIJComputeStackModifyIDOK {
	return &PostRemoteAPIJComputeStackModifyIDOK{}
}

/*PostRemoteAPIJComputeStackModifyIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJComputeStackModifyIDOK struct {
	Payload *models.JComputeStack
}

func (o *PostRemoteAPIJComputeStackModifyIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JComputeStack.modify/{id}][%d] postRemoteApiJComputeStackModifyIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJComputeStackModifyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JComputeStack)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
