package j_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJUserConvertParams creates a new JUserConvertParams object
// with the default values initialized.
func NewJUserConvertParams() *JUserConvertParams {
	var ()
	return &JUserConvertParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJUserConvertParamsWithTimeout creates a new JUserConvertParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJUserConvertParamsWithTimeout(timeout time.Duration) *JUserConvertParams {
	var ()
	return &JUserConvertParams{

		timeout: timeout,
	}
}

// NewJUserConvertParamsWithContext creates a new JUserConvertParams object
// with the default values initialized, and the ability to set a context for a request
func NewJUserConvertParamsWithContext(ctx context.Context) *JUserConvertParams {
	var ()
	return &JUserConvertParams{

		Context: ctx,
	}
}

/*JUserConvertParams contains all the parameters to send to the API endpoint
for the j user convert operation typically these are written to a http.Request
*/
type JUserConvertParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j user convert params
func (o *JUserConvertParams) WithTimeout(timeout time.Duration) *JUserConvertParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j user convert params
func (o *JUserConvertParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j user convert params
func (o *JUserConvertParams) WithContext(ctx context.Context) *JUserConvertParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j user convert params
func (o *JUserConvertParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j user convert params
func (o *JUserConvertParams) WithBody(body models.DefaultSelector) *JUserConvertParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j user convert params
func (o *JUserConvertParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JUserConvertParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
