package j_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJUserAuthenticateWithOauthParams creates a new JUserAuthenticateWithOauthParams object
// with the default values initialized.
func NewJUserAuthenticateWithOauthParams() *JUserAuthenticateWithOauthParams {
	var ()
	return &JUserAuthenticateWithOauthParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJUserAuthenticateWithOauthParamsWithTimeout creates a new JUserAuthenticateWithOauthParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJUserAuthenticateWithOauthParamsWithTimeout(timeout time.Duration) *JUserAuthenticateWithOauthParams {
	var ()
	return &JUserAuthenticateWithOauthParams{

		timeout: timeout,
	}
}

// NewJUserAuthenticateWithOauthParamsWithContext creates a new JUserAuthenticateWithOauthParams object
// with the default values initialized, and the ability to set a context for a request
func NewJUserAuthenticateWithOauthParamsWithContext(ctx context.Context) *JUserAuthenticateWithOauthParams {
	var ()
	return &JUserAuthenticateWithOauthParams{

		Context: ctx,
	}
}

/*JUserAuthenticateWithOauthParams contains all the parameters to send to the API endpoint
for the j user authenticate with oauth operation typically these are written to a http.Request
*/
type JUserAuthenticateWithOauthParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) WithTimeout(timeout time.Duration) *JUserAuthenticateWithOauthParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) WithContext(ctx context.Context) *JUserAuthenticateWithOauthParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) WithBody(body models.DefaultSelector) *JUserAuthenticateWithOauthParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j user authenticate with oauth params
func (o *JUserAuthenticateWithOauthParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JUserAuthenticateWithOauthParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
