package j_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JUserEmailAvailableReader is a Reader for the JUserEmailAvailable structure.
type JUserEmailAvailableReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JUserEmailAvailableReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJUserEmailAvailableOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewJUserEmailAvailableUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJUserEmailAvailableOK creates a JUserEmailAvailableOK with default headers values
func NewJUserEmailAvailableOK() *JUserEmailAvailableOK {
	return &JUserEmailAvailableOK{}
}

/*JUserEmailAvailableOK handles this case with default header values.

Request processed successfully
*/
type JUserEmailAvailableOK struct {
	Payload *models.DefaultResponse
}

func (o *JUserEmailAvailableOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JUser.emailAvailable][%d] jUserEmailAvailableOK  %+v", 200, o.Payload)
}

func (o *JUserEmailAvailableOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJUserEmailAvailableUnauthorized creates a JUserEmailAvailableUnauthorized with default headers values
func NewJUserEmailAvailableUnauthorized() *JUserEmailAvailableUnauthorized {
	return &JUserEmailAvailableUnauthorized{}
}

/*JUserEmailAvailableUnauthorized handles this case with default header values.

Unauthorized request
*/
type JUserEmailAvailableUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *JUserEmailAvailableUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JUser.emailAvailable][%d] jUserEmailAvailableUnauthorized  %+v", 401, o.Payload)
}

func (o *JUserEmailAvailableUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
