package j_user

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJUserGetSSHKeysReader is a Reader for the PostRemoteAPIJUserGetSSHKeys structure.
type PostRemoteAPIJUserGetSSHKeysReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJUserGetSSHKeysReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJUserGetSSHKeysOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIJUserGetSSHKeysUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJUserGetSSHKeysOK creates a PostRemoteAPIJUserGetSSHKeysOK with default headers values
func NewPostRemoteAPIJUserGetSSHKeysOK() *PostRemoteAPIJUserGetSSHKeysOK {
	return &PostRemoteAPIJUserGetSSHKeysOK{}
}

/*PostRemoteAPIJUserGetSSHKeysOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIJUserGetSSHKeysOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIJUserGetSSHKeysOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JUser.getSSHKeys][%d] postRemoteApiJUserGetSshKeysOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJUserGetSSHKeysOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIJUserGetSSHKeysUnauthorized creates a PostRemoteAPIJUserGetSSHKeysUnauthorized with default headers values
func NewPostRemoteAPIJUserGetSSHKeysUnauthorized() *PostRemoteAPIJUserGetSSHKeysUnauthorized {
	return &PostRemoteAPIJUserGetSSHKeysUnauthorized{}
}

/*PostRemoteAPIJUserGetSSHKeysUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIJUserGetSSHKeysUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIJUserGetSSHKeysUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JUser.getSSHKeys][%d] postRemoteApiJUserGetSshKeysUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIJUserGetSSHKeysUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
