module.exports = {

  'LOAD_GLOBAL_NOTIFICATION_SETTINGS_FAIL'
  'LOAD_GLOBAL_NOTIFICATION_SETTINGS_SUCCESS'

  'LOAD_CHANNEL_NOTIFICATION_SETTINGS_FAIL'
  'LOAD_CHANNEL_NOTIFICATION_SETTINGS_SUCCESS'

  'CREATE_CHANNEL_NOTIFICATION_SETTINGS_FAIL'
  'CREATE_CHANNEL_NOTIFICATION_SETTINGS_SUCCESS'

  'UPDATE_CHANNEL_NOTIFICATION_SETTINGS_FAIL'
  'UPDATE_CHANNEL_NOTIFICATION_SETTINGS_SUCCESS'

  'DELETE_CHANNEL_NOTIFICATION_SETTINGS_FAIL'
  'DELETE_CHANNEL_NOTIFICATION_SETTINGS_SUCCESS'

}
