#! /bin/sh
### BEGIN INIT INFO
# Provides:          single
# Required-Start:    $remote_fs $named $network $time
# Required-Stop:     $remote_fs $named $network $time
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: radosgw
### END INIT INFO

PATH=/sbin:/bin:/usr/bin

. /lib/lsb/init-functions

CLIENT_NAME=client.rgw-`hostname | sed 's/\..*//g'`
USER=www-data


do_start () {
        su $USER -c "radosgw -c /etc/ceph/ceph.conf -n $CLIENT_NAME >> /var/log/radosgw/radosgw.log 2>&1 &"
}

case "$1" in
  start)
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: $0 start|stop" >&2
        exit 3
        ;;
esac
