processes = new (require 'processes')
option '-c', '--configPath [CONFIG]', 'Which config file to use.'

task 'run', ({configPath, silent})->

  configPath ?= '../../config/dev'

  processes.fork
    name  : "activity-cacher"
    cmd   : "./index -c #{configPath}"
    restart : yes
    restartInterval : 1000

  return