(function() {function g(a){throw a;}var j=void 0,k=!0,l=null,o=!1;function aa(a){return function(){return this[a]}}function q(a){return function(){return a}}var t,ba=this;function ca(){}
function da(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function u(a){return a!==j}function ea(a){var b=da(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){return"string"==typeof a}function fa(a){return"number"==typeof a}function ga(a){var b=typeof a;return"object"==b&&a!=l||"function"==b}Math.floor(2147483648*Math.random()).toString(36);function ha(a,b,c){return a.call.apply(a.bind,arguments)}
function ia(a,b,c){a||g(Error());if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}}function w(a,b,c){w=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ha:ia;return w.apply(l,arguments)}function ja(a,b){function c(){}c.prototype=b.prototype;a.Od=b.prototype;a.prototype=new c};function ka(a){a=String(a);if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/"[^"\\\n\r\u2028\u2029\x00-\x08\x10-\x1f\x80-\x9f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}g(Error("Invalid JSON string: "+a))}function la(){this.Yb=j}
function ma(a,b,c){switch(typeof b){case "string":na(b,c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?b:"null");break;case "boolean":c.push(b);break;case "undefined":c.push("null");break;case "object":if(b==l){c.push("null");break}if("array"==da(b)){var d=b.length;c.push("[");for(var e="",f=0;f<d;f++)c.push(e),e=b[f],ma(a,a.Yb?a.Yb.call(b,String(f),e):e,c),e=",";c.push("]");break}c.push("{");d="";for(f in b)Object.prototype.hasOwnProperty.call(b,f)&&(e=b[f],"function"!=typeof e&&(c.push(d),
na(f,c),c.push(":"),ma(a,a.Yb?a.Yb.call(b,f,e):e,c),d=","));c.push("}");break;case "function":break;default:g(Error("Unknown type: "+typeof b))}}var oa={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},pa=/\uffff/.test("\uffff")?/[\\\"\x00-\x1f\x7f-\uffff]/g:/[\\\"\x00-\x1f\x7f-\xff]/g;
function na(a,b){b.push('"',a.replace(pa,function(a){if(a in oa)return oa[a];var b=a.charCodeAt(0),e="\\u";16>b?e+="000":256>b?e+="00":4096>b&&(e+="0");return oa[a]=e+b.toString(16)}),'"')};function y(a){if("undefined"!==typeof JSON&&u(JSON.stringify))a=JSON.stringify(a);else{var b=[];ma(new la,a,b);a=b.join("")}return a};function qa(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);55296<=e&&56319>=e&&(e-=55296,d++,z(d<a.length,"Surrogate pair missing trail surrogate."),e=65536+(e<<10)+(a.charCodeAt(d)-56320));128>e?b[c++]=e:(2048>e?b[c++]=e>>6|192:(65536>e?b[c++]=e>>12|224:(b[c++]=e>>18|240,b[c++]=e>>12&63|128),b[c++]=e>>6&63|128),b[c++]=e&63|128)}return b};function A(a,b,c,d){var e;d<b?e="at least "+b:d>c&&(e=0===c?"none":"no more than "+c);e&&g(Error(a+" failed: Was called with "+d+(1===d?" argument.":" arguments.")+" Expects "+e+"."))}function B(a,b,c){var d="";switch(b){case 1:d=c?"first":"First";break;case 2:d=c?"second":"Second";break;case 3:d=c?"third":"Third";break;case 4:d=c?"fourth":"Fourth";break;default:ra.assert(o,"errorPrefix_ called with argumentNumber > 4.  Need to update it?")}return a+" failed: "+(d+" argument ")}
function C(a,b,c,d){(!d||u(c))&&"function"!=da(c)&&g(Error(B(a,b,d)+"must be a valid function."))}function sa(a,b,c){u(c)&&(!ga(c)||c===l)&&g(Error(B(a,b,k)+"must be a valid context object."))};function D(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function ta(a,b){if(Object.prototype.hasOwnProperty.call(a,b))return a[b]};var ra={},ua=/[\[\].#$\/]/,va=/[\[\].#$]/;function wa(a){return v(a)&&0!==a.length&&!ua.test(a)}function xa(a,b,c){(!c||u(b))&&ya(B(a,1,c),b)}
function ya(a,b,c,d){c||(c=0);d||(d=[]);u(b)||g(Error(a+"contains undefined"+za(d)));"function"==da(b)&&g(Error(a+"contains a function"+za(d)+" with contents: "+b.toString()));Aa(b)&&g(Error(a+"contains "+b.toString()+za(d)));1E3<c&&g(new TypeError(a+"contains a cyclic object value ("+d.slice(0,100).join(".")+"...)"));v(b)&&(b.length>10485760/3&&10485760<qa(b).length)&&g(Error(a+"contains a string greater than 10485760 utf8 bytes"+za(d)+" ('"+b.substring(0,50)+"...')"));if(ga(b))for(var e in b)D(b,
e)&&(".priority"!==e&&(".value"!==e&&".sv"!==e&&!wa(e))&&g(Error(a+"contains an invalid key ("+e+")"+za(d)+'.  Keys must be non-empty strings and can\'t contain ".", "#", "$", "/", "[", or "]"')),d.push(e),ya(a,b[e],c+1,d),d.pop())}function za(a){return 0==a.length?"":" in property '"+a.join(".")+"'"}function Ba(a,b){ga(b)||g(Error(B(a,1,o)+" must be an object containing the children to replace."));xa(a,b,o)}
function Ca(a,b,c,d){if(!d||u(c))c!==l&&(!fa(c)&&!v(c)&&(!ga(c)||!D(c,".sv")))&&g(Error(B(a,b,d)+"must be a valid firebase priority (null or a string.)"))}function Da(a,b,c){if(!c||u(b))switch(b){case "value":case "child_added":case "child_removed":case "child_changed":case "child_moved":break;default:g(Error(B(a,1,c)+'must be a valid event type: "value", "child_added", "child_removed", "child_changed", or "child_moved".'))}}
function Ea(a,b){u(b)&&!wa(b)&&g(Error(B(a,2,k)+'must be a valid firebase key (non-empty string, not containing ".", "#", "$", "/", "[", or "]").'))}function Fa(a,b){(!v(b)||0===b.length||va.test(b))&&g(Error(B(a,1,o)+'must be a non-empty string and can\'t contain ".", "#", "$", "[", or "]".'))}function E(a,b){".info"===G(b)&&g(Error(a+" failed: Can't modify data under /.info/"))};function H(a,b,c,d,e,f,h){this.u=a;this.path=b;this.xa=c;this.ba=d;this.pa=e;this.va=f;this.Oa=h;u(this.ba)&&(u(this.va)&&u(this.xa))&&g("Query: Can't combine startAt(), endAt(), and limit().")}H.prototype.Dc=function(){A("Query.ref",0,0,arguments.length);return new J(this.u,this.path)};H.prototype.ref=H.prototype.Dc;
H.prototype.vc=function(a,b){A("Query.on",2,4,arguments.length);Da("Query.on",a,o);C("Query.on",2,b,o);var c=Ga("Query.on",arguments[2],arguments[3]);this.u.Fb(this,a,b,c.cancel,c.$);return b};H.prototype.on=H.prototype.vc;H.prototype.Lb=function(a,b,c){A("Query.off",0,3,arguments.length);Da("Query.off",a,k);C("Query.off",2,b,k);sa("Query.off",3,c);this.u.Xb(this,a,b,c)};H.prototype.off=H.prototype.Lb;
H.prototype.Cd=function(a,b){function c(h){f&&(f=o,e.Lb(a,c),b.call(d.$,h))}A("Query.once",2,4,arguments.length);Da("Query.once",a,o);C("Query.once",2,b,o);var d=Ga("Query.once",arguments[2],arguments[3]),e=this,f=k;this.vc(a,c,function(b){e.Lb(a,c);d.cancel&&d.cancel.call(d.$,b)})};H.prototype.once=H.prototype.Cd;
H.prototype.xd=function(a){A("Query.limit",1,1,arguments.length);(!fa(a)||Math.floor(a)!==a||0>=a)&&g("Query.limit: First argument must be a positive integer.");return new H(this.u,this.path,a,this.ba,this.pa,this.va,this.Oa)};H.prototype.limit=H.prototype.xd;H.prototype.Ld=function(a,b){A("Query.startAt",0,2,arguments.length);Ca("Query.startAt",1,a,k);Ea("Query.startAt",b);u(a)||(b=a=l);return new H(this.u,this.path,this.xa,a,b,this.va,this.Oa)};H.prototype.startAt=H.prototype.Ld;
H.prototype.rd=function(a,b){A("Query.endAt",0,2,arguments.length);Ca("Query.endAt",1,a,k);Ea("Query.endAt",b);return new H(this.u,this.path,this.xa,this.ba,this.pa,a,b)};H.prototype.endAt=H.prototype.rd;function Ha(a){var b={};u(a.ba)&&(b.sp=a.ba);u(a.pa)&&(b.sn=a.pa);u(a.va)&&(b.ep=a.va);u(a.Oa)&&(b.en=a.Oa);u(a.xa)&&(b.l=a.xa);u(a.ba)&&(u(a.pa)&&a.ba===l&&a.pa===l)&&(b.vf="l");return b}H.prototype.Ia=function(){var a=Ia(Ha(this));return"{}"===a?"default":a};
function Ga(a,b,c){var d={};b&&c?(d.cancel=b,C(a,3,d.cancel,k),d.$=c,sa(a,4,d.$)):b&&("object"===typeof b&&b!==l?d.$=b:"function"===typeof b?d.cancel=b:g(Error(B(a,3,k)+"must either be a cancel callback or a context object.")));return d};function K(a){if(a instanceof K)return a;if(1==arguments.length){this.m=a.split("/");for(var b=0,c=0;c<this.m.length;c++)0<this.m[c].length&&(this.m[b]=this.m[c],b++);this.m.length=b;this.X=0}else this.m=arguments[0],this.X=arguments[1]}function G(a){return a.X>=a.m.length?l:a.m[a.X]}function Ja(a){var b=a.X;b<a.m.length&&b++;return new K(a.m,b)}t=K.prototype;t.toString=function(){for(var a="",b=this.X;b<this.m.length;b++)""!==this.m[b]&&(a+="/"+this.m[b]);return a||"/"};
t.parent=function(){if(this.X>=this.m.length)return l;for(var a=[],b=this.X;b<this.m.length-1;b++)a.push(this.m[b]);return new K(a,0)};t.F=function(a){for(var b=[],c=this.X;c<this.m.length;c++)b.push(this.m[c]);if(a instanceof K)for(c=a.X;c<a.m.length;c++)b.push(a.m[c]);else{a=a.split("/");for(c=0;c<a.length;c++)0<a[c].length&&b.push(a[c])}return new K(b,0)};t.f=function(){return this.X>=this.m.length};
function Ka(a,b){var c=G(a);if(c===l)return b;if(c===G(b))return Ka(Ja(a),Ja(b));g("INTERNAL ERROR: innerPath ("+b+") is not within outerPath ("+a+")")}t.contains=function(a){var b=0;if(this.m.length>a.m.length)return o;for(;b<this.m.length;){if(this.m[b]!==a.m[b])return o;++b}return k};function La(){this.children={};this.jc=0;this.value=l}function Ma(a,b,c){this.ya=a?a:"";this.rb=b?b:l;this.z=c?c:new La}function L(a,b){for(var c=b instanceof K?b:new K(b),d=a,e;(e=G(c))!==l;)d=new Ma(e,d,ta(d.z.children,e)||new La),c=Ja(c);return d}t=Ma.prototype;t.k=function(){return this.z.value};function M(a,b){z("undefined"!==typeof b);a.z.value=b;Na(a)}t.gb=function(){return 0<this.z.jc};t.f=function(){return this.k()===l&&!this.gb()};
t.w=function(a){for(var b in this.z.children)a(new Ma(b,this,this.z.children[b]))};function Oa(a,b,c,d){c&&!d&&b(a);a.w(function(a){Oa(a,b,k,d)});c&&d&&b(a)}function Pa(a,b,c){for(a=c?a:a.parent();a!==l;){if(b(a))return k;a=a.parent()}return o}t.path=function(){return new K(this.rb===l?this.ya:this.rb.path()+"/"+this.ya)};t.name=aa("ya");t.parent=aa("rb");
function Na(a){if(a.rb!==l){var b=a.rb,c=a.ya,d=a.f(),e=D(b.z.children,c);d&&e?(delete b.z.children[c],b.z.jc--,Na(b)):!d&&!e&&(b.z.children[c]=a.z,b.z.jc++,Na(b))}};function N(a,b){this.La=a?a:Qa;this.aa=b?b:Ra}function Qa(a,b){return a<b?-1:a>b?1:0}t=N.prototype;t.ma=function(a,b){return new N(this.La,this.aa.ma(a,b,this.La).copy(l,l,o,l,l))};t.remove=function(a){return new N(this.La,this.aa.remove(a,this.La).copy(l,l,o,l,l))};t.get=function(a){for(var b,c=this.aa;!c.f();){b=this.La(a,c.key);if(0===b)return c.value;0>b?c=c.left:0<b&&(c=c.right)}return l};
function Sa(a,b){for(var c,d=a.aa,e=l;!d.f();){c=a.La(b,d.key);if(0===c){if(d.left.f())return e?e.key:l;for(d=d.left;!d.right.f();)d=d.right;return d.key}0>c?d=d.left:0<c&&(e=d,d=d.right)}g(Error("Attempted to find predecessor key for a nonexistent key.  What gives?"))}t.f=function(){return this.aa.f()};t.count=function(){return this.aa.count()};t.lb=function(){return this.aa.lb()};t.Ra=function(){return this.aa.Ra()};t.wa=function(a){return this.aa.wa(a)};t.Ja=function(a){return this.aa.Ja(a)};
t.Pa=function(a){return new Ta(this.aa,a)};function Ta(a,b){this.dd=b;for(this.Jb=[];!a.f();)this.Jb.push(a),a=a.left}function Ua(a){if(0===a.Jb.length)return l;var b=a.Jb.pop(),c;c=a.dd?a.dd(b.key,b.value):{key:b.key,value:b.value};for(b=b.right;!b.f();)a.Jb.push(b),b=b.left;return c}function Va(a,b,c,d,e){this.key=a;this.value=b;this.color=c!=l?c:k;this.left=d!=l?d:Ra;this.right=e!=l?e:Ra}t=Va.prototype;
t.copy=function(a,b,c,d,e){return new Va(a!=l?a:this.key,b!=l?b:this.value,c!=l?c:this.color,d!=l?d:this.left,e!=l?e:this.right)};t.count=function(){return this.left.count()+1+this.right.count()};t.f=q(o);t.wa=function(a){return this.left.wa(a)||a(this.key,this.value)||this.right.wa(a)};t.Ja=function(a){return this.right.Ja(a)||a(this.key,this.value)||this.left.Ja(a)};function Ya(a){return a.left.f()?a:Ya(a.left)}t.lb=function(){return Ya(this).key};
t.Ra=function(){return this.right.f()?this.key:this.right.Ra()};t.ma=function(a,b,c){var d,e;e=this;d=c(a,e.key);e=0>d?e.copy(l,l,l,e.left.ma(a,b,c),l):0===d?e.copy(l,b,l,l,l):e.copy(l,l,l,l,e.right.ma(a,b,c));return Za(e)};function $a(a){if(a.left.f())return Ra;!a.left.K()&&!a.left.left.K()&&(a=ab(a));a=a.copy(l,l,l,$a(a.left),l);return Za(a)}
t.remove=function(a,b){var c,d;c=this;if(0>b(a,c.key))!c.left.f()&&(!c.left.K()&&!c.left.left.K())&&(c=ab(c)),c=c.copy(l,l,l,c.left.remove(a,b),l);else{c.left.K()&&(c=bb(c));!c.right.f()&&(!c.right.K()&&!c.right.left.K())&&(c=cb(c),c.left.left.K()&&(c=bb(c),c=cb(c)));if(0===b(a,c.key)){if(c.right.f())return Ra;d=Ya(c.right);c=c.copy(d.key,d.value,l,l,$a(c.right))}c=c.copy(l,l,l,l,c.right.remove(a,b))}return Za(c)};t.K=aa("color");
function Za(a){a.right.K()&&!a.left.K()&&(a=db(a));a.left.K()&&a.left.left.K()&&(a=bb(a));a.left.K()&&a.right.K()&&(a=cb(a));return a}function ab(a){a=cb(a);a.right.left.K()&&(a=a.copy(l,l,l,l,bb(a.right)),a=db(a),a=cb(a));return a}function db(a){var b;b=a.copy(l,l,k,l,a.right.left);return a.right.copy(l,l,a.color,b,l)}function bb(a){var b;b=a.copy(l,l,k,a.left.right,l);return a.left.copy(l,l,a.color,l,b)}
function cb(a){var b,c;b=a.left.copy(l,l,!a.left.color,l,l);c=a.right.copy(l,l,!a.right.color,l,l);return a.copy(l,l,!a.color,b,c)}function eb(){}t=eb.prototype;t.copy=function(){return this};t.ma=function(a,b){return new Va(a,b,j,j,j)};t.remove=function(){return this};t.get=q(l);t.count=q(0);t.f=q(k);t.wa=q(o);t.Ja=q(o);t.lb=q(l);t.Ra=q(l);t.K=q(o);var Ra=new eb;var fb=Array.prototype,gb=fb.forEach?function(a,b,c){fb.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},hb=fb.map?function(a,b,c){return fb.map.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=Array(d),f=v(a)?a.split(""):a,h=0;h<d;h++)h in f&&(e[h]=b.call(c,f[h],h,a));return e};function ib(){};function jb(){this.B=[];this.ic=[];this.nd=[];this.Pb=[];this.Pb[0]=128;for(var a=1;64>a;++a)this.Pb[a]=0;this.reset()}ja(jb,ib);jb.prototype.reset=function(){this.B[0]=1732584193;this.B[1]=4023233417;this.B[2]=2562383102;this.B[3]=271733878;this.B[4]=3285377520;this.Mc=this.hb=0};
function kb(a,b){var c;c||(c=0);for(var d=a.nd,e=c;e<c+64;e+=4)d[e/4]=b[e]<<24|b[e+1]<<16|b[e+2]<<8|b[e+3];for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}c=a.B[0];for(var h=a.B[1],i=a.B[2],m=a.B[3],n=a.B[4],p,e=0;80>e;e++)40>e?20>e?(f=m^h&(i^m),p=1518500249):(f=h^i^m,p=1859775393):60>e?(f=h&i|m&(h|i),p=2400959708):(f=h^i^m,p=3395469782),f=(c<<5|c>>>27)+f+n+p+d[e]&4294967295,n=m,m=i,i=(h<<30|h>>>2)&4294967295,h=c,c=f;a.B[0]=a.B[0]+c&4294967295;a.B[1]=a.B[1]+h&
4294967295;a.B[2]=a.B[2]+i&4294967295;a.B[3]=a.B[3]+m&4294967295;a.B[4]=a.B[4]+n&4294967295}jb.prototype.update=function(a,b){u(b)||(b=a.length);var c=this.ic,d=this.hb,e=0;if(v(a))for(;e<b;)c[d++]=a.charCodeAt(e++),64==d&&(kb(this,c),d=0);else for(;e<b;)c[d++]=a[e++],64==d&&(kb(this,c),d=0);this.hb=d;this.Mc+=b};function lb(){this.Ka={};this.length=0}lb.prototype.setItem=function(a,b){D(this.Ka,a)||(this.length+=1);this.Ka[a]=b};lb.prototype.getItem=function(a){return D(this.Ka,a)?this.Ka[a]:l};lb.prototype.removeItem=function(a){D(this.Ka,a)&&(this.length-=1,delete this.Ka[a])};var mb=l;if("undefined"!==typeof sessionStorage)try{sessionStorage.setItem("firebase-sentinel","cache"),sessionStorage.removeItem("firebase-sentinel"),mb=sessionStorage}catch(nb){mb=new lb}else mb=new lb;function ob(a,b,c,d){this.host=a.toLowerCase();this.Zb=b;this.mb=c;this.da=d||mb.getItem(a)||this.host}function pb(a,b){b!==a.da&&(a.da=b,"s-"===a.da.substr(0,2)&&mb.setItem(a.host,a.da))}ob.prototype.toString=function(){return(this.Zb?"https://":"http://")+this.host};var qb,rb,sb,tb;function ub(){return ba.navigator?ba.navigator.userAgent:l}tb=sb=rb=qb=o;var vb;if(vb=ub()){var wb=ba.navigator;qb=0==vb.indexOf("Opera");rb=!qb&&-1!=vb.indexOf("MSIE");sb=!qb&&-1!=vb.indexOf("WebKit");tb=!qb&&!sb&&"Gecko"==wb.product}var xb=rb,yb=tb,zb=sb;var Ab;if(qb&&ba.opera){var Bb=ba.opera.version;"function"==typeof Bb&&Bb()}else yb?Ab=/rv\:([^\);]+)(\)|;)/:xb?Ab=/MSIE\s+([^\);]+)(\)|;)/:zb&&(Ab=/WebKit\/(\S+)/),Ab&&Ab.exec(ub());var Cb=l,Db=l;
function Eb(a,b){ea(a)||g(Error("encodeByteArray takes an array as a parameter"));if(!Cb){Cb={};Db={};for(var c=0;65>c;c++)Cb[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(c),Db[c]="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_.".charAt(c)}for(var c=b?Db:Cb,d=[],e=0;e<a.length;e+=3){var f=a[e],h=e+1<a.length,i=h?a[e+1]:0,m=e+2<a.length,n=m?a[e+2]:0,p=f>>2,f=(f&3)<<4|i>>4,i=(i&15)<<2|n>>6,n=n&63;m||(n=64,h||(i=64));d.push(c[p],c[f],c[i],c[n])}return d.join("")}
;var Fb,Gb=1;Fb=function(){return Gb++};function z(a,b){a||g(Error("Firebase INTERNAL ASSERT FAILED:"+b))}function Hb(a){var b=qa(a),a=new jb;a.update(b);var b=[],c=8*a.Mc;56>a.hb?a.update(a.Pb,56-a.hb):a.update(a.Pb,64-(a.hb-56));for(var d=63;56<=d;d--)a.ic[d]=c&255,c/=256;kb(a,a.ic);for(d=c=0;5>d;d++)for(var e=24;0<=e;e-=8)b[c++]=a.B[d]>>e&255;return Eb(b)}
function Ib(){for(var a="",b=0;b<arguments.length;b++)a=ea(arguments[b])?a+Ib.apply(l,arguments[b]):"object"===typeof arguments[b]?a+y(arguments[b]):a+arguments[b],a+=" ";return a}var Jb=l,Kb=k;function P(){Kb===k&&(Kb=o,Jb===l&&"true"===mb.getItem("logging_enabled")&&Lb(k));if(Jb){var a=Ib.apply(l,arguments);Jb(a)}}function Mb(a){return function(){P(a,arguments)}}
function Nb(){if("undefined"!==typeof console){var a="FIREBASE INTERNAL ERROR: "+Ib.apply(l,arguments);"undefined"!==typeof console.error?console.error(a):console.log(a)}}function Ob(){var a=Ib.apply(l,arguments);g(Error("FIREBASE FATAL ERROR: "+a))}function Pb(){if("undefined"!==typeof console){var a="FIREBASE WARNING: "+Ib.apply(l,arguments);"undefined"!==typeof console.warn?console.warn(a):console.log(a)}}
function Aa(a){return fa(a)&&(a!=a||a==Number.POSITIVE_INFINITY||a==Number.NEGATIVE_INFINITY)}function Qb(a,b){return a!==b?a===l?-1:b===l?1:typeof a!==typeof b?"number"===typeof a?-1:1:a>b?1:-1:0}function Rb(a,b){if(b&&a in b)return b[a];g(Error("Missing required key ("+a+") in object: "+y(b)))}function Ia(a){if("object"!==typeof a||a===l)return y(a);var b=[],c;for(c in a)b.push(c);b.sort();c="{";for(var d=0;d<b.length;d++)0!==d&&(c+=","),c+=y(b[d]),c+=":",c+=Ia(a[b[d]]);return c+"}"}
function Sb(a,b){if(a.length<=b)return[a];for(var c=[],d=0;d<a.length;d+=b)d+b>a?c.push(a.substring(d,a.length)):c.push(a.substring(d,d+b));return c}function Tb(a,b){if("array"==da(a))for(var c=0;c<a.length;++c)b(c,a[c]);else Ub(a,b)}
function Vb(a){z(!Aa(a));var b,c,d,e;0===a?(d=c=0,b=-Infinity===1/a?1:0):(b=0>a,a=Math.abs(a),a>=Math.pow(2,-1022)?(d=Math.min(Math.floor(Math.log(a)/Math.LN2),1023),c=d+1023,d=Math.round(a*Math.pow(2,52-d)-Math.pow(2,52))):(c=0,d=Math.round(a/Math.pow(2,-1074))));e=[];for(a=52;a;a-=1)e.push(d%2?1:0),d=Math.floor(d/2);for(a=11;a;a-=1)e.push(c%2?1:0),c=Math.floor(c/2);e.push(b?1:0);e.reverse();b=e.join("");c="";for(a=0;64>a;a+=8)d=parseInt(b.substr(a,8),2).toString(16),1===d.length&&(d="0"+d),c+=d;
return c.toLowerCase()};function Wb(a,b){this.D=a;z(this.D!==l,"LeafNode shouldn't be created with null value.");this.Ta="undefined"!==typeof b?b:l}t=Wb.prototype;t.H=q(k);t.j=aa("Ta");t.$a=function(a){return new Wb(this.D,a)};t.O=function(){return Q};t.N=function(a){return G(a)===l?this:Q};t.ca=q(l);t.G=function(a,b){return(new R(new N,this.Ta)).G(a,b)};t.sa=function(a,b){var c=G(a);return c===l?b:this.G(c,Q.sa(Ja(a),b))};t.f=q(o);t.Kb=q(0);
t.T=function(a){return a&&this.j()!==l?{".value":this.k(),".priority":this.j()}:this.k()};t.hash=function(){var a="";this.j()!==l&&(a+="priority:"+Xb(this.j())+":");var b=typeof this.D,a=a+(b+":"),a="number"===b?a+Vb(this.D):a+this.D;return Hb(a)};t.k=aa("D");t.toString=function(){return"string"===typeof this.D?'"'+this.D+'"':this.D};function R(a,b){this.n=a||new N;this.Ta="undefined"!==typeof b?b:l}t=R.prototype;t.H=q(o);t.j=aa("Ta");t.$a=function(a){return new R(this.n,a)};t.G=function(a,b){var c=this.n.remove(a);b&&b.f()&&(b=l);b!==l&&(c=c.ma(a,b));return b&&b.j()!==l?new Yb(c,l,this.Ta):new R(c,this.Ta)};t.sa=function(a,b){var c=G(a);if(c===l)return b;var d=this.O(c).sa(Ja(a),b);return this.G(c,d)};t.f=function(){return this.n.f()};t.Kb=function(){return this.n.count()};var Zb=/^\d+$/;t=R.prototype;
t.T=function(a){if(this.f())return l;var b={},c=0,d=0,e=k;this.w(function(f,h){b[f]=h.T(a);c++;e&&Zb.test(f)?d=Math.max(d,Number(f)):e=o});if(!a&&e&&d<2*c){var f=[],h;for(h in b)f[h]=b[h];return f}a&&this.j()!==l&&(b[".priority"]=this.j());return b};t.hash=function(){var a="";this.j()!==l&&(a+="priority:"+Xb(this.j())+":");this.w(function(b,c){var d=c.hash();""!==d&&(a+=":"+b+":"+d)});return""===a?"":Hb(a)};t.O=function(a){a=this.n.get(a);return a===l?Q:a};
t.N=function(a){var b=G(a);return b===l?this:this.O(b).N(Ja(a))};t.ca=function(a){return Sa(this.n,a)};t.Uc=function(){return this.n.lb()};t.Vc=function(){return this.n.Ra()};t.w=function(a){return this.n.wa(a)};t.pc=function(a){return this.n.Ja(a)};t.Pa=function(){return this.n.Pa()};t.toString=function(){var a="{",b=k;this.w(function(c,d){b?b=o:a+=", ";a+='"'+c+'" : '+d.toString()});return a+="}"};var Q=new R(new N);function Yb(a,b,c){R.call(this,a,c);b===l&&(b=new N($b),a.wa(function(a,c){b=b.ma({name:a,ga:c.j()},c)}));this.oa=b}ja(Yb,R);t=Yb.prototype;t.G=function(a,b){var c=this.O(a),d=this.n,e=this.oa;c!==l&&(d=d.remove(a),e=e.remove({name:a,ga:c.j()}));b&&b.f()&&(b=l);b!==l&&(d=d.ma(a,b),e=e.ma({name:a,ga:b.j()},b));return new Yb(d,e,this.j())};t.ca=function(a,b){var c=Sa(this.oa,{name:a,ga:b.j()});return c?c.name:l};t.w=function(a){return this.oa.wa(function(b,c){return a(b.name,c)})};
t.pc=function(a){return this.oa.Ja(function(b,c){return a(b.name,c)})};t.Pa=function(){return this.oa.Pa(function(a,b){return{key:a.name,value:b}})};t.Uc=function(){return this.oa.f()?l:this.oa.lb().name};t.Vc=function(){return this.oa.f()?l:this.oa.Ra().name};function S(a,b){if(a===l)return Q;var c=l;"object"===typeof a&&".priority"in a?c=a[".priority"]:"undefined"!==typeof b&&(c=b);z(c===l||"string"===typeof c||"number"===typeof c||"object"===typeof c&&".sv"in c);"object"===typeof a&&(".value"in a&&a[".value"]!==l)&&(a=a[".value"]);if("object"!==typeof a||".sv"in a)return new Wb(a,c);if(a instanceof Array){var c=new R(new N,c),d;for(d in a)if(D(a,d)&&"."!==d.substring(0,1)){var e=S(a[d]);if(e.H()||!e.f())c=c.G(d,e)}return c}var f=[],h={},i=o;Tb(a,function(b,
c){if("string"!==typeof c||"."!==c.substring(0,1)){var d=S(a[c]);d.f()||(i=i||d.j()!==l,f.push({name:c,ga:d.j()}),h[c]=d)}});d=ac(f,h,o);return i?(e=ac(f,h,k),new Yb(d,e,c)):new R(d,c)}var bc=Math.log(2);function cc(a){this.count=parseInt(Math.log(a+1)/bc);this.Qc=this.count-1;this.od=a+1&parseInt(Array(this.count+1).join("1"),2)}
function ac(a,b,c){function d(d,f){var h=n-d,p=n;n-=d;var s=a[h].name,h=new Va(c?a[h]:s,b[s],f,l,e(h+1,p));i?i.left=h:m=h;i=h}function e(d,f){var h=f-d;if(0==h)return l;if(1==h){var h=a[d].name,i=c?a[d]:h;return new Va(i,b[h],o,l,l)}var i=parseInt(h/2)+d,m=e(d,i),n=e(i+1,f),h=a[i].name,i=c?a[i]:h;return new Va(i,b[h],o,m,n)}var f=c?$b:ec;a.sort(f);var h;h=new cc(a.length);for(var i=l,m=l,n=a.length,p=0;p<h.count;++p){var r=!(h.od&1<<h.Qc);h.Qc--;var s=Math.pow(2,h.count-(p+1));r?d(s,o):(d(s,o),d(s,
k))}h=m;return h!==l?new N(c?f:l,h):new N(c?f:l)}function $b(a,b){return Qb(a.ga,b.ga)||(a.name!==b.name?a.name<b.name?-1:1:0)}function ec(a,b){return a.name!==b.name?a.name<b.name?-1:1:0}function Xb(a){return"number"===typeof a?"number:"+Vb(a):"string:"+a};function T(a,b){this.z=a;this.Wb=b}T.prototype.T=function(){A("Firebase.DataSnapshot.val",0,0,arguments.length);return this.z.T()};T.prototype.val=T.prototype.T;T.prototype.sd=function(){A("Firebase.DataSnapshot.exportVal",0,0,arguments.length);return this.z.T(k)};T.prototype.exportVal=T.prototype.sd;T.prototype.F=function(a){A("Firebase.DataSnapshot.child",0,1,arguments.length);fa(a)&&(a=String(a));Fa("Firebase.DataSnapshot.child",a);var b=new K(a),c=this.Wb.F(b);return new T(this.z.N(b),c)};
T.prototype.child=T.prototype.F;T.prototype.rc=function(a){A("Firebase.DataSnapshot.hasChild",1,1,arguments.length);Fa("Firebase.DataSnapshot.hasChild",a);var b=new K(a);return!this.z.N(b).f()};T.prototype.hasChild=T.prototype.rc;T.prototype.j=function(){A("Firebase.DataSnapshot.getPriority",0,0,arguments.length);return this.z.j()};T.prototype.getPriority=T.prototype.j;
T.prototype.forEach=function(a){A("Firebase.DataSnapshot.forEach",1,1,arguments.length);C("Firebase.DataSnapshot.forEach",1,a,o);if(this.z.H())return o;var b=this;return this.z.w(function(c,d){return a(new T(d,b.Wb.F(c)))})};T.prototype.forEach=T.prototype.forEach;T.prototype.gb=function(){A("Firebase.DataSnapshot.hasChildren",0,0,arguments.length);return this.z.H()?o:!this.z.f()};T.prototype.hasChildren=T.prototype.gb;
T.prototype.name=function(){A("Firebase.DataSnapshot.name",0,0,arguments.length);return this.Wb.name()};T.prototype.name=T.prototype.name;T.prototype.Kb=function(){A("Firebase.DataSnapshot.numChildren",0,0,arguments.length);return this.z.Kb()};T.prototype.numChildren=T.prototype.Kb;T.prototype.Dc=function(){A("Firebase.DataSnapshot.ref",0,0,arguments.length);return this.Wb};T.prototype.ref=T.prototype.Dc;function fc(a){this.zc=a;this.Rb=[];this.Na=0;this.kc=-1;this.Ga=l};function Ub(a,b){for(var c in a)b.call(j,a[c],c,a)}function gc(a){var b={},c;for(c in a)b[c]=a[c];return b};function hc(){this.bb={}}function ic(a,b,c){u(c)||(c=1);D(a.bb,b)||(a.bb[b]=0);a.bb[b]+=c}hc.prototype.get=function(){return gc(this.bb)};function jc(a){this.pd=a;this.Ib=l}jc.prototype.get=function(){var a=this.pd.get(),b=gc(a);if(this.Ib)for(var c in this.Ib)b[c]-=this.Ib[c];this.Ib=a;return b};function kc(a,b){this.Jc={};this.bc=new jc(a);this.o=b;setTimeout(w(this.bd,this),10+6E4*Math.random())}kc.prototype.bd=function(){var a=this.bc.get(),b={},c=o,d;for(d in a)0<a[d]&&D(this.Jc,d)&&(b[d]=a[d],c=k);c&&(a=this.o,a.U&&(b={c:b},a.e("reportStats",b),a.Aa("s",b)));setTimeout(w(this.bd,this),6E5*Math.random())};var lc={},mc={};function nc(a){a=a.toString();lc[a]||(lc[a]=new hc);return lc[a]};var oc=l;"undefined"!==typeof MozWebSocket?oc=MozWebSocket:"undefined"!==typeof WebSocket&&(oc=WebSocket);function pc(a,b,c){this.lc=a;this.e=Mb(this.lc);this.frames=this.jb=l;this.Lc=0;this.Y=nc(b);this.Ma=(b.Zb?"wss://":"ws://")+b.da+"/.ws?v=5";b.host!==b.da&&(this.Ma=this.Ma+"&ns="+b.mb);c&&(this.Ma=this.Ma+"&s="+c)}var qc;
pc.prototype.open=function(a,b){this.fa=b;this.Bd=a;this.e("websocket connecting to "+this.Ma);this.W=new oc(this.Ma);this.eb=o;var c=this;this.W.onopen=function(){c.e("Websocket connected.");c.eb=k};this.W.onclose=function(){c.e("Websocket connection was disconnected.");c.W=l;c.Ha()};this.W.onmessage=function(a){if(c.W!==l)if(a=a.data,ic(c.Y,"bytes_received",a.length),rc(c),c.frames!==l)sc(c,a);else{a:{z(c.frames===l,"We already have a frame buffer");if(4>=a.length){var b=Number(a);if(!isNaN(b)){c.Lc=
b;c.frames=[];a=l;break a}}c.Lc=1;c.frames=[]}a!==l&&sc(c,a)}};this.W.onerror=function(a){c.e("WebSocket error.  Closing connection.");a.data&&c.e(a.data);c.Ha()}};pc.prototype.start=function(){};pc.isAvailable=function(){return!("undefined"!==typeof navigator&&"Opera"===navigator.appName)&&oc!==l&&!qc};function sc(a,b){a.frames.push(b);if(a.frames.length==a.Lc){var c=a.frames.join("");a.frames=l;c="undefined"!==typeof JSON&&u(JSON.parse)?JSON.parse(c):ka(c);a.Bd(c)}}
pc.prototype.send=function(a){rc(this);a=y(a);ic(this.Y,"bytes_sent",a.length);a=Sb(a,16384);1<a.length&&this.W.send(String(a.length));for(var b=0;b<a.length;b++)this.W.send(a[b])};pc.prototype.Bb=function(){this.Ea=k;this.jb&&(clearTimeout(this.jb),this.jb=l);this.W&&(this.W.close(),this.W=l)};pc.prototype.Ha=function(){this.Ea||(this.e("WebSocket is closing itself"),this.Bb(),this.fa&&(this.fa(this.eb),this.fa=l))};pc.prototype.close=function(){this.Ea||(this.e("WebSocket is being closed"),this.Bb())};
function rc(a){clearTimeout(a.jb);a.jb=setInterval(function(){a.W.send("0");rc(a)},45E3)};function tc(){this.set={}}t=tc.prototype;t.add=function(a,b){this.set[a]=b!==l?b:k};t.contains=function(a){return D(this.set,a)};t.get=function(a){return this.contains(a)?this.set[a]:j};t.remove=function(a){delete this.set[a]};t.f=function(){var a;a:{for(a in this.set){a=o;break a}a=k}return a};t.count=function(){var a=0,b;for(b in this.set)a++;return a};function U(a,b){for(var c in a.set)D(a.set,c)&&b(c,a.set[c])}t.keys=function(){var a=[],b;for(b in this.set)D(this.set,b)&&a.push(b);return a};var uc="pLPCommand",vc="pRTLPCB";function wc(a,b,c){this.lc=a;this.e=Mb(a);this.Nd=b;this.Y=nc(b);this.ac=c;this.eb=o;this.Eb=function(a){b.host!==b.da&&(a.ns=b.mb);var c=[],f;for(f in a)a.hasOwnProperty(f)&&c.push(f+"="+a[f]);return(b.Zb?"https://":"http://")+b.da+"/.lp?"+c.join("&")}}var xc,yc;
wc.prototype.open=function(a,b){function c(){if(!d.Ea){d.ha=new zc(function(a,b,c,e,f){ic(d.Y,"bytes_received",y(arguments).length);if(d.ha)if(d.Ca&&(clearTimeout(d.Ca),d.Ca=l),d.eb=k,"start"==a)d.id=b,d.ad=c;else if("close"===a)if(b){d.ha.$b=o;var h=d.Yc;h.kc=b;h.Ga=function(){d.Ha()};h.kc<h.Na&&(h.Ga(),h.Ga=l)}else d.Ha();else g(Error("Unrecognized command received: "+a))},function(a,b){ic(d.Y,"bytes_received",y(arguments).length);var c=d.Yc;for(c.Rb[a]=b;c.Rb[c.Na];){var e=c.Rb[c.Na];delete c.Rb[c.Na];
for(var f=0;f<e.length;++f)e[f]&&c.zc(e[f]);if(c.Na===c.kc){c.Ga&&(clearTimeout(c.Ga),c.Ga(),c.Ga=l);break}c.Na++}},function(){d.Ha()},d.Eb);var a={start:"t"};a.ser=Math.floor(1E8*Math.random());d.ha.dc&&(a.cb=d.ha.dc);a.v="5";d.ac&&(a.s=d.ac);a=d.Eb(a);d.e("Connecting via long-poll to "+a);Ac(d.ha,a,function(){})}}this.Pc=0;this.P=b;this.Yc=new fc(a);this.Ea=o;var d=this;this.Ca=setTimeout(function(){d.e("Timed out trying to connect.");d.Ha();d.Ca=l},3E4);if("complete"===document.readyState)c();
else{var e=o,f=function(){document.body?e||(e=k,c()):setTimeout(f,10)};document.addEventListener?(document.addEventListener("DOMContentLoaded",f,o),window.addEventListener("load",f,o)):document.attachEvent&&(document.attachEvent("onreadystatechange",function(){"complete"===document.readyState&&f()},o),window.attachEvent("onload",f,o))}};
wc.prototype.start=function(){var a=this.ha,b=this.ad;a.zd=this.id;a.Ad=b;for(a.gc=k;Bc(a););a=this.id;b=this.ad;this.Sa=document.createElement("iframe");var c={dframe:"t"};c.id=a;c.pw=b;a=this.Eb(c);this.Sa.src=a;this.Sa.style.display="none";document.body.appendChild(this.Sa)};wc.isAvailable=function(){return!yc&&!("object"===typeof window&&window.chrome&&window.chrome.extension&&!/^chrome/.test(window.location.href))&&(xc||k)};
wc.prototype.Bb=function(){this.Ea=k;this.ha&&(this.ha.close(),this.ha=l);this.Sa&&(document.body.removeChild(this.Sa),this.Sa=l);this.Ca&&(clearTimeout(this.Ca),this.Ca=l)};wc.prototype.Ha=function(){this.Ea||(this.e("Longpoll is closing itself"),this.Bb(),this.P&&(this.P(this.eb),this.P=l))};wc.prototype.close=function(){this.Ea||(this.e("Longpoll is being closed."),this.Bb())};
wc.prototype.send=function(a){a=y(a);ic(this.Y,"bytes_sent",a.length);for(var a=qa(a),a=Eb(a,k),a=Sb(a,1840),b=0;b<a.length;b++){var c=this.ha;c.tb.push({Hd:this.Pc,Md:a.length,Rc:a[b]});c.gc&&Bc(c);this.Pc++}};
function zc(a,b,c,d){this.Eb=d;this.fa=c;this.Bc=new tc;this.tb=[];this.mc=Math.floor(1E8*Math.random());this.$b=k;this.dc=Fb();window[uc+this.dc]=a;window[vc+this.dc]=b;a=document.createElement("iframe");a.style.display="none";if(document.body){document.body.appendChild(a);try{a.contentWindow.document||P("No IE domain setting required")}catch(e){a.src="javascript:void((function(){document.open();document.domain='"+document.domain+"';document.close();})())"}}else g("Document body has not initialized. Wait to initialize Firebase until after the document is ready.");
a.contentDocument?a.ua=a.contentDocument:a.contentWindow?a.ua=a.contentWindow.document:a.document&&(a.ua=a.document);this.V=a;a="";this.V.src&&"javascript:"===this.V.src.substr(0,11)&&(a='<script>document.domain="'+document.domain+'";<\/script>');a="<html><body>"+a+"</body></html>";try{this.V.ua.open(),this.V.ua.write(a),this.V.ua.close()}catch(f){P("frame writing exception"),f.stack&&P(f.stack),P(f)}}
zc.prototype.close=function(){this.gc=o;if(this.V){this.V.ua.body.innerHTML="";var a=this;setTimeout(function(){a.V!==l&&(document.body.removeChild(a.V),a.V=l)},0)}var b=this.fa;b&&(this.fa=l,b())};
function Bc(a){if(a.gc&&a.$b&&a.Bc.count()<(0<a.tb.length?2:1)){a.mc++;var b={};b.id=a.zd;b.pw=a.Ad;b.ser=a.mc;for(var b=a.Eb(b),c="",d=0;0<a.tb.length;)if(1870>=a.tb[0].Rc.length+30+c.length){var e=a.tb.shift(),c=c+"&seg"+d+"="+e.Hd+"&ts"+d+"="+e.Md+"&d"+d+"="+e.Rc;d++}else break;var b=b+c,f=a.mc;a.Bc.add(f);var h=function(){a.Bc.remove(f);Bc(a)},i=setTimeout(h,25E3);Ac(a,b,function(){clearTimeout(i);h()});return k}return o}
function Ac(a,b,c){setTimeout(function(){try{if(a.$b){var d=a.V.ua.createElement("script");d.type="text/javascript";d.async=k;d.src=b;d.onload=d.onreadystatechange=function(){var a=d.readyState;if(!a||"loaded"===a||"complete"===a)d.onload=d.onreadystatechange=l,d.parentNode&&d.parentNode.removeChild(d),c()};d.onerror=function(){P("Long-poll script failed to load: "+b);a.$b=o;a.close()};a.V.ua.body.appendChild(d)}}catch(e){}},1)};function Cc(){var a=[];Tb(Dc,function(b,c){c&&c.isAvailable()&&a.push(c)});this.cc=a}var Dc=[wc,{isAvailable:q(o)},pc];function Ec(a,b,c,d,e,f){this.id=a;this.e=Mb("c:"+this.id+":");this.zc=c;this.pb=d;this.P=e;this.yc=f;this.R=b;this.Qb=[];this.Oc=0;this.Nc=new Cc;this.qa=0;this.e("Connection created");Fc(this)}function Fc(a){var b;var c=a.Nc;0<c.cc.length?b=c.cc[0]:g(Error("No transports available"));a.J=new b("c:"+a.id+":"+a.Oc++,a.R);var d=Gc(a,a.J),e=Hc(a,a.J);a.Cb=a.J;a.zb=a.J;a.A=l;setTimeout(function(){a.J&&a.J.open(d,e)},0)}
function Hc(a,b){return function(c){b===a.J?(a.J=l,!c&&0===a.qa?(a.e("Realtime connection failed."),"s-"===a.R.da.substr(0,2)&&(mb.removeItem(a.R.mb),a.R.da=a.R.host)):1===a.qa&&a.e("Realtime connection lost."),a.close()):b===a.A?(c=a.A,a.A=l,(a.Cb===c||a.zb===c)&&a.close()):a.e("closing an old connection")}}
function Gc(a,b){return function(c){if(2!=a.qa)if(b===a.zb){var d=Rb("t",c),c=Rb("d",c);if("c"==d){if(d=Rb("t",c),"d"in c)if(c=c.d,"h"===d){var d=c.ts,e=c.v,f=c.h;a.ac=c.s;pb(a.R,f);if(0==a.qa&&(a.J.start(),c=a.J,a.e("Realtime connection established."),a.J=c,a.qa=1,a.pb&&(a.pb(d),a.pb=l),"5"!==e&&Pb("Protocol version mismatch detected"),c=1<a.Nc.cc.length?a.Nc.cc[1]:l))a.A=new c("c:"+a.id+":"+a.Oc++,a.R,a.ac),a.A.open(Gc(a,a.A),Hc(a,a.A))}else if("n"===d){a.e("recvd end transmission on primary");
a.zb=a.A;for(c=0;c<a.Qb.length;++c)a.Nb(a.Qb[c]);a.Qb=[];Ic(a)}else"s"===d?(a.e("Connection shutdown command received. Shutting down..."),a.yc&&(a.yc(c),a.yc=l),a.P=l,a.close()):"r"===d?(a.e("Reset packet received.  New host: "+c),pb(a.R,c),1===a.qa?a.close():(Jc(a),Fc(a))):"e"===d?Nb("Server Error: "+c):Nb("Unknown control packet command: "+d)}else"d"==d&&a.Nb(c)}else b===a.A?(d=Rb("t",c),c=Rb("d",c),"c"==d?"t"in c&&(c=c.t,"a"===c?(a.A.start(),a.e("sending client ack on secondary"),a.A.send({t:"c",
d:{t:"a",d:{}}}),a.e("Ending transmission on primary"),a.J.send({t:"c",d:{t:"n",d:{}}}),a.Cb=a.A,Ic(a)):"r"===c&&(a.e("Got a reset on secondary, closing it"),a.A.close(),(a.Cb===a.A||a.zb===a.A)&&a.close())):"d"==d?a.Qb.push(c):g(Error("Unknown protocol layer: "+d))):a.e("message on old connection")}}Ec.prototype.Fc=function(a){a={t:"d",d:a};1!==this.qa&&g("Connection is not connected");this.Cb.send(a)};
function Ic(a){a.Cb===a.A&&a.zb===a.A&&(a.e("cleaning up and promoting a connection: "+a.A.lc),a.J=a.A,a.A=l)}Ec.prototype.Nb=function(a){this.zc(a)};Ec.prototype.close=function(){2!==this.qa&&(this.e("Closing realtime connection."),this.qa=2,Jc(this),this.P&&(this.P(),this.P=l))};function Jc(a){a.e("Shutting down all connections");a.J&&(a.J.close(),a.J=l);a.A&&(a.A.close(),a.A=l)};function Kc(a,b,c,d,e){this.id=Nc++;this.e=Mb("p:"+this.id+":");this.Ab=k;this.ea={};this.S=[];this.qb=0;this.ob=[];this.U=o;this.Vb=1E3;this.Ob=b||ca;this.Mb=c||ca;this.nb=d||ca;this.Ac=e||ca;this.R=a;this.Ec=l;this.Sb=[];this.xb={};this.Gd=0;this.kb=this.Xc=l;this.nc=setTimeout(w(this.Sc,this),0)}var Nc=0,Oc=0;t=Kc.prototype;t.Aa=function(a,b,c){var d=++this.Gd,a={r:d,a:a,b:b};this.e(y(a));this.U?this.vb.Fc(a):this.Sb.push(a);c&&(this.xb[d]=c)};
function Pc(a,b,c,d,e){a.e("Listen on "+b+" for "+c);var f={p:b},d=hb(d,function(a){return Ha(a)});"{}"!==c&&(f.q=d);a.Aa("l",f,function(d){a.e("listen response",d);d=d.s;"ok"!==d&&Qc(a,b,c);e&&e(d)})}t.ab=function(a,b,c){this.Da={qd:a,Tc:o,ja:b,Gb:c};this.e("Authenticating using credential: "+this.Da);Rc(this)};t.Db=function(){delete this.Da;this.nb(o);this.U&&this.Aa("unauth",{})};
function Rc(a){var b=a.Da;a.U&&b&&a.Aa("auth",{cred:b.qd},function(c){var d=c.s,c=c.d||"error";"ok"!==d&&a.Da===b&&delete a.Da;a.nb("ok"===d);b.Tc?"ok"!==d&&b.Gb&&b.Gb(d,c):(b.Tc=k,b.ja&&b.ja(d,c))})}t.jd=function(a,b,c){a=a.toString();Qc(this,a,b)&&this.U&&(this.e("Unlisten on "+a+" for "+b),a={p:a},c=hb(c,function(a){return Ha(a)}),"{}"!==b&&(a.q=c),this.Aa("u",a))};function Sc(a,b,c,d){a.U?Tc(a,"o",b,c,d):a.ob.push({Cc:b,action:"o",data:c,C:d})}
t.xc=function(a,b){this.U?Tc(this,"oc",a,l,b):this.ob.push({Cc:a,action:"oc",data:l,C:b})};function Tc(a,b,c,d,e){c={p:c,d:d};a.e("onDisconnect "+b,c);a.Aa(b,c,function(a){e&&setTimeout(function(){e(a.s)},0)})}t.put=function(a,b,c,d){Uc(this,"p",a,b,c,d)};function Uc(a,b,c,d,e,f){c={p:c,d:d};u(f)&&(c.h=f);a.S.push({action:b,cd:c,C:e});a.qb++;b=a.S.length-1;a.U&&Vc(a,b)}
function Vc(a,b){var c=a.S[b].action,d=a.S[b].cd,e=a.S[b].C;a.S[b].Dd=a.U;a.Aa(c,d,function(d){a.e(c+" response",d);delete a.S[b];a.qb--;0===a.qb&&(a.S=[]);e&&e(d.s)})}
t.Nb=function(a){if("r"in a){this.e("from server: "+y(a));var b=a.r,c=this.xb[b];c&&(delete this.xb[b],c(a.b))}else"error"in a&&g("A server-side error has occurred: "+a.error),"a"in a&&(b=a.a,a=a.b,this.e("handleServerMessage",b,a),"d"===b?this.Ob(a.p,a.d):"m"===b?this.Ob(a.p,a.d,k):"c"===b?(b=a.p,a=(a=a.q)?hb(a,function(a){return Ia(a)}).join("$"):"{}",(a=Qc(this,b,a))&&a.C&&a.C("permission_denied")):"ac"===b?(b=a.s,a=a.d,c=this.Da,delete this.Da,c&&c.Gb&&c.Gb(b,a),this.nb(o)):"sd"===b?this.Ec?this.Ec(a):
"msg"in a&&"undefined"!==typeof console&&console.log("FIREBASE: "+a.msg.replace("\n","\nFIREBASE: ")):Nb("Unrecognized action received from server: "+y(b)+"\nAre you using the latest client?"))};
t.pb=function(a){this.e("connection ready");this.U=k;this.kb=(new Date).getTime();this.Ac({serverTimeOffset:a-(new Date).getTime()});for(a=0;a<this.Sb.length;a++)this.vb.Fc(this.Sb[a]);this.Sb=[];Rc(this);for(var b in this.ea)for(var c in this.ea[b])a=this.ea[b][c],Pc(this,b,c,a.Ua,a.C);for(b=0;b<this.S.length;b++)this.S[b]&&Vc(this,b);for(;this.ob.length;)b=this.ob.shift(),Tc(this,b.action,b.Cc,b.data,b.C);this.Mb(k)};
t.Zc=function(){this.U=o;this.e("data client disconnected");for(var a=w(function(){this.Sc()},this),b=0;b<this.S.length;b++){var c=this.S[b];c&&("h"in c.cd&&c.Dd)&&(c.C&&c.C("disconnect"),delete this.S[b],this.qb--)}0===this.qb&&(this.S=[]);if(this.Ab)this.kb&&(3E4<(new Date).getTime()-this.kb&&(this.Vb=1E3),this.kb=l),b=Math.max(0,this.Vb-((new Date).getTime()-this.Xc)),b*=Math.random(),this.e("Trying to reconnect in "+b+"ms"),setTimeout(a,b),this.Vb=Math.min(3E5,1.3*this.Vb);else{for(var d in this.xb)delete this.xb[d];
this.ed=function(){setTimeout(a,0)}}this.Mb(o)};t.Sc=function(){if(this.Ab){this.e("Making a connection attempt");this.Xc=(new Date).getTime();this.kb=l;var a=w(this.Nb,this),b=w(this.pb,this),c=w(this.Zc,this),d=this.id+":"+Oc++,e=this;this.vb=new Ec(d,this.R,a,b,c,function(a){e.Ab=o;g(Error(a))})}};t.Qa=function(){this.Ab=o;this.vb?this.vb.close():(this.nc&&(clearTimeout(this.nc),this.nc=l),this.Zc())};t.yb=function(){this.Ab=k;this.ed();this.ed=j};
function Qc(a,b,c){b=(new K(b)).toString();c||(c="{}");var d=a.ea[b][c];delete a.ea[b][c];return d};function Wc(){this.n=this.D=l}function Xc(a,b,c){if(b.f())a.D=c,a.n=l;else if(a.D!==l)a.D=a.D.sa(b,c);else{a.n==l&&(a.n=new tc);var d=G(b);a.n.contains(d)||a.n.add(d,new Wc);a=a.n.get(d);b=Ja(b);Xc(a,b,c)}}function Yc(a,b){if(b.f())return a.D=l,a.n=l,k;if(a.D!==l){if(a.D.H())return o;var c=a.D;a.D=l;c.w(function(b,c){Xc(a,new K(b),c)});return Yc(a,b)}return a.n!==l?(c=G(b),b=Ja(b),a.n.contains(c)&&Yc(a.n.get(c),b)&&a.n.remove(c),a.n.f()?(a.n=l,k):o):k}
function Zc(a,b,c){a.D!==l?c(b,a.D):a.w(function(a,e){var f=new K(b.toString()+"/"+a);Zc(e,f,c)})}Wc.prototype.w=function(a){this.n!==l&&U(this.n,function(b,c){a(b,c)})};function $c(){this.za=Q}function V(a,b){return a.za.N(b)}function W(a,b,c){a.za=a.za.sa(b,c)}$c.prototype.toString=function(){return this.za.toString()};function ad(){this.Ba=new $c;this.I=new $c;this.ta=new $c;this.sb=new Ma}function bd(a,b){for(var c=V(a.Ba,b),d=V(a.I,b),e=L(a.sb,b),f=o,h=e;h!==l;){if(h.k()!==l){f=k;break}h=h.parent()}if(f)return o;c=cd(c,d,e);return c!==d?(W(a.I,b,c),k):o}function cd(a,b,c){if(c.f())return a;if(c.k()!==l)return b;a=a||Q;c.w(function(d){var d=d.name(),e=a.O(d),f=b.O(d),h=L(c,d),e=cd(e,f,h);a=a.G(d,e)});return a}
ad.prototype.set=function(a,b){var c=this,d=[];gb(b,function(a){var b=a.path,a=a.Fa,h=Fb();M(L(c.sb,b),h);W(c.I,b,a);d.push({path:b,Id:h})});return d};function dd(a,b){gb(b,function(b){var d=b.Id,b=L(a.sb,b.path),e=b.k();z(e!==l,"pendingPut should not be null.");e===d&&M(b,l)})};function ed(){this.la=[]}ed.prototype.Va=function(){for(var a=0;a<this.la.length;a++)if(this.la[a]){var b=this.la[a];this.la[a]=l;var c=b.ja;c(b.gd,b.ub)}this.la=[]};function X(a,b,c,d){this.type=a;this.na=b;this.Z=c;this.ub=d};function fd(a){this.L=a;this.ka=[];this.oc=new ed}function gd(a,b,c,d,e){a.ka.push({type:b,ja:c,cancel:d,$:e});var d=[],f=hd(a.i);a.ib&&f.push(new X("value",a.i));for(var h=0;h<f.length;h++)if(f[h].type===b){var i=new J(a.L.u,a.L.path);f[h].Z&&(i=i.F(f[h].Z));d.push({ja:e?w(c,e):c,gd:new T(f[h].na,i),ub:f[h].ub})}a=a.oc;0!==d.length&&a.la.push.apply(a.la,d)}fd.prototype.Tb=function(a,b){b=this.Ub(a,b);b!=l&&id(this,b)};
function id(a,b){for(var c=[],d=0;d<b.length;d++){var e=b[d],f=e.type,h=new J(a.L.u,a.L.path);b[d].Z&&(h=h.F(b[d].Z));h=new T(b[d].na,h);"value"===e.type&&!h.gb()?f+="("+h.T()+")":"value"!==e.type&&(f+=" "+h.name());P(a.L.u.o.id+": event:"+a.L.path+":"+a.L.Ia()+":"+f);for(f=0;f<a.ka.length;f++){var i=a.ka[f];b[d].type===i.type&&c.push({ja:i.$?w(i.ja,i.$):i.ja,gd:h,ub:e.ub})}}d=a.oc;0!==c.length&&d.la.push.apply(d.la,c)}fd.prototype.Va=function(){this.oc.Va()};
function hd(a){var b=[];if(!a.H()){var c=l;a.w(function(a,e){b.push(new X("child_added",e,a,c));c=a})}return b}function jd(a){a.ib||(a.ib=k,id(a,[new X("value",a.i)]))};function kd(a,b){fd.call(this,a);this.i=b}ja(kd,fd);kd.prototype.Ub=function(a,b){this.i=a;this.ib&&b!=l&&b.push(new X("value",this.i));return b};kd.prototype.fb=function(){return{}};function ld(a,b){this.Hb=a;this.wc=b}
function md(a,b,c,d,e){var f=a.N(c),h=b.N(c),d=new ld(d,e),e=nd(d,c,f,h),h=!f.f()&&!h.f()&&f.j()!==h.j();if(e||h){f=c;for(c=e;f.parent()!==l;){var i=a.N(f),e=b.N(f),m=f.parent();if(!d.Hb||L(d.Hb,m).k()){var n=b.N(m),p=[],f=f.X<f.m.length?f.m[f.m.length-1]:l;i.f()?(i=n.ca(f,e),p.push(new X("child_added",e,f,i))):e.f()?p.push(new X("child_removed",i,f)):(i=n.ca(f,e),h&&p.push(new X("child_moved",e,f,i)),c&&p.push(new X("child_changed",e,f,i)));d.wc(m,n,p)}h&&(h=o,c=k);f=m}}}
function nd(a,b,c,d){var e,f=[];c===d?e=o:c.H()&&d.H()?e=c.k()!==d.k():c.H()?(od(a,b,Q,d,f),e=k):d.H()?(od(a,b,c,Q,f),e=k):e=od(a,b,c,d,f);e?a.wc(b,d,f):c.j()!==d.j()&&a.wc(b,d,l);return e}
function od(a,b,c,d,e){var f=o,h=!a.Hb||!L(a.Hb,b).f(),i=[],m=[],n=[],p=[],r={},s={},x,O,I,F;x=c.Pa();I=Ua(x);O=d.Pa();for(F=Ua(O);I!==l||F!==l;){c=I===l?1:F===l?-1:I.key===F.key?0:$b({name:I.key,ga:I.value.j()},{name:F.key,ga:F.value.j()});if(0>c)f=ta(r,I.key),u(f)?(n.push({qc:I,Kc:i[f]}),i[f]=l):(s[I.key]=m.length,m.push(I)),f=k,I=Ua(x);else{if(0<c)f=ta(s,F.key),u(f)?(n.push({qc:m[f],Kc:F}),m[f]=l):(r[F.key]=i.length,i.push(F)),f=k;else{c=b.F(F.key);if(c=nd(a,c,I.value,F.value))p.push(F),f=k;I.value.j()!==
F.value.j()&&(n.push({qc:I,Kc:F}),f=k);I=Ua(x)}F=Ua(O)}if(!h&&f)return k}for(h=0;h<m.length;h++)if(r=m[h])c=b.F(r.key),nd(a,c,r.value,Q),e.push(new X("child_removed",r.value,r.key));for(h=0;h<i.length;h++)if(r=i[h])c=b.F(r.key),m=d.ca(r.key,r.value),nd(a,c,Q,r.value),e.push(new X("child_added",r.value,r.key,m));for(h=0;h<n.length;h++)r=n[h].qc,i=n[h].Kc,c=b.F(i.key),m=d.ca(i.key,i.value),e.push(new X("child_moved",i.value,i.key,m)),(c=nd(a,c,r.value,i.value))&&p.push(i);for(h=0;h<p.length;h++)a=p[h],
m=d.ca(a.key,a.value),e.push(new X("child_changed",a.value,a.key,m));return f};function pd(){this.Q=this.ra=l;this.set={}}ja(pd,tc);t=pd.prototype;t.setActive=function(a){this.ra=a};function qd(a){return a.contains("default")}function rd(a){return a.ra!=l&&qd(a)}t.defaultView=function(){return qd(this)?this.get("default"):l};t.path=aa("Q");t.toString=function(){return hb(this.keys(),function(a){return"default"===a?"{}":a}).join("$")};t.Ua=function(){var a=[];U(this,function(b,c){a.push(c.L)});return a};function sd(a,b){fd.call(this,a);this.i=Q;this.Ub(b,hd(b))}ja(sd,fd);
sd.prototype.Ub=function(a,b){if(b===l)return b;var c=[],d=this.L;u(d.ba)&&(u(d.pa)&&d.pa!=l?c.push(function(a,b){var c=Qb(b,d.ba);return 0<c||0===c&&a>=d.pa}):c.push(function(a,b){return 0<=Qb(b,d.ba)}));u(d.va)&&(u(d.Oa)?c.push(function(a,b){var c=Qb(b,d.va);return 0>c||0===c&&a<=d.Oa}):c.push(function(a,b){return 0>=Qb(b,d.va)}));var e=l,f=l;if(u(this.L.xa))if(u(this.L.ba)){if(e=td(a,c,this.L.xa,o)){var h=a.O(e).j();c.push(function(a,b){var c=Qb(b,h);return 0>c||0===c&&a<=e})}}else if(f=td(a,c,
this.L.xa,k)){var i=a.O(f).j();c.push(function(a,b){var c=Qb(b,i);return 0<c||0===c&&a>=f})}for(var m=[],n=[],p=[],r=[],s=0;s<b.length;s++){var x=b[s].Z,O=b[s].na;switch(b[s].type){case "child_added":ud(c,x,O)&&(this.i=this.i.G(x,O),n.push(b[s]));break;case "child_removed":this.i.O(x).f()||(this.i=this.i.G(x,l),m.push(b[s]));break;case "child_changed":!this.i.O(x).f()&&ud(c,x,O)&&(this.i=this.i.G(x,O),r.push(b[s]));break;case "child_moved":var I=!this.i.O(x).f(),F=ud(c,x,O);I?F?(this.i=this.i.G(x,
O),p.push(b[s])):(m.push(new X("child_removed",this.i.O(x),x)),this.i=this.i.G(x,l)):F&&(this.i=this.i.G(x,O),n.push(b[s]))}}var Lc=e||f;if(Lc){var Mc=(s=f!==l)?this.i.Uc():this.i.Vc(),dc=o,Wa=o,Xa=this;(s?a.pc:a.w).call(a,function(a,b){!Wa&&Mc===l&&(Wa=k);if(Wa&&dc)return k;dc?(m.push(new X("child_removed",Xa.i.O(a),a)),Xa.i=Xa.i.G(a,l)):Wa&&(n.push(new X("child_added",b,a)),Xa.i=Xa.i.G(a,b));Mc===a&&(Wa=k);a===Lc&&(dc=k)})}for(s=0;s<n.length;s++)c=n[s],x=this.i.ca(c.Z,c.na),m.push(new X("child_added",
c.na,c.Z,x));for(s=0;s<p.length;s++)c=p[s],x=this.i.ca(c.Z,c.na),m.push(new X("child_moved",c.na,c.Z,x));for(s=0;s<r.length;s++)c=r[s],x=this.i.ca(c.Z,c.na),m.push(new X("child_changed",c.na,c.Z,x));this.ib&&0<m.length&&m.push(new X("value",this.i));return m};function td(a,b,c,d){if(a.H())return l;var e=l;(d?a.pc:a.w).call(a,function(a,d){if(ud(b,a,d)&&(e=a,c--,0===c))return k});return e}function ud(a,b,c){for(var d=0;d<a.length;d++)if(!a[d](b,c.j()))return o;return k}
sd.prototype.rc=function(a){return this.i.O(a)!==Q};sd.prototype.fb=function(a,b,c){var d={};this.i.H()||this.i.w(function(a){d[a]=k});var e=this.i,c=V(c,new K("")),f=new Ma;M(L(f,this.L.path),k);var h=Q.sa(a,b),i=[];md(c,h,a,f,function(a,b,c){c!==l&&(i=i.concat(c))});this.Ub(b,i);this.i.H()||this.i.w(function(a){d[a]=k});this.i=e;return d};function vd(a,b){this.o=a;this.g=b;this.uc=b.za;this.ia=new Ma}
vd.prototype.Fb=function(a,b,c,d,e){var f=a.path,h=L(this.ia,f),i=h.k();i===l?(i=new pd,M(h,i)):z(!i.f(),"We shouldn't be storing empty QueryMaps");var m=a.Ia();if(i.contains(m))a=i.get(m),gd(a,b,c,d,e);else{var n=this.g.za.N(f),n=a="default"===a.Ia()?new kd(a,n):new sd(a,n);if(rd(i)||wd(h))i.add(m,n),i.Q||(i.Q=n.L.path);else{var p,r;i.f()||(p=i.toString(),r=i.Ua());i.add(m,n);i.Q||(i.Q=n.L.path);i.setActive(xd(this,i));p&&r&&this.o.jd(i.path(),p,r)}rd(i)&&Oa(h,function(a){if(a=a.k()){a.ra&&a.ra();
a.ra=l}});gd(a,b,c,d,e);(b=(b=Pa(L(this.ia,f),function(a){var b;if(b=a.k())if(b=a.k().defaultView())b=a.k().defaultView().ib;if(b)return k},k))||this.o===l&&!V(this.g,f).f())&&jd(a)}a.Va()};function yd(a,b,c,d,e){var f=a.get(b),h;if(h=f){h=o;for(var i=f.ka.length-1;0<=i;i--){var m=f.ka[i];if((!c||m.type===c)&&(!d||m.ja===d)&&(!e||m.$===e))if(f.ka.splice(i,1),h=k,c&&d)break}h=h&&!(0<f.ka.length)}(c=h)&&a.remove(b);return c}
vd.prototype.Xb=function(a,b,c,d){var e=L(this.ia,a.path).k();return e===l?l:zd(this,e,a,b,c,d)};
function zd(a,b,c,d,e,f){var h=b.path(),h=L(a.ia,h),c=c?c.Ia():l,i=[];c&&"default"!==c?yd(b,c,d,e,f)&&i.push(c):gb(b.keys(),function(a){yd(b,a,d,e,f)&&i.push(a)});b.f()&&M(h,l);c=wd(h);if(0<i.length&&!c){for(var m=h,n=h.parent(),c=o;!c&&n;){var p=n.k();if(p){z(!rd(p));var r=m.name(),s=o;U(p,function(a,b){s=b.rc(r)||s});s&&(c=k)}m=n;n=n.parent()}m=l;if(!rd(b)){n=b.ra;b.ra=l;var x=[],O=function(b){var c=b.k();if(c&&qd(c))x.push(c.path()),c.ra==l&&c.setActive(xd(a,c));else{if(c){c.ra!=l||c.setActive(xd(a,
c));var d={};U(c,function(a,b){b.i.w(function(a){D(d,a)||(d[a]=k,a=c.path().F(a),x.push(a))})})}b.w(O)}};O(h);m=x;n&&n()}return c?l:m}return l}function Ad(a,b,c){Oa(L(a.ia,b),function(a){(a=a.k())&&U(a,function(a,b){jd(b)})},c,k)}
function Bd(a,b,c){function d(a){for(var b=0;b<c.length;++b)if(c[b].contains(a))return k;return o}var e=a.uc,f=a.g.za;a.uc=f;md(e,f,b,a.ia,function(c,e,f){if(b.contains(c)){var n=d(c);n&&Ad(a,c,o);a.Tb(c,e,f);n&&Ad(a,c,k)}else a.Tb(c,e,f)});d(b)&&Ad(a,b,k);e=L(a.ia,b);Oa(e,function(a){(a=a.k())&&U(a,function(a,b){b.Va()})},k,k);Pa(e,function(a){(a=a.k())&&U(a,function(a,b){b.Va()})},o)}vd.prototype.Tb=function(a,b,c){a=L(this.ia,a).k();a!==l&&U(a,function(a,e){e.Tb(b,c)})};
function wd(a){return Pa(a,function(a){return a.k()&&rd(a.k())})}
function xd(a,b){if(a.o){var c=b.keys(),d=a.o,e=function(d){if("ok"!==d){var e="Unknown Error";"too_big"===d?e="The data requested exceeds the maximum size that can be accessed with a single request.":"permission_denied"==d&&(e="Client doesn't have permission to access the desired data.");var f=Error(d+": "+e);f.code=d.toUpperCase();Pb("on() or once() for "+b.path().toString()+" failed: "+f.toString());b&&(U(b,function(a,b){for(var c=0;c<b.ka.length;c++){var d=b.ka[c];d.cancel&&(d.$?w(d.cancel,d.$):
d.cancel)(f)}}),zd(a,b))}else gb(c,function(a){(a=b.get(a))&&jd(a)}),gb(c,function(a){(a=b.get(a))&&a.Va()})},f=b.toString(),h=b.path().toString();d.ea[h]=d.ea[h]||{};z(!d.ea[h][f],"listen() called twice for same path/queryId.");d.ea[h][f]={Ua:b.Ua(),C:e};d.U&&Pc(d,h,f,b.Ua(),e);return w(a.o.jd,a.o,b.path(),b.toString(),b.Ua())}return ca}
vd.prototype.fb=function(a,b,c,d){var e={};U(b,function(b,h){var i=h.fb(a,c,d);Ub(i,function(a,b){e[b]=a?k:ta(e,b)||o})});c.H()||c.w(function(a){D(e,a)||(e[a]=o)});return e};
function Cd(a,b,c,d,e,f){var h=b.path();if(f!==l){var i=[];d.H()||d.w(function(a,b){i.push({path:h.F(a),Fa:b});delete f[a]});Ub(f,function(a,b){i.push({path:h.F(b),Fa:Q})});return i}var b=a.fb(h,b,d,e),m=Q,n=[];Ub(b,function(b,f){var h=new K(f);b?m=m.G(f,d.N(h)):n=n.concat(Dd(a,d.N(h),L(c,h),e))});return[{path:h,Fa:m}].concat(n)}
function Ed(a,b,c,d,e){for(var f=L(a.ia,b),h=f.parent(),i=o;!i&&h!==l;){var m=h.k();m!==l&&(qd(m)?i=k:(m=a.fb(b,m,c,d),f=f.name(),ta(m,f)&&(i=k)));f=h;h=h.parent()}if(i)return[{path:b,Fa:c}];h=L(a.ia,b);i=h.k();return i!==l?qd(i)?[{path:b,Fa:c}]:Cd(a,i,h,c,d,e):Dd(a,c,h,d)}function Dd(a,b,c,d){var e=c.k();if(e!==l)return qd(e)?[{path:c.path(),Fa:b}]:Cd(a,e,c,b,d,l);var f=[];c.w(function(c){var e=b.H()?Q:b.O(c.name()),c=Dd(a,e,c,d);f=f.concat(c)});return f};function Fd(a,b){if(!a||"object"!==typeof a)return a;z(".sv"in a,"Unexpected leaf node or priority contents");return b[a[".sv"]]}function Gd(a,b){var c=Fd(a.j(),b),d;if(a.H()){var e=Fd(a.k(),b);return e!==a.k()||c!==a.j()?new Wb(e,c):a}d=a;c!==a.j()&&(d=d.$a(c));a.w(function(a,c){var e=Gd(c,b);e!==c&&(d=d.G(a,e))});return d};function Hd(a){this.R=a;this.Y=nc(a);this.o=new Kc(this.R,w(this.Ob,this),w(this.Mb,this),w(this.nb,this),w(this.Ac,this));var b=w(function(){return new kc(this.Y,this.o)},this),a=a.toString();mc[a]||(mc[a]=b());this.hd=mc[a];this.Ya=new Ma;this.Za=new $c;this.g=new ad;this.M=new vd(this.o,this.g.ta);this.sc=new $c;this.tc=new vd(l,this.sc);Id(this,"connected",o);Id(this,"authenticated",o);this.P=new Wc}t=Hd.prototype;t.toString=function(){return(this.R.Zb?"https://":"http://")+this.R.host};
t.name=function(){return this.R.mb};function Jd(a){a=V(a.sc,new K(".info/serverTimeOffset")).T()||0;return(new Date).getTime()+a}function Kd(a){a=a={timestamp:Jd(a)};a.timestamp=a.timestamp||(new Date).getTime();return a}
t.Ob=function(a,b,c){var d,e=[];if(9<=a.length&&a.lastIndexOf(".priority")===a.length-9)a=new K(a.substring(0,a.length-9)),d=V(this.g.Ba,a).$a(b),e.push(a);else if(c){a=new K(a);d=V(this.g.Ba,a);for(var f in b){var h=new K(f);d=d.sa(h,S(b[f]));e.push(a.F(f))}}else a=new K(a),d=S(b),e.push(a);b=Ed(this.M,a,d,this.g.I,c?b:l);c=o;for(f=0;f<b.length;++f){d=b[f];var h=this.g,i=d.path;W(h.Ba,i,d.Fa);c=bd(h,i)||c}c&&(a=Ld(this,a));Bd(this.M,a,e)};
t.Mb=function(a){Id(this,"connected",a);if(a===o){this.e("onDisconnectEvents");var b=this,c=[],d=Kd(this),a=Zc,e=new Wc;Zc(this.P,new K(""),function(a,b){Xc(e,a,Gd(b,d))});a(e,new K(""),function(a,d){var e=Ed(b.M,a,d,b.g.I,l);c.push.apply(c,b.g.set(a,e));e=Md(b,a);Ld(b,e);Bd(b.M,e,[a])});dd(this.g,c);this.P=new Wc}};t.Ac=function(a){var b=this;Tb(a,function(a,d){Id(b,d,a)})};t.nb=function(a){Id(this,"authenticated",a)};function Id(a,b,c){b=new K("/.info/"+b);W(a.sc,b,S(c));Bd(a.tc,b,[b])}
t.ab=function(a,b,c){this.o.ab(a,function(a,c){Nd(b,a,c)},function(a,b){Pb("auth() was canceled: "+b);if(c){var f=Error(b);f.code=a.toUpperCase();c(f)}})};t.Db=function(){this.o.Db()};
t.Xa=function(a,b,c,d){this.e("set",{path:a.toString(),value:b,ga:c});var e=Kd(this),b=S(b,c),e=Gd(b,e),e=Ed(this.M,a,e,this.g.I,l),f=this.g.set(a,e),h=this;this.o.put(a.toString(),b.T(k),function(b){"ok"!==b&&Pb("set at "+a+" failed: "+b);dd(h.g,f);bd(h.g,a);var c=Ld(h,a);Bd(h.M,c,[]);Nd(d,b)});e=Md(this,a);Ld(this,e);Bd(this.M,e,[a])};
t.update=function(a,b,c){this.e("update",{path:a.toString(),value:b});var d=V(this.g.ta,a),e=k,f=[],h=Kd(this),i;for(i in b){var e=o,m=S(b[i]),m=Gd(m,h),d=d.G(i,m);f.push(a.F(i))}if(e)P("update() called with empty data.  Don't do anything."),Nd(c,"ok");else{var d=Ed(this.M,a,d,this.g.I,b),n=this.g.set(a,d),p=this;Uc(this.o,"m",a.toString(),b,function(b){z("ok"===b||"permission_denied"===b,"merge at "+a+" failed.");dd(p.g,n);Nd(c,b)},j);b=Md(this,a);Ld(this,b);Bd(p.M,b,f)}};
t.Gc=function(a,b,c){this.e("setPriority",{path:a.toString(),ga:b});var d=Kd(this),d=Fd(b,d),d=V(this.g.I,a).$a(d),d=Ed(this.M,a,d,this.g.I,l),e=this.g.set(a,d),f=this;this.o.put(a.toString()+"/.priority",b,function(a){dd(f.g,e);Nd(c,a)});a=Ld(this,a);Bd(f.M,a,[])};t.xc=function(a,b){var c=this;this.o.xc(a.toString(),function(d){"ok"===d&&Yc(c.P,a);Nd(b,d)})};function Od(a,b,c,d){var e=S(c);Sc(a.o,b.toString(),e.T(k),function(c){"ok"===c&&Xc(a.P,b,e);Nd(d,c)})}
function Pd(a){ic(a.Y,"deprecated_on_disconnect");a.hd.Jc.deprecated_on_disconnect=k}t.Fb=function(a,b,c,d,e){".info"===G(a.path)?this.tc.Fb(a,b,c,d,e):this.M.Fb(a,b,c,d,e)};t.Xb=function(a,b,c,d){if(".info"===G(a.path))this.tc.Xb(a,b,c,d);else{b=this.M.Xb(a,b,c,d);if(c=b!==l){for(var c=this.g,d=a.path,e=[],f=0;f<b.length;++f)e[f]=V(c.Ba,b[f]);W(c.Ba,d,Q);for(f=0;f<b.length;++f)W(c.Ba,b[f],e[f]);c=bd(c,d)}c&&(W(this.g.ta,a.path,V(this.g.I,a.path)),this.M.uc=this.g.ta.za)}};t.Qa=function(){this.o.Qa()};
t.yb=function(){this.o.yb()};t.Hc=function(a){if("undefined"!==typeof console){a?(this.bc||(this.bc=new jc(this.Y)),a=this.bc.get()):a=this.Y.get();var b=a,c=[],d=0,e;for(e in b)c[d++]=e;var f=function(a,b){return Math.max(b.length,a)};if(c.reduce)e=c.reduce(f,0);else{var h=0;gb(c,function(a){h=f.call(j,h,a)});e=h}for(var i in a){b=a[i];for(c=i.length;c<e+2;c++)i+=" ";console.log(i+b)}}};t.Ic=function(a){ic(this.Y,a);this.hd.Jc[a]=k};t.e=function(){P("r:"+this.o.id+":",arguments)};
function Nd(a,b,c){if(a)if("ok"==b)a(l,c);else{var d=b=(b||"error").toUpperCase();c&&(d+=": "+c);c=Error(d);c.code=b;a(c)}};function Qd(a,b){var c=b||a.Ya;b||Rd(a,c);if(c.k()!==l){var d=Sd(a,c);z(0<d.length);if(2!==d[0].status&&4!==d[0].status){for(var e=c.path(),f=0;f<d.length;f++)z(1===d[f].status,"tryToSendTransactionQueue_: items in queue should all be run."),d[f].status=2,d[f].fd++;c=V(a.g.I,e).hash();W(a.g.I,e,V(a.g.ta,e));for(var h=V(a.Za,e).T(k),i=Fb(),m={},n=0;n<d.length;n++)d[n].hc&&(m[d[n].path.toString()]=d[n].path);var p=[],r;for(r in m)p.push(m[r]);for(f=0;f<p.length;f++)M(L(a.g.sb,p[f]),i);a.o.put(e.toString(),
h,function(b){a.e("transaction put response",{path:e.toString(),status:b});for(f=0;f<p.length;f++){var c=L(a.g.sb,p[f]),h=c.k();z(h!==l,"sendTransactionQueue_: pendingPut should not be null.");h===i&&(M(c,l),W(a.g.I,p[f],V(a.g.Ba,p[f])))}if("ok"===b){b=[];for(f=0;f<d.length;f++)d[f].status=3,d[f].C&&(c=Td(a,d[f].path),b.push(w(d[f].C,l,l,k,c))),d[f].ec();Rd(a,L(a.Ya,e));Qd(a);for(f=0;f<b.length;f++)b[f]()}else{if("datastale"===b)for(f=0;f<d.length;f++)d[f].status=4===d[f].status?5:1;else{Pb("transaction at "+
e+" failed: "+b);for(f=0;f<d.length;f++)d[f].status=5,d[f].fc=b}b=Ld(a,e);Bd(a.M,b,[e])}},c)}}else c.gb()&&c.w(function(b){Qd(a,b)})}
function Ld(a,b){var c=Ud(a,b),d=c.path(),e=Sd(a,c);W(a.g.ta,d,V(a.g.I,d));W(a.Za,d,V(a.g.I,d));if(0!==e.length){for(var f=c=V(a.g.ta,d),h=[],i=0;i<e.length;i++){var m=Ka(d,e[i].path),n=o,p;z(m!==l,"rerunTransactionsUnderNode_: relativePath should not be null.");if(5===e[i].status)n=k,p=e[i].fc;else if(1===e[i].status)if(25<=e[i].fd)n=k,p="maxretry";else{var r=e[i].update(c.N(m).T());u(r)?(ya("transaction failed: Data returned ",r),r=S(r),c=c.sa(m,r),e[i].hc&&(f=f.sa(m,r))):(n=k,p="nodata")}n&&(e[i].ec(),
e[i].status=3,e[i].C&&(n=new J(a,e[i].path),m=new T(c.N(m),n),"nodata"===p?h.push(w(e[i].C,l,l,o,m)):h.push(w(e[i].C,l,Error(p),o,m))))}p=V(a.g.I,d).j();c=c.$a(p);f=f.$a(p);W(a.Za,d,c);W(a.g.ta,d,f);Rd(a,a.Ya);for(i=0;i<h.length;i++)h[i]();Qd(a)}return d}function Ud(a,b){for(var c,d=a.Ya;(c=G(b))!==l&&d.k()===l;)d=L(d,c),b=Ja(b);return d}function Sd(a,b){var c=[];Vd(a,b,c);c.sort(function(a,b){return a.$c-b.$c});return c}
function Vd(a,b,c){var d=b.k();if(d!==l)for(var e=0;e<d.length;e++)c.push(d[e]);b.w(function(b){Vd(a,b,c)})}function Rd(a,b){var c=b.k();if(c){for(var d=0,e=0;e<c.length;e++)3!==c[e].status&&(c[d]=c[e],d++);c.length=d;M(b,0<c.length?c:l)}b.w(function(b){Rd(a,b)})}function Md(a,b){var c=Ud(a,b).path(),d=L(a.Ya,b);Pa(d,function(a){Wd(a)});Wd(d);Oa(d,function(a){Wd(a)});return c}
function Wd(a){var b=a.k();if(b!==l){for(var c=[],d=-1,e=0;e<b.length;e++)4!==b[e].status&&(2===b[e].status?(z(d===e-1,"All SENT items should be at beginning of queue."),d=e,b[e].status=4,b[e].fc="set"):(z(1===b[e].status),b[e].ec(),b[e].C&&c.push(w(b[e].C,l,Error("set"),o,l))));-1===d?M(a,l):b.length=d+1;for(e=0;e<c.length;e++)c[e]()}}function Td(a,b){var c=new J(a,b);return new T(V(a.Za,b),c)};function Y(){this.Wa={}}Y.vd=function(){return Y.Wc?Y.Wc:Y.Wc=new Y};Y.prototype.Qa=function(){for(var a in this.Wa)this.Wa[a].Qa()};Y.prototype.interrupt=Y.prototype.Qa;Y.prototype.yb=function(){for(var a in this.Wa)this.Wa[a].yb()};Y.prototype.resume=Y.prototype.yb;var Z={wd:function(a){var b=R.prototype.hash;R.prototype.hash=a;var c=Wb.prototype.hash;Wb.prototype.hash=a;return function(){R.prototype.hash=b;Wb.prototype.hash=c}}};Z.hijackHash=Z.wd;Z.Ia=function(a){return a.Ia()};Z.queryIdentifier=Z.Ia;Z.yd=function(a){return a.u.o.ea};Z.listens=Z.yd;Z.Ed=function(a){return a.u.o.vb};Z.refConnection=Z.Ed;Z.ld=Kc;Z.DataConnection=Z.ld;Kc.prototype.sendRequest=Kc.prototype.Aa;Kc.prototype.interrupt=Kc.prototype.Qa;Z.md=Ec;Z.RealTimeConnection=Z.md;
Ec.prototype.sendRequest=Ec.prototype.Fc;Ec.prototype.close=Ec.prototype.close;Z.kd=ob;Z.ConnectionTarget=Z.kd;Z.td=function(){xc=qc=k};Z.forceLongPolling=Z.td;Z.ud=function(){yc=k};Z.forceWebSockets=Z.ud;Z.Kd=function(a,b){a.u.o.Ec=b};Z.setSecurityDebugCallback=Z.Kd;Z.Hc=function(a,b){a.u.Hc(b)};Z.stats=Z.Hc;Z.Ic=function(a,b){a.u.Ic(b)};Z.statsIncrementCounter=Z.Ic;function $(a,b,c){this.wb=a;this.Q=b;this.ya=c}$.prototype.cancel=function(a){A("Firebase.onDisconnect().cancel",0,1,arguments.length);C("Firebase.onDisconnect().cancel",1,a,k);this.wb.xc(this.Q,a)};$.prototype.cancel=$.prototype.cancel;$.prototype.remove=function(a){A("Firebase.onDisconnect().remove",0,1,arguments.length);E("Firebase.onDisconnect().remove",this.Q);C("Firebase.onDisconnect().remove",1,a,k);Od(this.wb,this.Q,l,a)};$.prototype.remove=$.prototype.remove;
$.prototype.set=function(a,b){A("Firebase.onDisconnect().set",1,2,arguments.length);E("Firebase.onDisconnect().set",this.Q);xa("Firebase.onDisconnect().set",a,o);C("Firebase.onDisconnect().set",2,b,k);Od(this.wb,this.Q,a,b)};$.prototype.set=$.prototype.set;
$.prototype.Xa=function(a,b,c){A("Firebase.onDisconnect().setWithPriority",2,3,arguments.length);E("Firebase.onDisconnect().setWithPriority",this.Q);xa("Firebase.onDisconnect().setWithPriority",a,o);Ca("Firebase.onDisconnect().setWithPriority",2,b,o);C("Firebase.onDisconnect().setWithPriority",3,c,k);(".length"===this.ya||".keys"===this.ya)&&g("Firebase.onDisconnect().setWithPriority failed: "+this.ya+" is a read-only object.");var d=this.wb,e=this.Q,f=S(a,b);Sc(d.o,e.toString(),f.T(k),function(a){"ok"===
a&&Xc(d.P,e,f);Nd(c,a)})};$.prototype.setWithPriority=$.prototype.Xa;
$.prototype.update=function(a,b){A("Firebase.onDisconnect().update",1,2,arguments.length);E("Firebase.onDisconnect().update",this.Q);Ba("Firebase.onDisconnect().update",a);C("Firebase.onDisconnect().update",2,b,k);var c=this.wb,d=this.Q,e=k,f;for(f in a)e=o;if(e)P("onDisconnect().update() called with empty data.  Don't do anything."),Nd(b,k);else{e=c.o;f=d.toString();var h=function(e){if("ok"===e)for(var f in a){var h=S(a[f]);Xc(c.P,d.F(f),h)}Nd(b,e)};e.U?Tc(e,"om",f,a,h):e.ob.push({Cc:f,action:"om",
data:a,C:h})}};$.prototype.update=$.prototype.update;var Xd,Yd=0,Zd=[];Xd=function(a){var b=a===Yd;Yd=a;for(var c=Array(8),d=7;0<=d;d--)c[d]="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(a%64),a=Math.floor(a/64);z(0===a);a=c.join("");if(b){for(d=11;0<=d&&63===Zd[d];d--)Zd[d]=0;Zd[d]++}else for(d=0;12>d;d++)Zd[d]=Math.floor(64*Math.random());for(d=0;12>d;d++)a+="-0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz".charAt(Zd[d]);z(20===a.length,"NextPushId: Length should be 20.");return a};function J(){var a,b,c;if(arguments[0]instanceof Hd)c=arguments[0],a=arguments[1];else{A("new Firebase",1,2,arguments.length);var d=arguments[0];b=a="";var e=k,f="";if(v(d)){var h=d.indexOf("//");if(0<=h)var i=d.substring(0,h-1),d=d.substring(h+2);h=d.indexOf("/");-1===h&&(h=d.length);a=d.substring(0,h);var d=d.substring(h+1),m=a.split(".");if(3==m.length){h=m[2].indexOf(":");e=0<=h?"https"===i:k;if("firebase"===m[1])Ob(a+" is no longer supported. Please use <YOUR FIREBASE>.firebaseio.com instead");
else{b=m[0];f="";d=("/"+d).split("/");for(i=0;i<d.length;i++)if(0<d[i].length){h=d[i];try{h=decodeURIComponent(h.replace(/\+/g," "))}catch(n){}f+="/"+h}}b=b.toLowerCase()}else b=l}e||"undefined"!==typeof window&&(window.location&&window.location.protocol&&-1!==window.location.protocol.indexOf("https:"))&&Pb("Insecure Firebase access from a secure page. Please use https in calls to new Firebase().");a=new ob(a,e,b);b=new K(f);e=b.toString();if(!(d=!v(a.host)))if(!(d=0===a.host.length))if(!(d=!wa(a.mb)))if(d=
0!==e.length)e&&(e=e.replace(/^\/*\.info(\/|$)/,"/")),d=!(v(e)&&0!==e.length&&!va.test(e));d&&g(Error(B("new Firebase",1,o)+'must be a valid firebase URL and the path can\'t contain ".", "#", "$", "[", or "]".'));arguments[1]?arguments[1]instanceof Y?c=arguments[1]:g(Error("Expected a valid Firebase.Context for second argument to new Firebase()")):c=Y.vd();e=a.toString();d=ta(c.Wa,e);d||(d=new Hd(a),c.Wa[e]=d);c=d;a=b}H.call(this,c,a)}ja(J,H);var $d=J,ae=["Firebase"],be=ba;
!(ae[0]in be)&&be.execScript&&be.execScript("var "+ae[0]);for(var ce;ae.length&&(ce=ae.shift());)!ae.length&&u($d)?be[ce]=$d:be=be[ce]?be[ce]:be[ce]={};J.prototype.name=function(){A("Firebase.name",0,0,arguments.length);return this.path.f()?l:this.path.X<this.path.m.length?this.path.m[this.path.m.length-1]:l};J.prototype.name=J.prototype.name;
J.prototype.F=function(a){A("Firebase.child",1,1,arguments.length);if(fa(a))a=String(a);else if(!(a instanceof K))if(G(this.path)===l){var b=a;b&&(b=b.replace(/^\/*\.info(\/|$)/,"/"));Fa("Firebase.child",b)}else Fa("Firebase.child",a);return new J(this.u,this.path.F(a))};J.prototype.child=J.prototype.F;J.prototype.parent=function(){A("Firebase.parent",0,0,arguments.length);var a=this.path.parent();return a===l?l:new J(this.u,a)};J.prototype.parent=J.prototype.parent;
J.prototype.root=function(){A("Firebase.ref",0,0,arguments.length);for(var a=this;a.parent()!==l;)a=a.parent();return a};J.prototype.root=J.prototype.root;J.prototype.toString=function(){A("Firebase.toString",0,0,arguments.length);var a;if(this.parent()===l)a=this.u.toString();else{a=this.parent().toString()+"/";var b=this.name();a+=encodeURIComponent(String(b))}return a};J.prototype.toString=J.prototype.toString;
J.prototype.set=function(a,b){A("Firebase.set",1,2,arguments.length);E("Firebase.set",this.path);xa("Firebase.set",a,o);C("Firebase.set",2,b,k);return this.u.Xa(this.path,a,l,b)};J.prototype.set=J.prototype.set;J.prototype.update=function(a,b){A("Firebase.update",1,2,arguments.length);E("Firebase.update",this.path);Ba("Firebase.update",a);C("Firebase.update",2,b,k);return this.u.update(this.path,a,b)};J.prototype.update=J.prototype.update;
J.prototype.Xa=function(a,b,c){A("Firebase.setWithPriority",2,3,arguments.length);E("Firebase.setWithPriority",this.path);xa("Firebase.setWithPriority",a,o);Ca("Firebase.setWithPriority",2,b,o);C("Firebase.setWithPriority",3,c,k);(".length"===this.name()||".keys"===this.name())&&g("Firebase.setWithPriority failed: "+this.name()+" is a read-only object.");return this.u.Xa(this.path,a,b,c)};J.prototype.setWithPriority=J.prototype.Xa;
J.prototype.remove=function(a){A("Firebase.remove",0,1,arguments.length);E("Firebase.remove",this.path);C("Firebase.remove",1,a,k);this.set(l,a)};J.prototype.remove=J.prototype.remove;
J.prototype.transaction=function(a,b,c){function d(){}A("Firebase.transaction",1,3,arguments.length);E("Firebase.transaction",this.path);C("Firebase.transaction",1,a,o);C("Firebase.transaction",2,b,k);u(c)&&"boolean"!=typeof c&&g(Error(B("Firebase.transaction",3,k)+"must be a boolean."));(".length"===this.name()||".keys"===this.name())&&g("Firebase.transaction failed: "+this.name()+" is a read-only object.");"undefined"===typeof c&&(c=k);var e=this.u,f=this.path,h=c;e.e("transaction on "+f);var i=
new J(e,f);i.vc("value",d);var h={path:f,update:a,C:b,status:l,$c:Fb(),hc:h,fd:0,ec:function(){i.Lb("value",d)},fc:l},m=h.update(V(e.Za,f).T());if(u(m)){ya("transaction failed: Data returned ",m);h.status=1;var n=L(e.Ya,f),p=n.k()||[];p.push(h);M(n,p);n="object"===typeof m&&D(m,".priority")?m[".priority"]:V(e.g.I,f).j();W(e.Za,f,S(m,n));h.hc&&(W(e.g.ta,f,S(m,n)),Bd(e.M,f,[f]));Qd(e)}else h.ec(),h.C&&(e=Td(e,f),h.C(l,o,e))};J.prototype.transaction=J.prototype.transaction;
J.prototype.Gc=function(a,b){A("Firebase.setPriority",1,2,arguments.length);E("Firebase.setPriority",this.path);Ca("Firebase.setPriority",1,a,o);C("Firebase.setPriority",2,b,k);this.u.Gc(this.path,a,b)};J.prototype.setPriority=J.prototype.Gc;J.prototype.push=function(a,b){A("Firebase.push",0,2,arguments.length);E("Firebase.push",this.path);xa("Firebase.push",a,k);C("Firebase.push",2,b,k);var c=Jd(this.u),c=Xd(c),c=this.F(c);"undefined"!==typeof a&&a!==l&&c.set(a,b);return c};J.prototype.push=J.prototype.push;
J.prototype.fa=function(){return new $(this.u,this.path,this.name())};J.prototype.onDisconnect=J.prototype.fa;J.prototype.Fd=function(){Pb("FirebaseRef.removeOnDisconnect() being deprecated. Please use FirebaseRef.onDisconnect().remove() instead.");this.fa().remove();Pd(this.u)};J.prototype.removeOnDisconnect=J.prototype.Fd;J.prototype.Jd=function(a){Pb("FirebaseRef.setOnDisconnect(value) being deprecated. Please use FirebaseRef.onDisconnect().set(value) instead.");this.fa().set(a);Pd(this.u)};
J.prototype.setOnDisconnect=J.prototype.Jd;J.prototype.ab=function(a,b,c){A("Firebase.auth",1,3,arguments.length);v(a)||g(Error(B("Firebase.auth",1,o)+"must be a valid credential (a string)."));C("Firebase.auth",2,b,k);C("Firebase.auth",3,b,k);this.u.ab(a,b,c)};J.prototype.auth=J.prototype.ab;J.prototype.Db=function(){this.u.Db()};J.prototype.unauth=J.prototype.Db;
function Lb(a,b){z(!b||a===k||a===o,"Can't turn on custom loggers persistently.");a===k?("undefined"!==typeof console&&("function"===typeof console.log?Jb=w(console.log,console):"object"===typeof console.log&&(Jb=function(a){console.log(a)})),b&&mb.setItem("logging_enabled","true")):a?Jb=a:(Jb=l,mb.removeItem("logging_enabled"))}J.enableLogging=Lb;J.ServerValue={TIMESTAMP:{".sv":"timestamp"}};J.INTERNAL=Z;J.Context=Y;})();