- name: Amazon AWS
  image: logo_aws.svg
  width: 140
  height: 54
  code:
- name: Digital Ocean
  image: logo_digitalocean.svg
  width: 100
  height: 75
  code:
- name: Openstack
  image: logo_openstack.svg
  width: 155
  height: 29
  code: "aws_instances:	&#10;
         &nbsp;'App':&#10;
         &nbsp;&nbsp;instance_type: 'micro'&#10;
         &nbsp;&nbsp;ami: ''&#10;
         &nbsp;&nbsp;exec:&#10;
         &nbsp;&nbsp;&nbsp;apt-get install ruby mysql&#10;
         &nbsp;&nbsp;&nbsp;git clone git@github.com/koding/project.git&#10;
         &nbsp;&nbsp;&nbsp;chef-solo -c solo.rb -j web.json"
- name: Vagrant
  image: logo_vagrant.svg
  width: 180
  height: 46
  code:
- name: Microsoft Azure
  image: logo_azure.svg
  width: 190
  height: 27
  active: true
  code: "aws_instances:	&#10;
        &nbsp;'App':&#10;
        &nbsp;&nbsp;instance_type: 'micro'&#10;
        &nbsp;&nbsp;ami: ''&#10;
        &nbsp;&nbsp;exec:&#10;
        &nbsp;&nbsp;&nbsp;apt-get install ruby mysql&#10;
        &nbsp;&nbsp;&nbsp;git clone git@github.com/koding/project.git&#10;
        &nbsp;&nbsp;&nbsp;chef-solo -c solo.rb -j web.json"
- name: Google Cloud Platform
  image: logo_gcp.svg
  width: 300
  height: 33
  code:
- name: Docker
  image: logo_docker.svg
  width: 180
  height: 43
  code:
- name: Softlayer
  image: logo_softlayer.svg
  width: 180
  height: 15
  code:
- name: Mesospere
  image: logo_mesos.svg
  width: 240
  height: 43
  code: