language: go
sudo: false
go:
         - 1.4
         - 1.5
         - tip

install: go get -v ./hipchat
script:
    - go get -u github.com/golang/lint/golint
    - golint ./...
    - test `gofmt -l . | wc -l` = 0
    - make all

matrix:
    allow_failures:
        - go: tip
