package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
)

// JGroupData j group data
// swagger:model JGroupData
type JGroupData struct {

	// id
	ID string `json:"_id,omitempty"`

	// data
	Data interface{} `json:"data,omitempty"`

	// slug
	Slug string `json:"slug,omitempty"`
}

// Validate validates this j group data
func (m *JGroupData) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
