processes = new (require "processes")

option '-c', '--config [CONFIG]', 'Which config to use'
option '-s', '--silent', 'Set this flag to suppress stdout'

task 'run', ({config, silent}) ->
  KONFIG = require('koding-config-manager').load("main.#{config}")
  {webserver} = KONFIG

  if webserver
    webPort = webserver.port
    webPort = [webPort] unless Array.isArray webPort
    webPort.forEach (port) ->
      runServer config, port, silent

runServer = (config, port, silent) ->
  process.stdout.setMaxListeners 0
  process.stderr.setMaxListeners 0
  processes.fork
    name          : 'server' + port
    cmd           : "./index.js -c #{config} -p #{port}"
    restart : yes
    restartInterval : 100