fs        = require 'fs'
nodePath  = require 'path'
{spawn}   = require 'child_process'
mongodb   = require 'mongoskin'
KodingLogger = require 'koding-logger'

option '-c', '--configPath [CONFIG]', 'Which config file to use'

task 'run', ({configPath, noisy})->
  configPath ?= '../config/dev'
  {webPort, logger} = require configPath
  logger = new KodingLogger 'Koding WebServer', logger, noisy
  webPort = [webPort] unless Array.isArray webPort
  webPort.forEach (port)->
    runServer configPath, logger, port

runServer =(configPath, logger, port)->
  child = spawn 'node', [
    'index.js'
    '-c', configPath
    '-p', port
  ]
  logger.logAll child, {port}

shouldRestart =(port)-> yes
