fs        = require 'fs'
os        = require 'os'
nodePath  = require 'path'
{spawn}   = require 'child_process'
KodingLogger = require 'koding-logger'
processes   = new (require "processes")
httpProxy = require("http-proxy")

option '-c', '--configPath [CONFIG]', 'Which config file to use'
option '-s', '--silent', 'Set this flag to suppress stdout'

task 'run', ({configPath, silent})->
  configPath ?= '../config/dev'
  {webserver, logger,loadBalancer} = require configPath

  if webserver
    webPort = webserver.port
    webPort = [webPort] unless Array.isArray webPort
    webPort.forEach (port)->
      runServer configPath, logger, port,silent

  if loadBalancer
    runLoadBalancer configPath,logger,silent

runLoadBalancer = (configPath,logger,silent)->
  configPath ?= '../config/dev'
  # loggerLB = new KodingLogger 'load-balancer', os.hostname(), logger.mq
  # loggerLB.tailTo process.stdout unless silent
  
  lb = processes.run
    name        : 'load-balancer'
    modulePath  : "./load-balancer"
    args        : ["-c #{configPath}"]
    restart     : yes
    restartInterval : 1
    stdout  : process.stdout
    stderr  : process.stderr
    verbose : no
    # onMessage : (msg)->
    #   console.log msg.name,msg.mem.rss,msg.mem.heapTotal,msg.mem.heapUsed

  # loggerLB.logAll processes.get("load-balancer"), "load-balancer"



runServer =(configPath, logger, port,silent)->
  #loggerWS = new KodingLogger 'webserver', os.hostname(), logger.mq
  #loggerWS.tailTo process.stdout unless silent
  process.stdout.setMaxListeners 0
  process.stderr.setMaxListeners 0  
  processes.run
    name          : 'server'+port
    modulePath    : "./index.js"
    args          : ["-c #{configPath}","-p #{port}"]
    opts : silent : yes
    restart : yes
    restartInterval : 1
    verbose : yes
    # die : 
    #   interval : 60*1000
    # monitor : 
    #   interval : 1000
    onMessage : (msg)->
      if msg.mem.rss > 300
        processes.sendMessage 'load-balancer',{markAsDead:yes,port:port}
        console.log "[WEBSERVER #{port}] high memory usage - time to commit suicide."
        processes.kill 'server'+port
      # console.log msg.name,msg.mem.rss,msg.mem.heapTotal,msg.mem.heapUsed

  console.log "im the child of server:"+processes.get("server"+port).pid

# runServer =(configPath, logger, port,silent)->
#   #loggerWS = new KodingLogger 'webserver', os.hostname(), logger.mq
#   #loggerWS.tailTo process.stdout unless silent

#   processes.run
#     name    : 'server'+port
#     cmd     : "node ./index.js -c #{configPath} -p #{port}"
#     restart : no
#     restartInterval : 1
#     stdout  : process.stdout
#     stderr  : process.stderr
#     verbose : yes
#     die : 60*1000*Math.random() 

#   console.log "im the child of server:"+processes.get("server"+port).pid
  # loggerWS.logAll processes.get("server"+port), "webserver#{port}"
  # setTimeout (-> process.exit()),5000



shouldRestart =(port)-> yes
