package j_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJTagUnfollowIDReader is a Reader for the PostRemoteAPIJTagUnfollowID structure.
type PostRemoteAPIJTagUnfollowIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJTagUnfollowIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJTagUnfollowIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJTagUnfollowIDOK creates a PostRemoteAPIJTagUnfollowIDOK with default headers values
func NewPostRemoteAPIJTagUnfollowIDOK() *PostRemoteAPIJTagUnfollowIDOK {
	return &PostRemoteAPIJTagUnfollowIDOK{}
}

/*PostRemoteAPIJTagUnfollowIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJTagUnfollowIDOK struct {
	Payload PostRemoteAPIJTagUnfollowIDOKBody
}

func (o *PostRemoteAPIJTagUnfollowIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JTag.unfollow/{id}][%d] postRemoteApiJTagUnfollowIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJTagUnfollowIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJTagUnfollowIDOKBody post remote API j tag unfollow ID o k body
swagger:model PostRemoteAPIJTagUnfollowIDOKBody
*/
type PostRemoteAPIJTagUnfollowIDOKBody struct {
	models.JTag

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJTagUnfollowIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJTagUnfollowIDOKBodyAO0 models.JTag
	if err := swag.ReadJSON(raw, &postRemoteAPIJTagUnfollowIDOKBodyAO0); err != nil {
		return err
	}
	o.JTag = postRemoteAPIJTagUnfollowIDOKBodyAO0

	var postRemoteAPIJTagUnfollowIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJTagUnfollowIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJTagUnfollowIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJTagUnfollowIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJTagUnfollowIDOKBodyAO0, err := swag.WriteJSON(o.JTag)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJTagUnfollowIDOKBodyAO0)

	postRemoteAPIJTagUnfollowIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJTagUnfollowIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j tag unfollow ID o k body
func (o *PostRemoteAPIJTagUnfollowIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JTag.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
