package j_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJTagFetchContentsIDReader is a Reader for the PostRemoteAPIJTagFetchContentsID structure.
type PostRemoteAPIJTagFetchContentsIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJTagFetchContentsIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJTagFetchContentsIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJTagFetchContentsIDOK creates a PostRemoteAPIJTagFetchContentsIDOK with default headers values
func NewPostRemoteAPIJTagFetchContentsIDOK() *PostRemoteAPIJTagFetchContentsIDOK {
	return &PostRemoteAPIJTagFetchContentsIDOK{}
}

/*PostRemoteAPIJTagFetchContentsIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJTagFetchContentsIDOK struct {
	Payload PostRemoteAPIJTagFetchContentsIDOKBody
}

func (o *PostRemoteAPIJTagFetchContentsIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JTag.fetchContents/{id}][%d] postRemoteApiJTagFetchContentsIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJTagFetchContentsIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJTagFetchContentsIDOKBody post remote API j tag fetch contents ID o k body
swagger:model PostRemoteAPIJTagFetchContentsIDOKBody
*/
type PostRemoteAPIJTagFetchContentsIDOKBody struct {
	models.JTag

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJTagFetchContentsIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJTagFetchContentsIDOKBodyAO0 models.JTag
	if err := swag.ReadJSON(raw, &postRemoteAPIJTagFetchContentsIDOKBodyAO0); err != nil {
		return err
	}
	o.JTag = postRemoteAPIJTagFetchContentsIDOKBodyAO0

	var postRemoteAPIJTagFetchContentsIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJTagFetchContentsIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJTagFetchContentsIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJTagFetchContentsIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJTagFetchContentsIDOKBodyAO0, err := swag.WriteJSON(o.JTag)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJTagFetchContentsIDOKBodyAO0)

	postRemoteAPIJTagFetchContentsIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJTagFetchContentsIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j tag fetch contents ID o k body
func (o *PostRemoteAPIJTagFetchContentsIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JTag.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
