package j_tag

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJTagFetchFollowingWithRelationshipIDReader is a Reader for the PostRemoteAPIJTagFetchFollowingWithRelationshipID structure.
type PostRemoteAPIJTagFetchFollowingWithRelationshipIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJTagFetchFollowingWithRelationshipIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJTagFetchFollowingWithRelationshipIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJTagFetchFollowingWithRelationshipIDOK creates a PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK with default headers values
func NewPostRemoteAPIJTagFetchFollowingWithRelationshipIDOK() *PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK {
	return &PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK{}
}

/*PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK struct {
	Payload *models.JTag
}

func (o *PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JTag.fetchFollowingWithRelationship/{id}][%d] postRemoteApiJTagFetchFollowingWithRelationshipIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJTagFetchFollowingWithRelationshipIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.JTag)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
