package tracker

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewTrackerTrackParams creates a new TrackerTrackParams object
// with the default values initialized.
func NewTrackerTrackParams() *TrackerTrackParams {
	var ()
	return &TrackerTrackParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewTrackerTrackParamsWithTimeout creates a new TrackerTrackParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewTrackerTrackParamsWithTimeout(timeout time.Duration) *TrackerTrackParams {
	var ()
	return &TrackerTrackParams{

		timeout: timeout,
	}
}

// NewTrackerTrackParamsWithContext creates a new TrackerTrackParams object
// with the default values initialized, and the ability to set a context for a request
func NewTrackerTrackParamsWithContext(ctx context.Context) *TrackerTrackParams {
	var ()
	return &TrackerTrackParams{

		Context: ctx,
	}
}

/*TrackerTrackParams contains all the parameters to send to the API endpoint
for the tracker track operation typically these are written to a http.Request
*/
type TrackerTrackParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the tracker track params
func (o *TrackerTrackParams) WithTimeout(timeout time.Duration) *TrackerTrackParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the tracker track params
func (o *TrackerTrackParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the tracker track params
func (o *TrackerTrackParams) WithContext(ctx context.Context) *TrackerTrackParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the tracker track params
func (o *TrackerTrackParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the tracker track params
func (o *TrackerTrackParams) WithBody(body models.DefaultSelector) *TrackerTrackParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the tracker track params
func (o *TrackerTrackParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *TrackerTrackParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
