module.exports = {

  'ADD_PARTICIPANT_TO_NEW_CHANNEL'
  'REMOVE_PARTICIPANT_FROM_NEW_CHANNEL'
  'REMOVE_ALL_PARTICIPANTS_FROM_NEW_CHANNEL'
  'SET_CREATE_NEW_CHANNEL_PARTICIPANTS_QUERY'
  'UNSET_CREATE_NEW_CHANNEL_PARTICIPANTS_QUERY'
  'RESET_CREATE_NEW_CHANNEL_PARTICIPANTS_SELECTED_INDEX'
  'SET_CREATE_NEW_CHANNEL_PARTICIPANTS_SELECTED_INDEX'
  'MOVE_TO_NEXT_CREATE_NEW_CHANNEL_PARTICIPANT_INDEX'
  'MOVE_TO_PREV_CREATE_NEW_CHANNEL_PARTICIPANT_INDEX'
  'SET_CREATE_NEW_CHANNEL_PARTICIPANTS_DROPDOWN_VISIBILITY'
  'CREATE_PUBLIC_CHANNEL'
  'CREATE_PUBLIC_CHANNEL_FAIL'
  'CREATE_PUBLIC_CHANNEL_SUCCESS'
  'CREATE_PRIVATE_CHANNEL'
  'CREATE_PRIVATE_CHANNEL_FAIL'
  'CREATE_PRIVATE_CHANNEL_SUCCESS'

}
