module.exports = {
  'LOAD_MESSAGES_BEGIN'
  'LOAD_MESSAGES_FAIL'
  'LOAD_MESSAGES_SUCCESS'

  'SET_ALL_MESSAGES_LOADED'
  'UNSET_ALL_MESSAGES_LOADED'

  'LOAD_MESSAGE_BEGIN'
  'LOAD_MESSAGE_FAIL'
  'LOAD_MESSAGE_SUCCESS'

  'LOAD_MESSAGE_BY_SLUG_BEGIN'
  'LOAD_MESSAGE_BY_SLUG_FAIL'

  'ACTIVATE_LOADER_MARKER'
  'DEACTIVATE_LOADER_MARKER'

  'CREATE_MESSAGE_BEGIN'
  'CREATE_MESSAGE_SUCCESS'
  'CREATE_MESSAGE_FAIL'

  'EDIT_MESSAGE_BEGIN'
  'EDIT_MESSAGE_SUCCESS'
  'EDIT_MESSAGE_FAIL'

  'EDIT_MESSAGE_EMBED_PAYLOAD_BEGIN'
  'EDIT_MESSAGE_EMBED_PAYLOAD_SUCCESS'
  'EDIT_MESSAGE_EMBED_PAYLOAD_FAIL'
  'DISABLE_EDITED_MESSAGE_EMBED_PAYLOAD'

  'SET_MESSAGE_EDIT_MODE'
  'UNSET_MESSAGE_EDIT_MODE'

  'REMOVE_MESSAGE_BEGIN'
  'REMOVE_MESSAGE_SUCCESS'
  'REMOVE_MESSAGE_FAIL'

  'LIKE_MESSAGE_BEGIN'
  'LIKE_MESSAGE_SUCCESS'
  'LIKE_MESSAGE_FAIL'

  'UNLIKE_MESSAGE_BEGIN'
  'UNLIKE_MESSAGE_SUCCESS'
  'UNLIKE_MESSAGE_FAIL'

  'LOAD_COMMENTS_BEGIN'
  'LOAD_COMMENTS_FAIL'
  'LOAD_COMMENTS_SUCCESS'
  'LOAD_COMMENT_SUCCESS'

  'CREATE_COMMENT_BEGIN'
  'CREATE_COMMENT_SUCCESS'
  'CREATE_COMMENT_FAIL'

  'LOAD_CHANNEL_PARTICIPANTS_BEGIN'
  'LOAD_CHANNEL_PARTICIPANTS_FAIL'
  'LOAD_CHANNEL_PARTICIPANT_SUCCESS'
  'REMOVE_PARTICIPANT_FROM_CHANNEL'

  'LOAD_POPULAR_MESSAGES_BEGIN'
  'LOAD_POPULAR_MESSAGES_FAIL'
  'LOAD_POPULAR_MESSAGE_SUCCESS'

  'LOAD_CHANNEL_BY_NAME_BEGIN'
  'LOAD_CHANNEL_BY_NAME_FAIL'
  'LOAD_CHANNEL_BY_ID_BEGIN'
  'LOAD_CHANNEL_BY_ID_FAIL'
  'LOAD_CHANNEL_BY_PARTICIPANTS_BEGIN'
  'LOAD_CHANNEL_BY_NAME_FAIL'

  'LOAD_CHANNEL_BEGIN'
  'LOAD_CHANNEL_FAIL'
  'LOAD_CHANNEL_SUCCESS'

  'LOAD_FOLLOWED_PRIVATE_CHANNELS_BEGIN'
  'LOAD_FOLLOWED_PRIVATE_CHANNELS_FAIL'

  'LOAD_FOLLOWED_PRIVATE_CHANNEL_SUCCESS'

  'LOAD_FOLLOWED_PUBLIC_CHANNELS_BEGIN'
  'LOAD_FOLLOWED_PUBLIC_CHANNELS_FAIL'

  'LOAD_FOLLOWED_PUBLIC_CHANNEL_SUCCESS'

  'SET_SELECTED_CHANNEL_THREAD'
  'SET_SELECTED_CHANNEL_THREAD_FAIL'

  'SET_SELECTED_MESSAGE_THREAD'
  'SET_SELECTED_MESSAGE_THREAD_FAIL'

  'LOAD_POPULAR_CHANNELS_BEGIN'
  'LOAD_POPULAR_CHANNELS_SUCCESS'
  'LOAD_POPULAR_CHANNELS_FAIL'

  'LOAD_CHANNELS_BEGIN'
  'LOAD_CHANNELS_SUCCESS'
  'LOAD_CHANNELS_FAIL'

  'FOLLOW_CHANNEL_BEGIN'
  'FOLLOW_CHANNEL_SUCCESS'
  'FOLLOW_CHANNEL_FAIL'

  'UNFOLLOW_CHANNEL_BEGIN'
  'UNFOLLOW_CHANNEL_SUCCESS'
  'UNFOLLOW_CHANNEL_FAIL'

  'DELETE_PRIVATE_CHANNEL_BEGIN'
  'DELETE_PRIVATE_CHANNEL_SUCCESS'
  'DELETE_PRIVATE_CHANNEL_FAIL'

  'LEAVE_PRIVATE_CHANNEL_BEGIN'
  'LEAVE_PRIVATE_CHANNEL_SUCCESS'
  'LEAVE_PRIVATE_CHANNEL_FAIL'

  'SET_CHANNEL_UNREAD_COUNT'

  'GLANCE_CHANNEL_BEGIN'
  'GLANCE_CHANNEL_SUCCESS'

  'SET_SUGGESTIONS_QUERY'
  'SET_SUGGESTIONS_VISIBILITY'
  'SET_SUGGESTIONS_ACCESSIBILITY'
  'FETCH_SUGGESTIONS_SUCCESS'
  'FETCH_SUGGESTIONS_FAIL'
  'SUGGESTIONS_DATA_RESET'
  'SET_SUGGESTIONS_SELECTED_INDEX'
  'MOVE_TO_NEXT_SUGGESTIONS_INDEX'
  'MOVE_TO_PREV_SUGGESTIONS_INDEX'
  'RESET_SUGGESTIONS_SELECTED_INDEX'

  'SET_CHANNEL_PARTICIPANTS_QUERY'
  'UNSET_CHANNEL_PARTICIPANTS_QUERY'

  'ADD_PARTICIPANTS_TO_CHANNEL_BEGIN'
  'ADD_PARTICIPANTS_TO_CHANNEL_FAIL'
  'ADD_PARTICIPANTS_TO_CHANNEL_SUCCESS'

  'SET_CHANNEL_PARTICIPANTS_DROPDOWN_VISIBILITY'
  'SET_CHANNEL_PARTICIPANTS_SELECTED_INDEX'
  'RESET_CHANNEL_PARTICIPANTS_SELECTED_INDEX'
  'MOVE_TO_NEXT_CHANNEL_PARTICIPANT_INDEX'
  'MOVE_TO_PREV_CHANNEL_PARTICIPANT_INDEX'

  'INVITE_MEMBER_SUCCESS'
  'INVITE_MEMBER_FAIL'

  'SET_SIDEBAR_PUBLIC_CHANNELS_QUERY'
  'SET_SIDEBAR_PUBLIC_CHANNELS_TAB'

  'SET_CHANNEL_SCROLL_POSITION'
  'SET_CHANNEL_LAST_SEEN_TIME'

  'UPDATE_CHANNEL_BEGIN'
  'UPDATE_CHANNEL_FAIL'
  'UPDATE_CHANNEL_SUCCESS'

  'SET_CHANNEL_MESSAGES_SEARCH_QUERY'
  'CHANNEL_MESSAGES_SEARCH_BEGIN'
  'CHANNEL_MESSAGES_SEARCH_FAIL'
  'CHANNEL_MESSAGES_SEARCH_SUCCESS'

  'SET_CHANNEL_RESULT_STATE'

  'SOCIAL_SHARE_LINK_CREATED'
  'SOCIAL_SHARE_LINK_DELETED'
  'SET_ACTIVE_SOCIAL_SHARE_LINK_ID'
}
