module.exports = {
  'LOAD_MESSAGES_BEGIN'
  'LOAD_MESSAGES_FAIL'
  'LOAD_MESSAGE_SUCCESS'

  'CREATE_MESSAGE_BEGIN'
  'CREATE_MESSAGE_SUCCESS'
  'CREATE_MESSAGE_FAIL'

  'REMOVE_MESSAGE_BEGIN'
  'REMOVE_MESSAGE_SUCCESS'
  'REMOVE_MESSAGE_FAIL'

  'LIKE_MESSAGE_BEGIN'
  'LIKE_MESSAGE_SUCCESS'
  'LIKE_MESSAGE_FAIL'

  'UNLIKE_MESSAGE_BEGIN'
  'UNLIKE_MESSAGE_SUCCESS'
  'UNLIKE_MESSAGE_FAIL'

  'LOAD_FOLLOWED_PRIVATE_CHANNELS_BEGIN'
  'LOAD_FOLLOWED_PRIVATE_CHANNELS_FAIL'

  'LOAD_FOLLOWED_PRIVATE_CHANNEL_SUCCESS'

  'LOAD_FOLLOWED_PUBLIC_CHANNELS_BEGIN'
  'LOAD_FOLLOWED_PUBLIC_CHANNELS_FAIL'

  'LOAD_FOLLOWED_PUBLIC_CHANNEL_SUCCESS'

  'SET_SELECTED_CHANNEL_THREAD'

  'SET_SUGGESTIONS_QUERY'
  'SET_SUGGESTIONS_VISIBILITY'
  'SET_SUGGESTIONS_ACCESS'
  'FETCH_SUGGESTIONS_SUCCESS'
  'FETCH_SUGGESTIONS_FAIL'
  'SUGGESTIONS_DATA_RESET'
}

