module.exports = {
  'LOAD_TEAM_BEGIN'
  'LOAD_TEAM_FAIL'
  'LOAD_TEAM_SUCCESS'

  'SET_TEAM_INVITE_INPUT_VALUE'

  'FETCH_TEAM_MEMBERS_BEGIN'
  'FETCH_TEAM_MEMBERS_FAIL'
  'FETCH_TEAM_MEMBERS_SUCCESS'

  'FETCH_TEAM_MEMBERS_ROLES_BEGIN'
  'FETCH_TEAM_MEMBERS_ROLES_FAIL'
  'FETCH_TEAM_MEMBERS_ROLES_SUCCESS'

  'GET_INVITE_INPUTS'
  'SET_SEARCH_INPUT_VALUE'
  'RESET_TEAM_INVITES'
  'UPDATE_TEAM_MEMBER'
  'DELETE_TEAM_MEMBER'

  'LOAD_PENDING_INVITATION_BEGIN'
  'LOAD_PENDING_INVITATION_SUCCESS'
  'LOAD_PENDING_INVITATION_FAIL'
}
