module.exports = {
  'LOAD_TEAM_BEGIN'
  'LOAD_TEAM_FAIL'
  'LOAD_TEAM_SUCCESS'

  'UPDATE_TEAM_SUCCESS'

  'SET_TEAM_INVITE_INPUT_VALUE'

  'LOAD_TEAM_MEMBERS_BEGIN'
  'LOAD_TEAM_MEMBERS_FAIL'
  'LOAD_TEAM_MEMBERS_SUCCESS'

  'FETCH_TEAM_MEMBERS_ROLES_BEGIN'
  'FETCH_TEAM_MEMBERS_ROLES_FAIL'
  'FETCH_TEAM_MEMBERS_ROLES_SUCCESS'

  'GET_INVITE_INPUTS'
  'SET_SEARCH_INPUT_VALUE'
  'RESET_TEAM_INVITES'
  'UPDATE_TEAM_MEMBER'
  'UPDATE_TEAM_MEMBER_WITH_ID'
  'DELETE_TEAM_MEMBER'
  'SAVE_DISABLED_TEAM_MEMBER'
  'LOAD_DISABLED_MEMBERS'
  'REMOVE_ENABLED_MEMBER'
  'ADD_MEMBER_TO_TEAM'

  'LOAD_PENDING_INVITATION_BEGIN'
  'LOAD_PENDING_INVITATION_SUCCESS'
  'LOAD_PENDING_INVITATION_FAIL'
  'REMOVE_PENDING_INVITATION'
  'REMOVE_PENDING_INVITATION_BY_ID'

  'DELETE_PENDING_INVITATION_BEGIN'
  'DELETE_PENDING_INVITATION_SUCCESS'
  'DELETE_PENDING_INVITATION_FAIL'

  'ALL_USERS_LOADED'

  'FOCUS_SEND_INVITES_SECTION'

  'FETCH_API_TOKENS_SUCCESS'
  'DELETE_API_TOKEN_SUCCESS'
  'ADD_API_TOKEN_SUCCESS'
  'SET_API_ACCESS_STATE'
  'LOAD_OTA_TOKEN_SUCCESS'
}
