# Applications Kite

option '-c', '--config [CONFIG]', 'select a config file (default is prod)'

processes = new(require 'processes')
https = require 'https'

task 'run','run applications',(options)->

  options.config ?= "config-dev"

  processes.run
    name    : "applications"
    cmd     : "coffee index.coffee -c #{options.config} --applications"
    restart : yes
    stdout  : process.stdout
    stderr  : process.stderr
    onExit  : (pid,name)->
      if options.config is "config-prod"
        https.get e = "https://koding.com/-/status/processIsDead/#{name}"
    
