option '-c', '--config', 'select a config file (default is prod)'


processes = require 'processes'
        

task "install", 'install packages',(options)->
  processes.run
    cmd : "npm i ldapjs@0.4.8"
    log : yes

task "build",'builds sharedhosting client',(options)->
  console.log "run npm i ldapjs@0.4.8"


task 'run','run sharedHosting',(options)->

  options.config ?= "config-dev"
  
  processes.run 
    cmd     : "coffee index.coffee -c #{options.config} --sharedHosting"
    log     : yes       # or provide a path for log file
    restart : no        # or provide a function 


  
