require '../../app/test'
require '../../activity/lib/test'
require '../../ide/test'
require '../../account/lib/test'
require '../../admin/lib/test'
require '../../app/lib/providers/test'
require '../../home/lib/virtualmachines/test/generictoggler.test'
require '../../home/lib/virtualmachines/test/machinedetails.test'