option '-c', '--config [CONFIG]', 'select a config file (default is prod)'


processes = new(require 'processes')


task "install", 'install packages',(options)->
  processes.run
    cmd : "npm i ldapjs@0.4.8"
    log : yes

task "build",'builds sharedhosting client',(options)->
  console.log "run npm i ldapjs@0.4.8"


task 'run','run databases',(options)->

  options.config ?= "config-dev"

  processes.run
    name    : "databases"
    cmd     : "coffee index.coffee -c #{options.config} --databases"
    restart : yes
    stdout  : process.stdout
    stderr  : process.stderr
    onExit  : (pid,name)->
      http.get e = "#{config.uri.address}/status/processIsDead/#{name}"



