package j_stack_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JStackTemplateHasStacksReader is a Reader for the JStackTemplateHasStacks structure.
type JStackTemplateHasStacksReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JStackTemplateHasStacksReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJStackTemplateHasStacksOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJStackTemplateHasStacksOK creates a JStackTemplateHasStacksOK with default headers values
func NewJStackTemplateHasStacksOK() *JStackTemplateHasStacksOK {
	return &JStackTemplateHasStacksOK{}
}

/*JStackTemplateHasStacksOK handles this case with default header values.

OK
*/
type JStackTemplateHasStacksOK struct {
	Payload JStackTemplateHasStacksOKBody
}

func (o *JStackTemplateHasStacksOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JStackTemplate.hasStacks/{id}][%d] jStackTemplateHasStacksOK  %+v", 200, o.Payload)
}

func (o *JStackTemplateHasStacksOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JStackTemplateHasStacksOKBody j stack template has stacks o k body
swagger:model JStackTemplateHasStacksOKBody
*/
type JStackTemplateHasStacksOKBody struct {
	models.JStackTemplate

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *JStackTemplateHasStacksOKBody) UnmarshalJSON(raw []byte) error {

	var jStackTemplateHasStacksOKBodyAO0 models.JStackTemplate
	if err := swag.ReadJSON(raw, &jStackTemplateHasStacksOKBodyAO0); err != nil {
		return err
	}
	o.JStackTemplate = jStackTemplateHasStacksOKBodyAO0

	var jStackTemplateHasStacksOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &jStackTemplateHasStacksOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = jStackTemplateHasStacksOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o JStackTemplateHasStacksOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	jStackTemplateHasStacksOKBodyAO0, err := swag.WriteJSON(o.JStackTemplate)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jStackTemplateHasStacksOKBodyAO0)

	jStackTemplateHasStacksOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jStackTemplateHasStacksOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this j stack template has stacks o k body
func (o *JStackTemplateHasStacksOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JStackTemplate.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
