package j_stack_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJStackTemplateVerifyIDReader is a Reader for the PostRemoteAPIJStackTemplateVerifyID structure.
type PostRemoteAPIJStackTemplateVerifyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJStackTemplateVerifyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJStackTemplateVerifyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJStackTemplateVerifyIDOK creates a PostRemoteAPIJStackTemplateVerifyIDOK with default headers values
func NewPostRemoteAPIJStackTemplateVerifyIDOK() *PostRemoteAPIJStackTemplateVerifyIDOK {
	return &PostRemoteAPIJStackTemplateVerifyIDOK{}
}

/*PostRemoteAPIJStackTemplateVerifyIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJStackTemplateVerifyIDOK struct {
	Payload PostRemoteAPIJStackTemplateVerifyIDOKBody
}

func (o *PostRemoteAPIJStackTemplateVerifyIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JStackTemplate.verify/{id}][%d] postRemoteApiJStackTemplateVerifyIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJStackTemplateVerifyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJStackTemplateVerifyIDOKBody post remote API j stack template verify ID o k body
swagger:model PostRemoteAPIJStackTemplateVerifyIDOKBody
*/
type PostRemoteAPIJStackTemplateVerifyIDOKBody struct {
	models.JStackTemplate

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJStackTemplateVerifyIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJStackTemplateVerifyIDOKBodyAO0 models.JStackTemplate
	if err := swag.ReadJSON(raw, &postRemoteAPIJStackTemplateVerifyIDOKBodyAO0); err != nil {
		return err
	}
	o.JStackTemplate = postRemoteAPIJStackTemplateVerifyIDOKBodyAO0

	var postRemoteAPIJStackTemplateVerifyIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJStackTemplateVerifyIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJStackTemplateVerifyIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJStackTemplateVerifyIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJStackTemplateVerifyIDOKBodyAO0, err := swag.WriteJSON(o.JStackTemplate)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJStackTemplateVerifyIDOKBodyAO0)

	postRemoteAPIJStackTemplateVerifyIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJStackTemplateVerifyIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j stack template verify ID o k body
func (o *PostRemoteAPIJStackTemplateVerifyIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JStackTemplate.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
