package j_stack_template

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRemoteAPIJStackTemplateUpdateIDParams creates a new PostRemoteAPIJStackTemplateUpdateIDParams object
// with the default values initialized.
func NewPostRemoteAPIJStackTemplateUpdateIDParams() *PostRemoteAPIJStackTemplateUpdateIDParams {
	var ()
	return &PostRemoteAPIJStackTemplateUpdateIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJStackTemplateUpdateIDParamsWithTimeout creates a new PostRemoteAPIJStackTemplateUpdateIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJStackTemplateUpdateIDParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJStackTemplateUpdateIDParams {
	var ()
	return &PostRemoteAPIJStackTemplateUpdateIDParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJStackTemplateUpdateIDParamsWithContext creates a new PostRemoteAPIJStackTemplateUpdateIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJStackTemplateUpdateIDParamsWithContext(ctx context.Context) *PostRemoteAPIJStackTemplateUpdateIDParams {
	var ()
	return &PostRemoteAPIJStackTemplateUpdateIDParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJStackTemplateUpdateIDParams contains all the parameters to send to the API endpoint
for the post remote API j stack template update ID operation typically these are written to a http.Request
*/
type PostRemoteAPIJStackTemplateUpdateIDParams struct {

	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJStackTemplateUpdateIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) WithContext(ctx context.Context) *PostRemoteAPIJStackTemplateUpdateIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) WithID(id string) *PostRemoteAPIJStackTemplateUpdateIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post remote API j stack template update ID params
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJStackTemplateUpdateIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
