package j_invitation

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJInvitationAcceptIDReader is a Reader for the PostRemoteAPIJInvitationAcceptID structure.
type PostRemoteAPIJInvitationAcceptIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJInvitationAcceptIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJInvitationAcceptIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJInvitationAcceptIDOK creates a PostRemoteAPIJInvitationAcceptIDOK with default headers values
func NewPostRemoteAPIJInvitationAcceptIDOK() *PostRemoteAPIJInvitationAcceptIDOK {
	return &PostRemoteAPIJInvitationAcceptIDOK{}
}

/*PostRemoteAPIJInvitationAcceptIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJInvitationAcceptIDOK struct {
	Payload PostRemoteAPIJInvitationAcceptIDOKBody
}

func (o *PostRemoteAPIJInvitationAcceptIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JInvitation.accept/{id}][%d] postRemoteApiJInvitationAcceptIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJInvitationAcceptIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJInvitationAcceptIDOKBody post remote API j invitation accept ID o k body
swagger:model PostRemoteAPIJInvitationAcceptIDOKBody
*/
type PostRemoteAPIJInvitationAcceptIDOKBody struct {
	models.JInvitation

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJInvitationAcceptIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJInvitationAcceptIDOKBodyAO0 models.JInvitation
	if err := swag.ReadJSON(raw, &postRemoteAPIJInvitationAcceptIDOKBodyAO0); err != nil {
		return err
	}
	o.JInvitation = postRemoteAPIJInvitationAcceptIDOKBodyAO0

	var postRemoteAPIJInvitationAcceptIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJInvitationAcceptIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJInvitationAcceptIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJInvitationAcceptIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJInvitationAcceptIDOKBodyAO0, err := swag.WriteJSON(o.JInvitation)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJInvitationAcceptIDOKBodyAO0)

	postRemoteAPIJInvitationAcceptIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJInvitationAcceptIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j invitation accept ID o k body
func (o *PostRemoteAPIJInvitationAcceptIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JInvitation.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
