package digitalocean

import (
	"errors"
	"fmt"
	"koding/kites/kloud/eventer"
	"koding/kites/kloud/kloud/machinestate"
	"koding/kites/kloud/kloud/protocol"
	"koding/kites/kloud/sshutil"
	"net/url"

	klientprotocol "koding/kites/klient/protocol"

	kiteprotocol "github.com/koding/kite/protocol"
	"github.com/mitchellh/mapstructure"
	"github.com/mitchellh/packer/builder/digitalocean"
)

// Prepare prepares the state for upcoming methods like Build/etc.. It's needs to
// be called before every other method call once. Raws contains the credentials
// as a map[string]interface{} format.
func (d *DigitalOcean) Prepare(raws ...interface{}) (err error) {
	if len(raws) != 2 {
		return errors.New("need at least two arguments")
	}

	// Credentials
	if err := mapstructure.Decode(raws[0], &d.Creds); err != nil {
		return err
	}

	// Builder data
	if err := mapstructure.Decode(raws[1], &d.Builder); err != nil {
		return err
	}

	if d.Creds.ClientID == "" {
		return errors.New("credentials client_id is empty")
	}

	if d.Creds.APIKey == "" {
		return errors.New("credentials api_key is empty")
	}

	d.Builder.ClientID = d.Creds.ClientID
	d.Builder.APIKey = d.Creds.APIKey

	d.Client = digitalocean.DigitalOceanClient{}.New(d.Creds.ClientID, d.Creds.APIKey)

	// authenticate credentials with a simple call
	// TODO: cache gor a given clientID and apiKey
	d.Log.Debug("Testing authentication with a simple /regions call")
	_, err = d.Regions()
	if err != nil {
		return errors.New("authentication with DigitalOcean failed.")
	}

	return nil
}

// Build is building an image and creates a droplet based on that image. If the
// given snapshot/image exist it directly skips to creating the droplet. It
// acceps two string arguments, first one is the snapshotname, second one is
// the dropletName.
func (d *DigitalOcean) Build(opts *protocol.MachineOptions) (p *protocol.BuildResponse, err error) {
	if opts.ImageName == "" {
		return nil, errors.New("snapshotName is empty")
	}
	snapshotName := opts.ImageName

	if opts.InstanceName == "" {
		return nil, errors.New("dropletName is empty")
	}
	dropletName := opts.InstanceName

	if opts.Username == "" {
		return nil, errors.New("username is empty")
	}

	if opts.Eventer == nil {
		return nil, errors.New("Eventer is not defined.")
	}

	d.setPusher(opts, machinestate.Building)

	// needed because this is passed as `data` to packer.Provider
	d.Builder.SnapshotName = snapshotName

	var image digitalocean.Image

	// check if snapshot image does exist, if not create a new one.
	d.Push(fmt.Sprintf("Fetching image %s", snapshotName), 10)
	image, err = d.Image(snapshotName)
	if err != nil {
		d.Push(fmt.Sprintf("Image %s does not exist, creating a new one", snapshotName), 12)
		image, err = d.CreateImage()
		if err != nil {
			return nil, err
		}

		defer func() {
			// return value of latest err, if there is no error just return lazily
			if err == nil {
				return
			}

			d.Push("Destroying image", 95)
			err := d.DestroyImage(image.Id)
			if err != nil {
				curlstr := fmt.Sprintf("curl '%v/images/%d/destroy?client_id=%v&api_key=%v'",
					digitalocean.DIGITALOCEAN_API_URL, image.Id, d.Creds.ClientID, d.Creds.APIKey)

				d.Push(fmt.Sprintf("Error cleaning up droplet. Please delete the droplet manually: %v", curlstr), 95)
			}
		}()
	}

	machine, err := d.DropletWithKey(dropletName, image.Id)
	if err != nil {
		return nil, err
	}

	sshAddress := machine.Droplet.IpAddress + ":22"
	sshConfig, err := sshutil.SshConfig(machine.PrivateKey)
	if err != nil {
		return nil, err
	}

	d.Push(fmt.Sprintf("Connecting to ssh %s", sshAddress), 65)
	client, err := sshutil.ConnectSSH(sshAddress, sshConfig)
	if err != nil {
		return nil, err
	}
	defer client.Close()

	// generate kite key specific for the user
	d.Push("Creating kite.key", 70)
	kiteKey, kiteId, err := d.SignFunc(opts.Username)
	if err != nil {
		return nil, err
	}
	d.Push(fmt.Sprintf("Kite key created for id %s", kiteId), 75)

	// for debugging, remove it later ...
	d.Push(fmt.Sprintf("Writing kite key to temporary file (kite.key)"), 75)
	// DEBUG
	// if err := ioutil.WriteFile("kite.key", []byte(kiteKey), 0400); err != nil {
	// 	d.Log.Info("couldn't write temporary kite file", err)
	// }

	keyPath := "/opt/kite/klient/key/kite.key"

	d.Push(fmt.Sprintf("Copying remote kite key %s", keyPath), 85)
	remoteFile, err := client.Create(keyPath)
	if err != nil {
		return nil, err
	}

	_, err = remoteFile.Write([]byte(kiteKey))
	if err != nil {
		return nil, err
	}

	d.Push(fmt.Sprintf("Starting klient on remote machine"), 90)
	if err := client.StartCommand("service klient start"); err != nil {
		return nil, err
	}

	// arslan/public-host/klient/0.0.1/unknown/testkloud-1401755272229370184-0/393ff626-8fa5-4713-648c-4a51604f98c6
	klient := kiteprotocol.Kite{
		Username:    opts.Username, // kite.key is signed for this user
		ID:          kiteId,        // id is generated by ourself
		Hostname:    dropletName,   // hostname is the dropletName
		Name:        klientprotocol.Name,
		Environment: klientprotocol.Environment,
		Region:      klientprotocol.Region,
		Version:     klientprotocol.Version,
	}

	return &protocol.BuildResponse{
		QueryString:  klient.String(),
		IpAddress:    machine.Droplet.IpAddress,
		InstanceName: machine.Droplet.Name,
		InstanceId:   machine.Droplet.Id,
	}, nil
}

// Start starts the machine for the given dropletID
func (d *DigitalOcean) Start(opts *protocol.MachineOptions) error {
	d.setPusher(opts, machinestate.Starting)
	dropletId, err := d.DropletId()
	if err != nil {
		return err
	}

	d.Push("Starting machine", 10)

	path := fmt.Sprintf("droplets/%v/power_on", dropletId)
	body, err := digitalocean.NewRequest(*d.Client, path, url.Values{})
	if err != nil {
		return err
	}

	d.Push("Start message is being sent, waiting.", 30)

	eventId, ok := body["event_id"].(float64)
	if !ok {
		return fmt.Errorf("restart malformed data %v", body)
	}

	return d.WaitUntilReady(int(eventId), 30, 80)
}

// Stop stops the machine for the given dropletID
func (d *DigitalOcean) Stop(opts *protocol.MachineOptions) error {
	d.setPusher(opts, machinestate.Stopping)
	dropletId, err := d.DropletId()
	if err != nil {
		return err
	}

	d.Push("Stopping machine", 10)

	path := fmt.Sprintf("droplets/%v/shutdown", dropletId)
	body, err := digitalocean.NewRequest(*d.Client, path, url.Values{})
	if err != nil {
		return err
	}

	d.Push("Stop message is being sent, waiting.", 30)

	eventId, ok := body["event_id"].(float64)
	if !ok {
		return fmt.Errorf("restart malformed data %v", body)
	}

	return d.WaitUntilReady(int(eventId), 30, 80)
}

// Restart restart the machine for the given dropletID
func (d *DigitalOcean) Restart(opts *protocol.MachineOptions) error {
	d.setPusher(opts, machinestate.Rebooting)
	dropletId, err := d.DropletId()
	if err != nil {
		return err
	}

	d.Push("Rebooting machine", 10)

	path := fmt.Sprintf("droplets/%v/reboot", dropletId)
	body, err := digitalocean.NewRequest(*d.Client, path, url.Values{})
	if err != nil {
		return err
	}

	d.Push("Reboot message is being sent, waiting.", 30)

	eventId, ok := body["event_id"].(float64)
	if !ok {
		return fmt.Errorf("restart malformed data %v", body)
	}

	return d.WaitUntilReady(int(eventId), 30, 80)
}

// Destroy destroys the machine with the given droplet ID.
func (d *DigitalOcean) Destroy(opts *protocol.MachineOptions) error {
	d.setPusher(opts, machinestate.Terminating)
	dropletId, err := d.DropletId()
	if err != nil {
		return err
	}

	d.Push("Terminating machine", 10)

	path := fmt.Sprintf("droplets/%v/destroy", dropletId)
	body, err := digitalocean.NewRequest(*d.Client, path, url.Values{})
	if err != nil {
		return err
	}

	d.Push("Terminating message is being sent, waiting.", 30)

	eventId, ok := body["event_id"].(float64)
	if !ok {
		return fmt.Errorf("restart malformed data %v", body)
	}

	return d.WaitUntilReady(int(eventId), 50, 80)
}

// Info returns all information about the given droplet info.
func (d *DigitalOcean) Info(opts *protocol.MachineOptions) (*protocol.InfoResponse, error) {
	dropletId, err := d.DropletId()
	if err != nil {
		return nil, err
	}

	droplet, err := d.DropletInfo(dropletId)
	if err != nil {
		return nil, err
	}

	if statusToState(droplet.Status) == machinestate.Unknown {
		d.Log.Warning("Unknown digitalocean status: %s. This needs to be fixed.", droplet.Status)
	}

	return &protocol.InfoResponse{
		State: statusToState(droplet.Status),
	}, nil

}

// statusToState converts a digitalocean status to a sensible
// machinestate.State format
func statusToState(status string) machinestate.State {
	switch status {
	case "active":
		return machinestate.Running
	case "off":
		return machinestate.Stopped
	case "new":
		return machinestate.Building
	default:
		return machinestate.Unknown
	}

}

func (d *DigitalOcean) setPusher(opts *protocol.MachineOptions, state machinestate.State) {
	d.Push = func(msg string, percentage int) {
		d.Log.Info("[machineId: '%s': username: '%s' dropletName: '%s' snapshotName: '%s'] - %s",
			opts.MachineId, opts.Username, opts.InstanceName, opts.ImageName, msg)

		opts.Eventer.Push(&eventer.Event{
			Message:    msg,
			Status:     state,
			Percentage: percentage,
		})
	}
}
