package j_machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JMachineOneReader is a Reader for the JMachineOne structure.
type JMachineOneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JMachineOneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJMachineOneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewJMachineOneUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJMachineOneOK creates a JMachineOneOK with default headers values
func NewJMachineOneOK() *JMachineOneOK {
	return &JMachineOneOK{}
}

/*JMachineOneOK handles this case with default header values.

Request processed successfully
*/
type JMachineOneOK struct {
	Payload *models.DefaultResponse
}

func (o *JMachineOneOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JMachine.one][%d] jMachineOneOK  %+v", 200, o.Payload)
}

func (o *JMachineOneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJMachineOneUnauthorized creates a JMachineOneUnauthorized with default headers values
func NewJMachineOneUnauthorized() *JMachineOneUnauthorized {
	return &JMachineOneUnauthorized{}
}

/*JMachineOneUnauthorized handles this case with default header values.

Unauthorized request
*/
type JMachineOneUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *JMachineOneUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JMachine.one][%d] jMachineOneUnauthorized  %+v", 401, o.Payload)
}

func (o *JMachineOneUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
