package j_machine

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewPostRemoteAPIJMachineShareIDParams creates a new PostRemoteAPIJMachineShareIDParams object
// with the default values initialized.
func NewPostRemoteAPIJMachineShareIDParams() *PostRemoteAPIJMachineShareIDParams {
	var ()
	return &PostRemoteAPIJMachineShareIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJMachineShareIDParamsWithTimeout creates a new PostRemoteAPIJMachineShareIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJMachineShareIDParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJMachineShareIDParams {
	var ()
	return &PostRemoteAPIJMachineShareIDParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJMachineShareIDParamsWithContext creates a new PostRemoteAPIJMachineShareIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJMachineShareIDParamsWithContext(ctx context.Context) *PostRemoteAPIJMachineShareIDParams {
	var ()
	return &PostRemoteAPIJMachineShareIDParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJMachineShareIDParams contains all the parameters to send to the API endpoint
for the post remote API j machine share ID operation typically these are written to a http.Request
*/
type PostRemoteAPIJMachineShareIDParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJMachineShareIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) WithContext(ctx context.Context) *PostRemoteAPIJMachineShareIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) WithBody(body models.DefaultSelector) *PostRemoteAPIJMachineShareIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) WithID(id string) *PostRemoteAPIJMachineShareIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post remote API j machine share ID params
func (o *PostRemoteAPIJMachineShareIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJMachineShareIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
