sudo: false

language: go

before_script:
  - go get -u github.com/golang/lint/golint

go: 1.5
script:
  - test -z "$(gofmt -s -l -w ./autorest/. | tee /dev/stderr)"
  - test -z "$(golint ./... |  tee /dev/stderr)"
  - go vet ./...
  - go build -v ./...
  - go test -v ./...
