#!/bin/bash

if [ -n "$DISABLE_TESTS" ]; then
    echo "Tests are disabled"
    exit 0
fi

INSTANCE_DATA_FILE=$1

if [ "$WERCKER_RESULT" = "failed" ]; then
  if [ -z "$TERMINATE_FAILED_TEST_INSTANCE" ]; then
    exit 0
  fi
fi

SCRIPTS=$(dirname $0)/..

INSTANCE_IDS=$(cat $INSTANCE_DATA_FILE | awk '{print $1}')

# `terminate` script does accept a single instance id.  `xargs -n 1`
# passes instance ids to `terminate` script one by one.

echo $INSTANCE_IDS | xargs -n 1 $SCRIPTS/test-instance/unprotect
echo $INSTANCE_IDS | xargs -n 1 $SCRIPTS/test-instance/terminate
