#!/bin/bash

INSTANCE_DATA_FILE=$1

SCRIPTS=$(dirname $0)/..

INSTANCES=$(cat $INSTANCE_DATA_FILE)

function check () {
  INSTANCE=$1
  INSTANCE_ID=$(echo $INSTANCE | awk '{print $1}')
  HOST=$(echo $INSTANCE | awk '{print $2}')

  PORT=$2
  INTERVAL=$3
  TRY_COUNT=$4

  echo -en "$HOST:$PORT\t\t"
  $SCRIPTS/test-instance/check-connectivity $HOST $PORT $INTERVAL $TRY_COUNT
}

rm -f $INSTANCE_DATA_FILE
touch $INSTANCE_DATA_FILE

IFS=$'\n'
for INSTANCE in $INSTANCES; do
  check $INSTANCE 8090 1m 1 || continue # nginx
  check $INSTANCE 4444 1m 1 || continue # selenium-server
  echo $INSTANCE >> $INSTANCE_DATA_FILE
  echo
done

exit 0
