#!/bin/bash

INSTANCE_DATA_FILE=$1

SCRIPTS=$(dirname $0)/..

function terminate_instance () {
  INSTANCE_ID=$1
  $SCRIPTS/test-instance/terminate $INSTANCE_ID
}

function check () {
  INSTANCE=$1
  INSTANCE_ID=$(echo $INSTANCE | awk '{print $1}')
  HOST=$(echo $INSTANCE | awk '{print $2}')

  PORT=$2
  INTERVAL=$3
  TRY_COUNT=$4

  echo -en "$HOST:$PORT\t\t"
  $SCRIPTS/test-instance/check-connectivity $HOST $PORT $INTERVAL $TRY_COUNT
  EXIT_CODE=$?

  if [ $EXIT_CODE -ne 0 ]; then
    terminate_instance $INSTANCE_ID
  fi

  return $EXIT_CODE
}

function health_check () {
  echo -n "Health check $INSTANCE "
  INSTANCE=$1
  HOST=$(echo $INSTANCE | awk '{print $2}')
  OUTPUT=$(curl --silent --dump-header /dev/stdout "http://$HOST:8090/-/healthCheck")
  STATUS_LINE=$(echo "$OUTPUT" | head -n1)
  STATUS_LINE=$(echo "$STATUS_LINE" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

  if [ "$STATUS_LINE" != "HTTP/1.1 200 OK" ]; then
    echo 'NOT OK'
    return 1
  fi

  echo 'OK'
  return 0
}

IFS=$'\n'

INSTANCES=$(cat $INSTANCE_DATA_FILE)
truncate --size 0 $INSTANCE_DATA_FILE

for INSTANCE in $INSTANCES; do
  (
    check $INSTANCE  8090 1m 1 || continue # nginx
    check $INSTANCE 42424 1m 1 || continue # selenium-server

    if health_check $INSTANCE; then
      echo $INSTANCE >> $INSTANCE_DATA_FILE
    fi
  ) &
done

wait

INSTANCE_IDS=$(cat $INSTANCE_DATA_FILE | awk '{print $1}')

if [ -z "$INSTANCE_IDS" ]; then
  exit 1
fi

INSTANCE_COUNT=$(echo $INSTANCE_IDS | wc -l)

if [ $INSTANCE_COUNT -eq 0 ]; then
  exit 1
fi

echo $INSTANCE_IDS | xargs -n 1 $SCRIPTS/test-instance/protect

exit 0
