#!/bin/bash

set -o errexit

cd $WERCKER_ROOT/go
mkdir -p src/socialapi/db/sql/kontrol
cp src/vendor/github.com/koding/kite/kontrol/*.sql src/socialapi/db/sql/kontrol/
src/socialapi/db/sql/definition/create-wercker.sh src/socialapi/db/sql
../run migrations
bin/migrate -url "postgres://$WERCKER_POSTGRESQL_HOST:$WERCKER_POSTGRESQL_PORT/$WERCKER_POSTGRESQL_DATABASE?user=$WERCKER_POSTGRESQL_USERNAME&password=$WERCKER_POSTGRESQL_PASSWORD" -path "src/socialapi/db/sql/migrations" up

exit 0
