#!/bin/bash

set -o errexit

$GOPATH/src/socialapi/db/sql/definition/create-wercker.sh src/socialapi/db/sql
$KONFIG_PROJECTROOT/run migrations
$GOBIN/migrate -url $KONFIG_POSTGRES_URL -path $GOPATH/src/socialapi/db/sql/migrations up
