#!/bin/bash

cd $(dirname $0)

OPTIONS=''

HEADS=$(git branch -r -v | \
           grep ${WERCKER_GIT_COMMIT:0:7} | \
           awk '{print $1}')

for HEAD in $HEADS; do
  if [ -n "$(echo $HEAD | grep '/pull/')" ]; then
    PR_HEAD=$HEAD
  fi
done

if [ -n "$PR_HEAD" ]; then
  PR_NR=$(echo $PR_HEAD | awk -F '/' '{print $NF}')
  OPTIONS="--pull-request '+refs/pull/$PR_NR/head' $OPTIONS"
else
  OPTIONS="--commit $WERCKER_GIT_COMMIT $OPTIONS"
fi

echo $OPTIONS

exit 0
