#!/bin/bash

REMOTE_BRANCH=$1
BRANCH_NAME=$(echo $REMOTE_BRANCH | awk -F '/' '{print $NF}')

if [ -z $BRANCH_NAME ]; then
    exit 1
fi

if [ $(echo $REMOTE_BRANCH | grep 'origin/pull/') ]; then
    echo "+refs/pull/$BRANCH_NAME/head"
else
    echo "+refs/heads/$BRANCH_NAME"
fi
