#!/bin/bash

set -e

HOST=$(ec2metadata | grep public-hostname | FS=':' awk '{print $2}')

export HOME=/root/
export DISPLAY=:99
export REPOSITORY_PATH='/opt/koding'

function npm_install ()
{
  PROJECT_NAME=$1
  DIRECTORY=$2

  if [ -n "$DIRECTORY" ]; then
    cd $REPOSITORY_PATH/$DIRECTORY
  fi

  rm -rf node_modules
  git clone git@github.com:koding/$PROJECT_NAME-node_modules-wercker.git node_modules
}

service nginx stop

npm_install koding
npm_install client  client/
npm_install landing client/landing

cd $REPOSITORY_PATH

./configure --host $HOST:8090
./run services
./run install
./run resetdb --yes
./run &
disown $!

sleep 60

Xvfb $DISPLAY -shmem -screen 0 1440x1200x16 &
sleep 15

x11vnc -passwd secret -display $DISPLAY -N -forever &
sleep 10

su nightwatch -c 'start-selenium &'

exit 0
