#!/bin/bash

cp scripts/wercker/social-api.conf /etc/init/social-api.conf
touch /etc/init.d/social-api
initctl emit social-api KONFIG_SOCIALAPI_POSTGRES_HOST=$WERCKER_POSTGRESQL_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$WERCKER_POSTGRESQL_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$WERCKER_POSTGRESQL_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$WERCKER_POSTGRESQL_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$WERCKER_POSTGRESQL_DATABASE \
                        KONFIG_SOCIALAPI_MQ_HOST=$WERCKER_RABBITMQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$WERCKER_RABBITMQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$WERCKER_RABBITMQ_USERNAME \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$WERCKER_RABBITMQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$WERCKER_REDIS_HOST:$WERCKER_REDIS_PORT \
                        KONFIG_SOCIALAPI_MONGO=$WERCKER_MONGODB_URL \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR


cp scripts/wercker/social-populartopic.conf /etc/init/social-populartopic.conf
touch /etc/init.d/social-populartopic
initctl emit social-populartopic KONFIG_SOCIALAPI_POSTGRES_HOST=$WERCKER_POSTGRESQL_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$WERCKER_POSTGRESQL_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$WERCKER_POSTGRESQL_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$WERCKER_POSTGRESQL_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$WERCKER_POSTGRESQL_DATABASE \
                        KONFIG_SOCIALAPI_MQ_HOST=$WERCKER_RABBITMQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$WERCKER_RABBITMQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$WERCKER_RABBITMQ_USERNAME \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$WERCKER_RABBITMQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$WERCKER_REDIS_HOST:$WERCKER_REDIS_PORT \
                        KONFIG_SOCIALAPI_MONGO=$WERCKER_MONGODB_URL \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR

cp scripts/wercker/social-pinnedpost.conf /etc/init/social-pinnedpost.conf
touch /etc/init.d/social-pinnedpost
initctl emit social-pinnedpost KONFIG_SOCIALAPI_POSTGRES_HOST=$WERCKER_POSTGRESQL_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$WERCKER_POSTGRESQL_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$WERCKER_POSTGRESQL_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$WERCKER_POSTGRESQL_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$WERCKER_POSTGRESQL_DATABASE \
                        KONFIG_SOCIALAPI_MQ_HOST=$WERCKER_RABBITMQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$WERCKER_RABBITMQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$WERCKER_RABBITMQ_USERNAME \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$WERCKER_RABBITMQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$WERCKER_REDIS_HOST:$WERCKER_REDIS_PORT \
                        KONFIG_SOCIALAPI_MONGO=$WERCKER_MONGODB_URL \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR
