#!/bin/bash

cp scripts/wercker/social-api.conf /etc/init/social-api.conf
touch /etc/init.d/social-api
initctl emit social-api KONFIG_SOCIALAPI_POSTGRES_HOST=$KONFIG_SOCIALAPI_POSTGRES_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$KONFIG_SOCIALAPI_POSTGRES_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$KONFIG_SOCIALAPI_POSTGRES_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$KONFIG_SOCIALAPI_POSTGRES_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$KONFIG_SOCIALAPI_POSTGRES_DBNAME \
                        KONFIG_SOCIALAPI_MQ_HOST=$KONFIG_SOCIALAPI_MQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$KONFIG_SOCIALAPI_MQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$KONFIG_SOCIALAPI_MQ_LOGIN \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$KONFIG_SOCIALAPI_MQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$KONFIG_SOCIALAPI_REDIS_URL \
                        KONFIG_SOCIALAPI_MONGO=$KONFIG_SOCIALAPI_MONGO \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR


cp scripts/wercker/social-populartopic.conf /etc/init/social-populartopic.conf
touch /etc/init.d/social-populartopic
initctl emit social-populartopic KONFIG_SOCIALAPI_POSTGRES_HOST=$KONFIG_SOCIALAPI_POSTGRES_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$KONFIG_SOCIALAPI_POSTGRES_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$KONFIG_SOCIALAPI_POSTGRES_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$KONFIG_SOCIALAPI_POSTGRES_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$KONFIG_SOCIALAPI_POSTGRES_DBNAME \
                        KONFIG_SOCIALAPI_MQ_HOST=$KONFIG_SOCIALAPI_MQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$KONFIG_SOCIALAPI_MQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$KONFIG_SOCIALAPI_MQ_LOGIN \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$KONFIG_SOCIALAPI_MQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$KONFIG_SOCIALAPI_REDIS_URL \
                        KONFIG_SOCIALAPI_MONGO=$KONFIG_SOCIALAPI_MONGO \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR

cp scripts/wercker/social-pinnedpost.conf /etc/init/social-pinnedpost.conf
touch /etc/init.d/social-pinnedpost
initctl emit social-pinnedpost KONFIG_SOCIALAPI_POSTGRES_HOST=$KONFIG_SOCIALAPI_POSTGRES_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$KONFIG_SOCIALAPI_POSTGRES_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$KONFIG_SOCIALAPI_POSTGRES_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$KONFIG_SOCIALAPI_POSTGRES_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$KONFIG_SOCIALAPI_POSTGRES_DBNAME \
                        KONFIG_SOCIALAPI_MQ_HOST=$KONFIG_SOCIALAPI_MQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$KONFIG_SOCIALAPI_MQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$KONFIG_SOCIALAPI_MQ_LOGIN \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$KONFIG_SOCIALAPI_MQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$KONFIG_SOCIALAPI_REDIS_URL \
                        KONFIG_SOCIALAPI_MONGO=$KONFIG_SOCIALAPI_MONGO \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR

cp scripts/wercker/social-webhook.conf /etc/init/social-webhook.conf
touch /etc/init.d/social-webhook
initctl emit social-webhook KONFIG_SOCIALAPI_POSTGRES_HOST=$KONFIG_SOCIALAPI_POSTGRES_HOST \
                        KONFIG_SOCIALAPI_POSTGRES_PORT=$KONFIG_SOCIALAPI_POSTGRES_PORT \
                        KONFIG_SOCIALAPI_POSTGRES_USERNAME=$KONFIG_SOCIALAPI_POSTGRES_USERNAME \
                        KONFIG_SOCIALAPI_POSTGRES_PASSWORD=$KONFIG_SOCIALAPI_POSTGRES_PASSWORD \
                        KONFIG_SOCIALAPI_POSTGRES_DBNAME=$KONFIG_SOCIALAPI_POSTGRES_DBNAME \
                        KONFIG_SOCIALAPI_MQ_HOST=$KONFIG_SOCIALAPI_MQ_HOST \
                        KONFIG_SOCIALAPI_MQ_PORT=$KONFIG_SOCIALAPI_MQ_PORT \
                        KONFIG_SOCIALAPI_MQ_LOGIN=$KONFIG_SOCIALAPI_MQ_LOGIN \
                        KONFIG_SOCIALAPI_MQ_PASSWORD=$KONFIG_SOCIALAPI_MQ_PASSWORD \
                        KONFIG_SOCIALAPI_REDIS_URL=$KONFIG_SOCIALAPI_REDIS_URL \
                        KONFIG_SOCIALAPI_MONGO=$KONFIG_SOCIALAPI_MONGO \
                        WERCKER_SOURCE_DIR=$WERCKER_SOURCE_DIR
