#!/bin/bash

set -e

HOST=$(ec2metadata | grep public-hostname | FS=':' awk '{print $2}')

export REPOSITORY_PATH='/opt/koding'
export DISPLAY=:99

service nginx stop

cd $REPOSITORY_PATH
HOME=/root/ npm install --unsafe-perm
./configure --host $HOST:8090
./run services
./run install
./run &
disown $!

sleep 60

Xvfb $DISPLAY -shmem -screen 0 1440x1200x16 &
sleep 10

x11vnc -passwd secret -display $DISPLAY -N -forever &
sleep 10

su nightwatch -c 'start-selenium &'

exit 0
