#!/bin/bash

set -o errexit
set -o xtrace

PROJECT_NAME=$1
NODE_MODULES=$WERCKER_CACHE_DIR/$PROJECT_NAME-node-modules

if [ -d $NODE_MODULES ]; then
  rsync $NODE_MODULES/ node_modules/
fi

npm install
rsync node_modules/ $NODE_MODULES/
