#!/bin/bash

set -o errexit

PROJECT_NAME=$1

USER=git
HOST=github.com
REPOSITORY_NAME=$PROJECT_NAME-node_modules-wercker.git
REPOSITORY_URL=$USER@$HOST:koding/$REPOSITORY_NAME

git clone $REPOSITORY_URL node_modules

npm install

cd node_modules

find . -mindepth 2 -iname '.git' -delete

git add --force --ignore-errors .
git commit --all --message 'Updated' || :
git push origin master

exit 0
