#!/bin/bash

SCRIPTS_DIR=$WERCKER_ROOT/scripts

set -o errexit

INSTANCE_OPTIONS=$($SCRIPTS_DIR/test-instance/get-options)
echo $INSTANCE_OPTIONS
$SCRIPTS_DIR/test-instance/launch $INSTANCE_OPTIONS > INSTANCE_DATA
cat INSTANCE_DATA

exit 0
