#!/bin/bash

SCRIPTS_DIR=$WERCKER_ROOT/scripts

set -o errexit

BRANCH_NAME=${BRANCH_NAME:-$WERCKER_GIT_BRANCH}
COUNT=$(coffee -e "console.log require('$SCRIPTS_DIR/test-instance/parallel-sets').length")

INSTANCE_OPTIONS=$($SCRIPTS_DIR/test-instance/get-options)
INSTANCE_OPTIONS="--branch-name $BRANCH_NAME $INSTANCE_OPTIONS"
INSTANCE_OPTIONS="--count $COUNT $INSTANCE_OPTIONS"
$SCRIPTS_DIR/test-instance/launch $INSTANCE_OPTIONS
