#!/bin/bash

INSTANCE_DATA=$1
HOST="http://$(head -n1 $INSTANCE_DATA | awk '{ print $2}'):8090"

pushd ./tests
gem install rainforest-cli

rainforest upload --token $RAINFOREST_TOKEN

rainforest run --token $RAINFOREST_TOKEN \
           --tag automated \
           --site_id 5822 \
           --fail-fast \
           --custom_url $HOST \
           --description "wercker build for ${WERCKER_GIT_COMMIT:0:8}" \
           --fg
