#!/bin/bash

declare instance_data_file=$1

declare scripts=$(dirname $0)/..

if [ "$WERCKER_RESULT" = "passed" ]; then
	exit 0
fi

cat $instance_data_file | awk '{print $2}' \
	| xargs -n 1 \
		-I HOST \
		$KONFIG_PROJECTROOT/scripts/test-instance/ssh HOST \
		"sudo /opt/koding/run exec \
			/opt/koding/scripts/test-instance/upload-logs \
			$WERCKER_BUILD_ID \
			$KONFIG_TEST_CREDENTIALS_AWS_ACCESSKEYID \
			$KONFIG_TEST_CREDENTIALS_AWS_SECRETACCESSKEY"

cat - <<EOF
You can view logs at s3://kodingdev-test-instance-logs/$WERCKER_BUILD_ID/
EOF

exit 0
