package j_name

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJNameOneReader is a Reader for the PostRemoteAPIJNameOne structure.
type PostRemoteAPIJNameOneReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJNameOneReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJNameOneOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPIJNameOneUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJNameOneOK creates a PostRemoteAPIJNameOneOK with default headers values
func NewPostRemoteAPIJNameOneOK() *PostRemoteAPIJNameOneOK {
	return &PostRemoteAPIJNameOneOK{}
}

/*PostRemoteAPIJNameOneOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPIJNameOneOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPIJNameOneOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JName.one][%d] postRemoteApiJNameOneOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJNameOneOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPIJNameOneUnauthorized creates a PostRemoteAPIJNameOneUnauthorized with default headers values
func NewPostRemoteAPIJNameOneUnauthorized() *PostRemoteAPIJNameOneUnauthorized {
	return &PostRemoteAPIJNameOneUnauthorized{}
}

/*PostRemoteAPIJNameOneUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPIJNameOneUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPIJNameOneUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JName.one][%d] postRemoteApiJNameOneUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPIJNameOneUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
