require './browseprivatechannelsmodal/test'
require './datemarker/test'
require './appcomponent/test'
require './chatinputwidget/test'
require './browsepublicchannelsmodal/test'
require './channelinfo/test'
require './channellabel/test'
require './channelparticipants/test'
require './channelparticipantsinputwidget/test'

