sudo: false

language: go

go:
  - 1.5
  - tip

install: make updatedeps

script:
  - make test

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#terraform-tool"
    skip_join: true
    use_notice: true

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
