sudo: false

language: go

go:
  - 1.6

# Need to ensure at least something remains in the install stanza to opt out of
# Travis's built-in 'godep restore', which will fail Travis
# See https://docs.travis-ci.com/user/languages/go#godep-support
install:
  - echo noop

script:
  - make test vet

branches:
  only:
    - master

notifications:
  irc:
    channels:
      - "irc.freenode.org#terraform-tool"
    skip_join: true
    use_notice: true

matrix:
  fast_finish: true
  allow_failures:
    - go: tip
