all::
	g++ -g -o test main.cpp -fPIC  -I../../build/sdk/include  -I../../build/app/libraries/log/include -I../ -lpthread -lutil -L../../build/app/libraries/log/lib -llog -L../../build/sdk/lib.static/boost/ -lboost_log-mt -lboost_filesystem-mt -lboost_thread-mt -lboost_system-mt  
