
{exec} = require "child_process"
fs     = require "fs"

task "install","installs required modules for kfmjs to build",(options)->
  fs.mkdir "./node_modules",()->  
    l = (d) -> console.log d.replace /\n+$/, ''
    exe = "npm i hat noxmox stylus coffee-script@1.3.3 underscore log4js@0.4.1 nib progress prompt sqwish gzip mkdirp"        
    a = exec exe,->
    a.stdout.on 'data', l
    a.stderr.on 'data', l

  
