package social_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPISocialChannelLeaveReader is a Reader for the PostRemoteAPISocialChannelLeave structure.
type PostRemoteAPISocialChannelLeaveReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPISocialChannelLeaveReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPISocialChannelLeaveOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPISocialChannelLeaveUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPISocialChannelLeaveOK creates a PostRemoteAPISocialChannelLeaveOK with default headers values
func NewPostRemoteAPISocialChannelLeaveOK() *PostRemoteAPISocialChannelLeaveOK {
	return &PostRemoteAPISocialChannelLeaveOK{}
}

/*PostRemoteAPISocialChannelLeaveOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPISocialChannelLeaveOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPISocialChannelLeaveOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.leave][%d] postRemoteApiSocialChannelLeaveOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPISocialChannelLeaveOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPISocialChannelLeaveUnauthorized creates a PostRemoteAPISocialChannelLeaveUnauthorized with default headers values
func NewPostRemoteAPISocialChannelLeaveUnauthorized() *PostRemoteAPISocialChannelLeaveUnauthorized {
	return &PostRemoteAPISocialChannelLeaveUnauthorized{}
}

/*PostRemoteAPISocialChannelLeaveUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPISocialChannelLeaveUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPISocialChannelLeaveUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.leave][%d] postRemoteApiSocialChannelLeaveUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPISocialChannelLeaveUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
