package social_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewPostRemoteAPISocialChannelRemoveParticipantsParams creates a new PostRemoteAPISocialChannelRemoveParticipantsParams object
// with the default values initialized.
func NewPostRemoteAPISocialChannelRemoveParticipantsParams() *PostRemoteAPISocialChannelRemoveParticipantsParams {
	var ()
	return &PostRemoteAPISocialChannelRemoveParticipantsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPISocialChannelRemoveParticipantsParamsWithTimeout creates a new PostRemoteAPISocialChannelRemoveParticipantsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPISocialChannelRemoveParticipantsParamsWithTimeout(timeout time.Duration) *PostRemoteAPISocialChannelRemoveParticipantsParams {
	var ()
	return &PostRemoteAPISocialChannelRemoveParticipantsParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPISocialChannelRemoveParticipantsParamsWithContext creates a new PostRemoteAPISocialChannelRemoveParticipantsParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPISocialChannelRemoveParticipantsParamsWithContext(ctx context.Context) *PostRemoteAPISocialChannelRemoveParticipantsParams {
	var ()
	return &PostRemoteAPISocialChannelRemoveParticipantsParams{

		Context: ctx,
	}
}

/*PostRemoteAPISocialChannelRemoveParticipantsParams contains all the parameters to send to the API endpoint
for the post remote API social channel remove participants operation typically these are written to a http.Request
*/
type PostRemoteAPISocialChannelRemoveParticipantsParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) WithTimeout(timeout time.Duration) *PostRemoteAPISocialChannelRemoveParticipantsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) WithContext(ctx context.Context) *PostRemoteAPISocialChannelRemoveParticipantsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) WithBody(body models.DefaultSelector) *PostRemoteAPISocialChannelRemoveParticipantsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API social channel remove participants params
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPISocialChannelRemoveParticipantsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
