package social_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPISocialChannelPinMessageReader is a Reader for the PostRemoteAPISocialChannelPinMessage structure.
type PostRemoteAPISocialChannelPinMessageReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPISocialChannelPinMessageReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPISocialChannelPinMessageOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPISocialChannelPinMessageUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPISocialChannelPinMessageOK creates a PostRemoteAPISocialChannelPinMessageOK with default headers values
func NewPostRemoteAPISocialChannelPinMessageOK() *PostRemoteAPISocialChannelPinMessageOK {
	return &PostRemoteAPISocialChannelPinMessageOK{}
}

/*PostRemoteAPISocialChannelPinMessageOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPISocialChannelPinMessageOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPISocialChannelPinMessageOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.pinMessage][%d] postRemoteApiSocialChannelPinMessageOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPISocialChannelPinMessageOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPISocialChannelPinMessageUnauthorized creates a PostRemoteAPISocialChannelPinMessageUnauthorized with default headers values
func NewPostRemoteAPISocialChannelPinMessageUnauthorized() *PostRemoteAPISocialChannelPinMessageUnauthorized {
	return &PostRemoteAPISocialChannelPinMessageUnauthorized{}
}

/*PostRemoteAPISocialChannelPinMessageUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPISocialChannelPinMessageUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPISocialChannelPinMessageUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.pinMessage][%d] postRemoteApiSocialChannelPinMessageUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPISocialChannelPinMessageUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
