package social_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPISocialChannelUpdateLastSeenTimeReader is a Reader for the PostRemoteAPISocialChannelUpdateLastSeenTime structure.
type PostRemoteAPISocialChannelUpdateLastSeenTimeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPISocialChannelUpdateLastSeenTimeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPISocialChannelUpdateLastSeenTimeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewPostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPISocialChannelUpdateLastSeenTimeOK creates a PostRemoteAPISocialChannelUpdateLastSeenTimeOK with default headers values
func NewPostRemoteAPISocialChannelUpdateLastSeenTimeOK() *PostRemoteAPISocialChannelUpdateLastSeenTimeOK {
	return &PostRemoteAPISocialChannelUpdateLastSeenTimeOK{}
}

/*PostRemoteAPISocialChannelUpdateLastSeenTimeOK handles this case with default header values.

Request processed successfully
*/
type PostRemoteAPISocialChannelUpdateLastSeenTimeOK struct {
	Payload *models.DefaultResponse
}

func (o *PostRemoteAPISocialChannelUpdateLastSeenTimeOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.updateLastSeenTime][%d] postRemoteApiSocialChannelUpdateLastSeenTimeOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPISocialChannelUpdateLastSeenTimeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewPostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized creates a PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized with default headers values
func NewPostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized() *PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized {
	return &PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized{}
}

/*PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized handles this case with default header values.

Unauthorized request
*/
type PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/SocialChannel.updateLastSeenTime][%d] postRemoteApiSocialChannelUpdateLastSeenTimeUnauthorized  %+v", 401, o.Payload)
}

func (o *PostRemoteAPISocialChannelUpdateLastSeenTimeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
