package social_channel

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewSocialChannelRemoveParticipantsParams creates a new SocialChannelRemoveParticipantsParams object
// with the default values initialized.
func NewSocialChannelRemoveParticipantsParams() *SocialChannelRemoveParticipantsParams {
	var ()
	return &SocialChannelRemoveParticipantsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewSocialChannelRemoveParticipantsParamsWithTimeout creates a new SocialChannelRemoveParticipantsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewSocialChannelRemoveParticipantsParamsWithTimeout(timeout time.Duration) *SocialChannelRemoveParticipantsParams {
	var ()
	return &SocialChannelRemoveParticipantsParams{

		timeout: timeout,
	}
}

// NewSocialChannelRemoveParticipantsParamsWithContext creates a new SocialChannelRemoveParticipantsParams object
// with the default values initialized, and the ability to set a context for a request
func NewSocialChannelRemoveParticipantsParamsWithContext(ctx context.Context) *SocialChannelRemoveParticipantsParams {
	var ()
	return &SocialChannelRemoveParticipantsParams{

		Context: ctx,
	}
}

/*SocialChannelRemoveParticipantsParams contains all the parameters to send to the API endpoint
for the social channel remove participants operation typically these are written to a http.Request
*/
type SocialChannelRemoveParticipantsParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) WithTimeout(timeout time.Duration) *SocialChannelRemoveParticipantsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) WithContext(ctx context.Context) *SocialChannelRemoveParticipantsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) WithBody(body models.DefaultSelector) *SocialChannelRemoveParticipantsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the social channel remove participants params
func (o *SocialChannelRemoveParticipantsParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *SocialChannelRemoveParticipantsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
