#!/bin/bash

set -o errexit

pushd $(dirname $0)/..

function configure() {
	[ ! -d node_modules ] && npm install --unsafe-perm
	./configure "$@"
}

function build() {
	go/build.sh
	make -C client dist
	./run exec make klient
}

function run_backend() {
	go/build.sh
	migrations_up
	./run exec supervisord -c supervisord.conf
	sleep 2
	tail --follow --lines +0 --quiet .logs/*.log
}

function is_ready() {
	until [ -x ./run ] && ./run is_ready; do
		sleep 10
	done
}

function run() {
	case "$1" in
	backend)
		run_backend
		;;
	*)
		echo 'error: unknown service'
		exit 1
		;;
	esac
}

function migrations_up() {
	./run is_ready || exit 255
	./run migrations up
}

if [[ -z "$*" ]]; then
	run_backend
elif [[ "${1:0:1}" == '-' ]]; then
	configure "$@"
	build
	run_backend
elif [ "$1" = "run" ]; then
	shift
	is_ready
	run "$@"
elif [ "$1" = "k8s_build" ]; then
	shift
	source .env-kubernetes
	configure "$@"
	build
	migrations_up
elif [ "$1" = "is_ready" ]; then
	shift
	is_ready
	exec "$@"
else
	exec "$@"
fi
