#!/bin/bash

set -o errexit

pushd $(dirname $0)/..

function configure() {
  npm install --unsafe-perm
  ./configure $*
}

function build() {
  go/build.sh
  make -C client dist
}

function run_backend() {
  ./run exec scripts/check-service-connectivity.sh || exit 255
  ./run migrate up
  nginx -c $(pwd)/nginx.conf
  ./run exec supervisord -c supervisord.conf
  sleep 2
  tail --follow --lines +0 --quiet .logs/*.log
}

if [[ -z "$*" || "${1:0:1}" = '-' ]]; then
  configure $*
  run_backend
elif [ "$1" = "build" ]; then
  shift
  configure $*
  build
  run_backend
else
  exec "$@"
fi
