#!/bin/bash

set -o errexit

pushd $(dirname $0)/..

CONFIGURE_ARGS="$@"

function configure() {
  npm install --unsafe-perm
  ./configure $CONFIGURE_ARGS
}

function build() {
  configure
  go/build.sh
  make -C client dist
}

function start() {
  configure
  ./run exec scripts/check-service-connectivity.sh || exit 255
  ./run migrate up
  nginx -c $(pwd)/nginx.conf
  ./run exec supervisord -c supervisord.conf
  sleep 2
}

function tail_logs() {
  tail --follow --lines +0 --quiet .logs/*.log
}

if [[ -z "$*" || "${1:0:1}" = '-' ]]; then
  start && tail_logs
elif [ "$1" = "build" ]; then
  shift
  build && start && tail_logs
else
  exec "$@"
fi
