package j_workspace

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewPostRemoteAPIJWorkspaceUpdateParams creates a new PostRemoteAPIJWorkspaceUpdateParams object
// with the default values initialized.
func NewPostRemoteAPIJWorkspaceUpdateParams() *PostRemoteAPIJWorkspaceUpdateParams {
	var ()
	return &PostRemoteAPIJWorkspaceUpdateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJWorkspaceUpdateParamsWithTimeout creates a new PostRemoteAPIJWorkspaceUpdateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJWorkspaceUpdateParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJWorkspaceUpdateParams {
	var ()
	return &PostRemoteAPIJWorkspaceUpdateParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJWorkspaceUpdateParamsWithContext creates a new PostRemoteAPIJWorkspaceUpdateParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJWorkspaceUpdateParamsWithContext(ctx context.Context) *PostRemoteAPIJWorkspaceUpdateParams {
	var ()
	return &PostRemoteAPIJWorkspaceUpdateParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJWorkspaceUpdateParams contains all the parameters to send to the API endpoint
for the post remote API j workspace update operation typically these are written to a http.Request
*/
type PostRemoteAPIJWorkspaceUpdateParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJWorkspaceUpdateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) WithContext(ctx context.Context) *PostRemoteAPIJWorkspaceUpdateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) WithBody(body models.DefaultSelector) *PostRemoteAPIJWorkspaceUpdateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API j workspace update params
func (o *PostRemoteAPIJWorkspaceUpdateParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJWorkspaceUpdateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
