package j_kite

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRemoteAPIJKiteDeletePlanIDParams creates a new PostRemoteAPIJKiteDeletePlanIDParams object
// with the default values initialized.
func NewPostRemoteAPIJKiteDeletePlanIDParams() *PostRemoteAPIJKiteDeletePlanIDParams {
	var ()
	return &PostRemoteAPIJKiteDeletePlanIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJKiteDeletePlanIDParamsWithTimeout creates a new PostRemoteAPIJKiteDeletePlanIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJKiteDeletePlanIDParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJKiteDeletePlanIDParams {
	var ()
	return &PostRemoteAPIJKiteDeletePlanIDParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJKiteDeletePlanIDParamsWithContext creates a new PostRemoteAPIJKiteDeletePlanIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJKiteDeletePlanIDParamsWithContext(ctx context.Context) *PostRemoteAPIJKiteDeletePlanIDParams {
	var ()
	return &PostRemoteAPIJKiteDeletePlanIDParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJKiteDeletePlanIDParams contains all the parameters to send to the API endpoint
for the post remote API j kite delete plan ID operation typically these are written to a http.Request
*/
type PostRemoteAPIJKiteDeletePlanIDParams struct {

	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout time.Duration
	Context context.Context
}

// WithTimeout adds the timeout to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJKiteDeletePlanIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) WithContext(ctx context.Context) *PostRemoteAPIJKiteDeletePlanIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithID adds the id to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) WithID(id string) *PostRemoteAPIJKiteDeletePlanIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post remote API j kite delete plan ID params
func (o *PostRemoteAPIJKiteDeletePlanIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJKiteDeletePlanIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
