module.exports = {
  'LOAD_CREDENTIALS_BEGIN'
  'LOAD_CREDENTIALS_SUCCESS'
  'LOAD_CREDENTIALS_FAIL'

  'UPDATE_CREDENTIAL_SUCCESS'
  'REMOVE_CREDENTIAL_SUCCESS'

  'LOAD_CREDENTIAL_USERS'
  'UPDATE_CREDENTIAL_USERS'
}
