module.exports = {
  'LOAD_STRIPE_CLIENT_BEGIN'
  'LOAD_STRIPE_CLIENT_SUCCESS'
  'LOAD_STRIPE_CLIENT_FAIL'

  'CREATE_STRIPE_TOKEN_BEGIN'
  'CREATE_STRIPE_TOKEN_SUCCESS'
  'CREATE_STRIPE_TOKEN_FAIL'
}
