module.exports = {
  'LOAD_STRIPE_CLIENT_BEGIN'
  'LOAD_STRIPE_CLIENT_SUCCESS'
  'LOAD_STRIPE_CLIENT_FAIL'

  'CREATE_STRIPE_TOKEN_BEGIN'
  'CREATE_STRIPE_TOKEN_SUCCESS'
  'CREATE_STRIPE_TOKEN_FAIL'

  'LOAD_GROUP_INVOICES_BEGIN'
  'LOAD_GROUP_INVOICES_SUCCESS'
  'LOAD_GROUP_INVOICES_FAIL'

  'LOAD_GROUP_PLAN_BEGIN'
  'LOAD_GROUP_PLAN_SUCCESS'
  'LOAD_GROUP_PLAN_FAIL'

  'SUBSCRIBE_GROUP_PLAN_BEGIN'
  'SUBSCRIBE_GROUP_PLAN_SUCCESS'
  'SUBSCRIBE_GROUP_PLAN_FAIL'

  'LOAD_GROUP_CREDIT_CARD_BEGIN'
  'LOAD_GROUP_CREDIT_CARD_SUCCESS'
  'LOAD_GROUP_CREDIT_CARD_FAIL'

  'UPDATE_GROUP_CREDIT_CARD_BEGIN'
  'UPDATE_GROUP_CREDIT_CARD_SUCCESS'
  'UPDATE_GROUP_CREDIT_CARD_FAIL'
}
