#!/bin/bash

HOST=$1
PORT=$2
INTERVAL=$3
TRY_COUNT=$4
COUNTER=0

until nc $HOST $PORT < /dev/null; do
    COUNTER=$((COUNTER + 1))
    if [ $COUNTER -eq $TRY_COUNT ]; then
        exit 1
    fi
    sleep $INTERVAL
done
