#!/bin/bash

cd $(dirname $0)

SCRIPTS=$(pwd)/..

OPTIONS=''
PULL_REQUEST_NUMBER=$($SCRIPTS/find-pull-request)

if [ -n "$PULL_REQUEST_NUMBER" ]; then
  OPTIONS="--pull-request $PULL_REQUEST_NUMBER --commit $REVISION $OPTIONS"
else
  OPTIONS="--commit $REVISION $OPTIONS"
fi

COUNT=$(coffee -e 'console.log require("./parallel-sets").length')

if [ -n "$COUNT" ]; then
  OPTIONS="--count $COUNT $OPTIONS"
fi

echo $OPTIONS

exit 0
