#!/bin/bash

set -e

HOST=$(ec2metadata | grep public-hostname | FS=':' awk '{print $2}')

export HOME=/root/
export DISPLAY=:99
export REPOSITORY_PATH='/opt/koding'

export CI="true"
export WERCKER="true"

service nginx stop

cd $REPOSITORY_PATH

export CONFIG_DEBUGMODE="true"
export NIGHTWATCH_OPTIONS="--verbose"

scripts/wercker/install-node-modules koding
scripts/install-npm.sh -u

./configure --host $HOST:8090

scripts/install-npm.sh -d client -u

export TEST_EXTRAS="--no-start-selenium --url http://$HOST:8090"
make -C client/test build

./run services
./run install
./run migrate up
./run resetdb --yes
./run importusers

./run backend &
disown $!

sleep 60

Xvfb $DISPLAY -shmem -screen 0 1440x1200x16 &
sleep 15

x11vnc -passwd secret -display $DISPLAY -N -forever &
sleep 10

su nightwatch -c 'selenium-standalone start &'

exit 0
