#!/bin/bash

:<<EOF
This script executes client/test/run.sh script over ssh.

First option passed to this script is HOST to run test suite. Rest of
the command line options are passed to test suite runner script on
HOST.
EOF

set -o errexit

HOST=$1

shift # Remove HOST option from positional parameter array.

OPTIONS=$*

ssh -o 'StrictHostKeyChecking no' \
	-i $(dirname $0)/koding-test-instances-2015-06.pem \
	ubuntu@$HOST \
	IGNORED_TEST_CASES="'$IGNORED_TEST_CASES'" \
	NIGHTWATCH_OPTIONS="'$NIGHTWATCH_OPTIONS'" \
	CI="'$CI'" \
	"sudo -E /opt/koding/run exec /opt/koding/client/test/run.sh $OPTIONS" &

PID=$!

trap 'kill -TERM $PID' TERM

wait $PID # Wait until child process is exited

trap - TERM INT

wait $PID # In case an interrupt signal is received
