#!/bin/bash

cd $(dirname $0)/../..

HOST=$1
PRIVATE_KEY='scripts/test-instance/koding-test-instances-2015-06.pem'
USER='root'

# Discard positional parameter $1 to pass rest to `ssh` command
shift

SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no"

ssh $SSH_OPTIONS -i $PRIVATE_KEY -l $USER $HOST $*
