#!/bin/bash

cd $(dirname $0)/../..

HOST=$1
PRIVATE_KEY='scripts/test-instance/koding-test-instances-2015-06.pem'
USER='ubuntu'

# Discard positional parameter $1 to pass rest to `ssh` command
shift

ssh -i $PRIVATE_KEY -l $USER $HOST $*
