#!/bin/bash

set -o errexit

declare instance_data_file=$1

declare scripts=$(dirname $0)/..

cat $instance_data_file | awk '{print $2}' \
	| xargs -n 1 \
		-I HOST \
		$KONFIG_PROJECTROOT/scripts/test-instance/ssh HOST \
		"sudo /opt/koding/run exec \
			/opt/koding/scripts/test-instance/s3cmd-upload-logs $2"

cat - <<EOF
You can view logs at s3://kodingdev-test-instance-logs/$2/
EOF

exit 0
