#!/bin/bash

declare instance_id=$(ec2metadata | grep instance-id | awk '{print $2}')

declare access_key=$2
declare secret_key=$3

declare bucket="kodingdev-test-instance-logs"
declare prefix=$1
declare destination="s3://$bucket/$prefix/$instance_id"

if [ -z "$prefix" ]; then
	echo 'error: prefix parameter is not given'
	exit 1
fi

declare s3cmd_options="--human-readable-sizes --follow-symlinks --quiet"

s3cmd --access_key=$access_key --secret_key=$secret_key put $s3cmd_options --recursive $KONFIG_PROJECTROOT/.logs $destination/
s3cmd --access_key=$access_key --secret_key=$secret_key put $s3cmd_options /var/log/cloud-init-output.log $destination/
