package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJGroupFetchModeratorsWithEmailParams creates a new JGroupFetchModeratorsWithEmailParams object
// with the default values initialized.
func NewJGroupFetchModeratorsWithEmailParams() *JGroupFetchModeratorsWithEmailParams {
	var ()
	return &JGroupFetchModeratorsWithEmailParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJGroupFetchModeratorsWithEmailParamsWithTimeout creates a new JGroupFetchModeratorsWithEmailParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJGroupFetchModeratorsWithEmailParamsWithTimeout(timeout time.Duration) *JGroupFetchModeratorsWithEmailParams {
	var ()
	return &JGroupFetchModeratorsWithEmailParams{

		timeout: timeout,
	}
}

// NewJGroupFetchModeratorsWithEmailParamsWithContext creates a new JGroupFetchModeratorsWithEmailParams object
// with the default values initialized, and the ability to set a context for a request
func NewJGroupFetchModeratorsWithEmailParamsWithContext(ctx context.Context) *JGroupFetchModeratorsWithEmailParams {
	var ()
	return &JGroupFetchModeratorsWithEmailParams{

		Context: ctx,
	}
}

/*JGroupFetchModeratorsWithEmailParams contains all the parameters to send to the API endpoint
for the j group fetch moderators with email operation typically these are written to a http.Request
*/
type JGroupFetchModeratorsWithEmailParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) WithTimeout(timeout time.Duration) *JGroupFetchModeratorsWithEmailParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) WithContext(ctx context.Context) *JGroupFetchModeratorsWithEmailParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) WithBody(body models.DefaultSelector) *JGroupFetchModeratorsWithEmailParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WithID adds the id to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) WithID(id string) *JGroupFetchModeratorsWithEmailParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the j group fetch moderators with email params
func (o *JGroupFetchModeratorsWithEmailParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *JGroupFetchModeratorsWithEmailParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
