package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JGroupSetOAuthReader is a Reader for the JGroupSetOAuth structure.
type JGroupSetOAuthReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JGroupSetOAuthReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJGroupSetOAuthOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJGroupSetOAuthOK creates a JGroupSetOAuthOK with default headers values
func NewJGroupSetOAuthOK() *JGroupSetOAuthOK {
	return &JGroupSetOAuthOK{}
}

/*JGroupSetOAuthOK handles this case with default header values.

OK
*/
type JGroupSetOAuthOK struct {
	Payload JGroupSetOAuthOKBody
}

func (o *JGroupSetOAuthOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JGroup.setOAuth/{id}][%d] jGroupSetOAuthOK  %+v", 200, o.Payload)
}

func (o *JGroupSetOAuthOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*JGroupSetOAuthOKBody j group set o auth o k body
swagger:model JGroupSetOAuthOKBody
*/
type JGroupSetOAuthOKBody struct {
	models.JGroup

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *JGroupSetOAuthOKBody) UnmarshalJSON(raw []byte) error {

	var jGroupSetOAuthOKBodyAO0 models.JGroup
	if err := swag.ReadJSON(raw, &jGroupSetOAuthOKBodyAO0); err != nil {
		return err
	}
	o.JGroup = jGroupSetOAuthOKBodyAO0

	var jGroupSetOAuthOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &jGroupSetOAuthOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = jGroupSetOAuthOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o JGroupSetOAuthOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	jGroupSetOAuthOKBodyAO0, err := swag.WriteJSON(o.JGroup)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jGroupSetOAuthOKBodyAO0)

	jGroupSetOAuthOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, jGroupSetOAuthOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this j group set o auth o k body
func (o *JGroupSetOAuthOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JGroup.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
