package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewJGroupFetchMyMembershipsParams creates a new JGroupFetchMyMembershipsParams object
// with the default values initialized.
func NewJGroupFetchMyMembershipsParams() *JGroupFetchMyMembershipsParams {
	var ()
	return &JGroupFetchMyMembershipsParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewJGroupFetchMyMembershipsParamsWithTimeout creates a new JGroupFetchMyMembershipsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewJGroupFetchMyMembershipsParamsWithTimeout(timeout time.Duration) *JGroupFetchMyMembershipsParams {
	var ()
	return &JGroupFetchMyMembershipsParams{

		timeout: timeout,
	}
}

// NewJGroupFetchMyMembershipsParamsWithContext creates a new JGroupFetchMyMembershipsParams object
// with the default values initialized, and the ability to set a context for a request
func NewJGroupFetchMyMembershipsParamsWithContext(ctx context.Context) *JGroupFetchMyMembershipsParams {
	var ()
	return &JGroupFetchMyMembershipsParams{

		Context: ctx,
	}
}

/*JGroupFetchMyMembershipsParams contains all the parameters to send to the API endpoint
for the j group fetch my memberships operation typically these are written to a http.Request
*/
type JGroupFetchMyMembershipsParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) WithTimeout(timeout time.Duration) *JGroupFetchMyMembershipsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) WithContext(ctx context.Context) *JGroupFetchMyMembershipsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) WithBody(body models.DefaultSelector) *JGroupFetchMyMembershipsParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the j group fetch my memberships params
func (o *JGroupFetchMyMembershipsParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *JGroupFetchMyMembershipsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
