package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// JGroupFetchMyMembershipsReader is a Reader for the JGroupFetchMyMemberships structure.
type JGroupFetchMyMembershipsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *JGroupFetchMyMembershipsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewJGroupFetchMyMembershipsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewJGroupFetchMyMembershipsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewJGroupFetchMyMembershipsOK creates a JGroupFetchMyMembershipsOK with default headers values
func NewJGroupFetchMyMembershipsOK() *JGroupFetchMyMembershipsOK {
	return &JGroupFetchMyMembershipsOK{}
}

/*JGroupFetchMyMembershipsOK handles this case with default header values.

Request processed successfully
*/
type JGroupFetchMyMembershipsOK struct {
	Payload *models.DefaultResponse
}

func (o *JGroupFetchMyMembershipsOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JGroup.fetchMyMemberships][%d] jGroupFetchMyMembershipsOK  %+v", 200, o.Payload)
}

func (o *JGroupFetchMyMembershipsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DefaultResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewJGroupFetchMyMembershipsUnauthorized creates a JGroupFetchMyMembershipsUnauthorized with default headers values
func NewJGroupFetchMyMembershipsUnauthorized() *JGroupFetchMyMembershipsUnauthorized {
	return &JGroupFetchMyMembershipsUnauthorized{}
}

/*JGroupFetchMyMembershipsUnauthorized handles this case with default header values.

Unauthorized request
*/
type JGroupFetchMyMembershipsUnauthorized struct {
	Payload *models.UnauthorizedRequest
}

func (o *JGroupFetchMyMembershipsUnauthorized) Error() string {
	return fmt.Sprintf("[POST /remote.api/JGroup.fetchMyMemberships][%d] jGroupFetchMyMembershipsUnauthorized  %+v", 401, o.Payload)
}

func (o *JGroupFetchMyMembershipsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.UnauthorizedRequest)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
