package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// PostRemoteAPIJGroupModifyIDReader is a Reader for the PostRemoteAPIJGroupModifyID structure.
type PostRemoteAPIJGroupModifyIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *PostRemoteAPIJGroupModifyIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewPostRemoteAPIJGroupModifyIDOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewPostRemoteAPIJGroupModifyIDOK creates a PostRemoteAPIJGroupModifyIDOK with default headers values
func NewPostRemoteAPIJGroupModifyIDOK() *PostRemoteAPIJGroupModifyIDOK {
	return &PostRemoteAPIJGroupModifyIDOK{}
}

/*PostRemoteAPIJGroupModifyIDOK handles this case with default header values.

OK
*/
type PostRemoteAPIJGroupModifyIDOK struct {
	Payload PostRemoteAPIJGroupModifyIDOKBody
}

func (o *PostRemoteAPIJGroupModifyIDOK) Error() string {
	return fmt.Sprintf("[POST /remote.api/JGroup.modify/{id}][%d] postRemoteApiJGroupModifyIdOK  %+v", 200, o.Payload)
}

func (o *PostRemoteAPIJGroupModifyIDOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*PostRemoteAPIJGroupModifyIDOKBody post remote API j group modify ID o k body
swagger:model PostRemoteAPIJGroupModifyIDOKBody
*/
type PostRemoteAPIJGroupModifyIDOKBody struct {
	models.JGroup

	models.DefaultResponse
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *PostRemoteAPIJGroupModifyIDOKBody) UnmarshalJSON(raw []byte) error {

	var postRemoteAPIJGroupModifyIDOKBodyAO0 models.JGroup
	if err := swag.ReadJSON(raw, &postRemoteAPIJGroupModifyIDOKBodyAO0); err != nil {
		return err
	}
	o.JGroup = postRemoteAPIJGroupModifyIDOKBodyAO0

	var postRemoteAPIJGroupModifyIDOKBodyAO1 models.DefaultResponse
	if err := swag.ReadJSON(raw, &postRemoteAPIJGroupModifyIDOKBodyAO1); err != nil {
		return err
	}
	o.DefaultResponse = postRemoteAPIJGroupModifyIDOKBodyAO1

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o PostRemoteAPIJGroupModifyIDOKBody) MarshalJSON() ([]byte, error) {
	var _parts [][]byte

	postRemoteAPIJGroupModifyIDOKBodyAO0, err := swag.WriteJSON(o.JGroup)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJGroupModifyIDOKBodyAO0)

	postRemoteAPIJGroupModifyIDOKBodyAO1, err := swag.WriteJSON(o.DefaultResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, postRemoteAPIJGroupModifyIDOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this post remote API j group modify ID o k body
func (o *PostRemoteAPIJGroupModifyIDOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.JGroup.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.DefaultResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
