package j_group

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewPostRemoteAPIJGroupModifyDataIDParams creates a new PostRemoteAPIJGroupModifyDataIDParams object
// with the default values initialized.
func NewPostRemoteAPIJGroupModifyDataIDParams() *PostRemoteAPIJGroupModifyDataIDParams {
	var ()
	return &PostRemoteAPIJGroupModifyDataIDParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIJGroupModifyDataIDParamsWithTimeout creates a new PostRemoteAPIJGroupModifyDataIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIJGroupModifyDataIDParamsWithTimeout(timeout time.Duration) *PostRemoteAPIJGroupModifyDataIDParams {
	var ()
	return &PostRemoteAPIJGroupModifyDataIDParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIJGroupModifyDataIDParamsWithContext creates a new PostRemoteAPIJGroupModifyDataIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIJGroupModifyDataIDParamsWithContext(ctx context.Context) *PostRemoteAPIJGroupModifyDataIDParams {
	var ()
	return &PostRemoteAPIJGroupModifyDataIDParams{

		Context: ctx,
	}
}

/*PostRemoteAPIJGroupModifyDataIDParams contains all the parameters to send to the API endpoint
for the post remote API j group modify data ID operation typically these are written to a http.Request
*/
type PostRemoteAPIJGroupModifyDataIDParams struct {

	/*Body
	  body of the request

	*/
	Body PostRemoteAPIJGroupModifyDataIDBody
	/*ID
	  Mongo ID of target instance

	*/
	ID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) WithTimeout(timeout time.Duration) *PostRemoteAPIJGroupModifyDataIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) WithContext(ctx context.Context) *PostRemoteAPIJGroupModifyDataIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) WithBody(body PostRemoteAPIJGroupModifyDataIDBody) *PostRemoteAPIJGroupModifyDataIDParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) SetBody(body PostRemoteAPIJGroupModifyDataIDBody) {
	o.Body = body
}

// WithID adds the id to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) WithID(id string) *PostRemoteAPIJGroupModifyDataIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the post remote API j group modify data ID params
func (o *PostRemoteAPIJGroupModifyDataIDParams) SetID(id string) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIJGroupModifyDataIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	// path param id
	if err := r.SetPathParam("id", o.ID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
