source "https://rubygems.org"
ruby RUBY_VERSION

# gem "jekyll", "3.2.1"

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
  # gem "jekyll-github-metadata", "~> 1.0"
  gem "jekyll-paginate"
end
