#!/bin/bash

### PREPARE ###

# docker pull koding/mongo
# docker pull koding/postgres
# docker pull koding/rabbitmq
# docker pull koding/redis
# docker build --no-cache -t koding/run .

# Remove all stopped containers.
# docker rm $(docker ps -a -q)

# Remove all untagged images
# docker rmi $(docker images | grep "^<none>" | awk "{print $3}")

### RUN ###

PRJ=/opt/koding       # `pwd`
BLD=/root/BUILD_DATA        # /BUILD_DATA
CFG=`cat $BLD/BUILD_CONFIG`
RGN=`cat $BLD/BUILD_REGION` 
HST=`cat $BLD/BUILD_HOSTNAME`
PBKEY=$PRJ/certs/test_kontrol_rsa_public.pem
PVKEY=$PRJ/certs/test_kontrol_rsa_private.pem
LOG=/tmp/logs
GB=$PRJ/go/bin
SOCIALCONFIG=./go/src/socialapi/config/docker.toml

mkdir -p $LOG


docker run                 -d --name=mongo            --entrypoint=mongod                  koding/mongo    --dbpath /root/data/db --smallfiles --nojournal
docker run     						 -d --name=postgres                                              koding/postgres
docker run     						 -d --name=rabbitmq                                              koding/rabbitmq
docker run     						 -d --name=redis                                                 koding/redis    redis-server
sleep 5
docker run -p 4000:4000		 -d --name=kontrol           --entrypoint=$GB/kontrol       		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $CFG -r $RGN
docker run                 -d --name=kloud             --entrypoint=$GB/kloud         		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $CFG -r $RGN -public-key $PBKEY -private-key $PVKEY -kontrol-url "http://$HST:4000/kite"
docker run                 -d --name=rerouting         --entrypoint=$GB/rerouting     		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $CFG
docker run                 -d --name=cronJobs          --entrypoint=$GB/cron          		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $CFG
docker run  -p 8008:8008   -d --name=broker            --entrypoint=$GB/broker        		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $CFG
docker run  -p 4001:4001   -d --name=proxy             --entrypoint=$GB/reverseproxy  		 															 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -region $RGN -host $HST -env production 
docker run  -p 7000:7000   -d --name=socialapi         --entrypoint=$GB/api       		 		-e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG -port 7000
docker run                 -d --name=dailymailnotifier --entrypoint=$GB/dailymailnotifier -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=notification      --entrypoint=$GB/notification      -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=popularpost       --entrypoint=$GB/popularpost       -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=populartopic      --entrypoint=$GB/populartopic      -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=realtime          --entrypoint=$GB/realtime       	  -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=sitemapfeeder     --entrypoint=$GB/sitemapfeeder     -e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=topicfeed         --entrypoint=$GB/topicfeed       	-e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run                 -d --name=trollmode         --entrypoint=$GB/trollmode       	-e "SOCIAL_API_HOSTNAME=$HST"  --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  -c $SOCIALCONFIG
docker run  -p 80:80       -d --name=webserver         --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/server/index.js               -c $CFG -p 80   --disable-newrelic
docker run  -p 3526:3526   -d --name=sourceMapServer   --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/server/lib/source-server/index.js   -c $CFG -p 3526
docker run                 -d --name=authWorker        --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/workers/auth/index.js         -c $CFG
docker run  -p 3030:3030   -d --name=social            --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/workers/social/index.js       -c $CFG -p 3030 --disable-newrelic --kite-port=13020
docker run                 -d --name=guestCleaner      --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/workers/guestcleaner/index.js -c $CFG
docker run                 -d --name=emailSender       --entrypoint=node 								 																 --link=mongo:mongo --link=postgres:postgres --link=redis:redis --link=rabbitmq:rabbitmq koding/run  $PRJ/workers/emailsender/index.js  -c $CFG













