module.exports =
  getters   : require './getters'
  actions   :
    message     : require './actions/message'
    thread      : require './actions/thread'
    channel     : require './actions/channel'
    suggestions : require './actions/suggestions'
    emoji       : require './actions/emoji'
  stores    : [
    require './stores/messagesstore'
    require './stores/channelsstore'
    require './stores/channelthreadsstore'
    require './stores/messagethreadssstore'
    require './stores/selectedchannelthreadidstore'
    require './stores/selectedmessagethreadidstore'
    require './stores/followedpublicchannelidsstore'
    require './stores/followedprivatechannelidsstore'
    require './stores/channelparticipantidsstore'
    require './stores/channelpopularmessageidsstore'
    require './stores/suggestions/suggestionsquerystore'
    require './stores/suggestions/suggestionsflagsstore'
    require './stores/suggestions/suggestionsstore'
    require './stores/messagelikerssstore'
    require './stores/channelflagsstore'
    require './stores/chatinput/emojisstore'
    require './stores/chatinput/filteredemojilistquerystore'
    require './stores/chatinput/filteredemojilistselectedindexstore'
    require './stores/chatinput/commonemojilistselectedindexstore'
    require './stores/chatinput/commonemojilistflagsstore'
    require './stores/chatinput/chatinputchannelsselectedindexstore'
    require './stores/chatinput/chatinputchannelsquerystore'
  ]

