module.exports = {
  'CredentialChangesRevertRequested'
  'CredentialChangesSaveRequested'
  'WarnAboutMissingCredentials'
  'CredentialSelectionChanged'
  'CredentialFilterChanged'
  'SelectedProviderChanged'
  'CredentialListUpdated'
  'StackWizardCancelled'
  'InitializeRequested'
  'TemplateDataChanged'
  'ProviderSelected'
  'LazyLoadFinished'
  'LazyLoadStarted'
  'ShowCredentials'
  'GotFocus'
  'Log'
}
