{fork} = require 'child_process'
KodingLogger = require 'koding-logger'
os = require 'os'

option '-c', '--configPath [CONFIG]', 'Which config file to use.'
option '-n', '--numberOfWorkers [WORKERS]', 'The number of workers to run.'
option '-s', '--silent', 'Set this flag to suppress stdout'

task 'run', ({numberOfWorkers, configPath, silent})->
  configPath ?= '../../config/dev'
  {logger, configNumberOfWorkers} = require configPath
  numberOfWorkers ?= configNumberOfWorkers ? 1
  logger = new KodingLogger 'social', os.hostname(), logger.mq
  logger.tailTo process.stdout unless silent
  i = 0
  logger.logAll process, 'supervisor'
  while i < numberOfWorkers
    child = fork './index', ['-c', configPath], silent: yes
    logger.logAll child, "worker#{i}"
    i++