option '-p', '--path [PATH]', 'specify the path to place the built js into'

fs          = require 'fs'
cs          = require 'coffee-script'
stylus          = require 'stylus'
{exec} = require 'child_process'

applicationFiles = [
  './src/AppRequirements.coffee'
  './src/AppController.coffee'
]

styleFiles = [
  './styles/app.styl'
]
  
wrapWithJSClosure = (js)-> "(function(){#{js}}).call(this);"

concatenateAndCompileFilePaths=(pathArray)->
  contents = ""
  for filePath in pathArray
    contents += "#{fs.readFileSync filePath, 'utf-8'}\n"
  # fs.writeFile 'debug.coffee',contents
  try
    contents = cs.compile contents,bare:yes
    return contents
  catch error
    console.log "#{(error.stack.split "\n")[0]} at: "
    
compileFilePath=(path)->
  contents = fs.readFileSync path, 'utf-8'
  try
    contents = cs.compile contents,bare:yes
    return contents
  catch error
    console.log "#{(error.stack.split "\n")[0]} at: #{path}"

concatenateAndCompileStylusFilePaths = (pathArray)->
  contents = ""
  for filePath in pathArray
    contents += "#{fs.readFileSync filePath, 'utf-8'}\n"
  stylus.render contents, (err,css)->
    unless err
      callback css
    else
      console.log "#{err} error with styl file"

compileStylusFilePath=(path, callback)->
  contents = fs.readFileSync path, 'utf-8'
  stylus.render contents,(err,css)=>
    unless err
      callback css
    else
      console.log "#{err} error with styl file at #{path}"
                           
task 'build', 'build your application', (options={})->
  path = options.path or ""
  
  concatenatedFiles = concatenateAndCompileFilePaths applicationFiles
  concatenatedFiles = wrapWithJSClosure concatenatedFiles
  
  fs.writeFile "#{path}/AppController.js",concatenatedFiles,(err) ->if err then console.log err
  concatenateAndCompileStylusFilePaths styleFiles, (css)->
    fs.writeFile "#{path}/app.css", css, (err)->if err then console.log err
  
  exec "cp -r ./js/ #{path}"
  exec "cp -r ./css/ #{path}"



task 'preview', 'preview your application', (options)->
  # wip