language: go

# depman needs to be installed with GOPATH pointing to a single directory.
script:
  - GOPATH=$HOME/gopath go get github.com/vube/depman
  - GOPATH=$HOME/gopath $HOME/gopath/bin/depman
  - go test -v ./...

go:
  - 1.3.3
  - 1.4.2

install:
  - go get gopkg.in/fsnotify.v0
