package git_provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewGitProviderCreateImportedStackTemplateParams creates a new GitProviderCreateImportedStackTemplateParams object
// with the default values initialized.
func NewGitProviderCreateImportedStackTemplateParams() *GitProviderCreateImportedStackTemplateParams {
	var ()
	return &GitProviderCreateImportedStackTemplateParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewGitProviderCreateImportedStackTemplateParamsWithTimeout creates a new GitProviderCreateImportedStackTemplateParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGitProviderCreateImportedStackTemplateParamsWithTimeout(timeout time.Duration) *GitProviderCreateImportedStackTemplateParams {
	var ()
	return &GitProviderCreateImportedStackTemplateParams{

		timeout: timeout,
	}
}

// NewGitProviderCreateImportedStackTemplateParamsWithContext creates a new GitProviderCreateImportedStackTemplateParams object
// with the default values initialized, and the ability to set a context for a request
func NewGitProviderCreateImportedStackTemplateParamsWithContext(ctx context.Context) *GitProviderCreateImportedStackTemplateParams {
	var ()
	return &GitProviderCreateImportedStackTemplateParams{

		Context: ctx,
	}
}

/*GitProviderCreateImportedStackTemplateParams contains all the parameters to send to the API endpoint
for the git provider create imported stack template operation typically these are written to a http.Request
*/
type GitProviderCreateImportedStackTemplateParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) WithTimeout(timeout time.Duration) *GitProviderCreateImportedStackTemplateParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) WithContext(ctx context.Context) *GitProviderCreateImportedStackTemplateParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) WithBody(body models.DefaultSelector) *GitProviderCreateImportedStackTemplateParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the git provider create imported stack template params
func (o *GitProviderCreateImportedStackTemplateParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *GitProviderCreateImportedStackTemplateParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
