package git_provider

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	"koding/remoteapi/models"
)

// NewPostRemoteAPIGitProviderFetchConfigParams creates a new PostRemoteAPIGitProviderFetchConfigParams object
// with the default values initialized.
func NewPostRemoteAPIGitProviderFetchConfigParams() *PostRemoteAPIGitProviderFetchConfigParams {
	var ()
	return &PostRemoteAPIGitProviderFetchConfigParams{

		timeout: cr.DefaultTimeout,
	}
}

// NewPostRemoteAPIGitProviderFetchConfigParamsWithTimeout creates a new PostRemoteAPIGitProviderFetchConfigParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPostRemoteAPIGitProviderFetchConfigParamsWithTimeout(timeout time.Duration) *PostRemoteAPIGitProviderFetchConfigParams {
	var ()
	return &PostRemoteAPIGitProviderFetchConfigParams{

		timeout: timeout,
	}
}

// NewPostRemoteAPIGitProviderFetchConfigParamsWithContext creates a new PostRemoteAPIGitProviderFetchConfigParams object
// with the default values initialized, and the ability to set a context for a request
func NewPostRemoteAPIGitProviderFetchConfigParamsWithContext(ctx context.Context) *PostRemoteAPIGitProviderFetchConfigParams {
	var ()
	return &PostRemoteAPIGitProviderFetchConfigParams{

		Context: ctx,
	}
}

/*PostRemoteAPIGitProviderFetchConfigParams contains all the parameters to send to the API endpoint
for the post remote API git provider fetch config operation typically these are written to a http.Request
*/
type PostRemoteAPIGitProviderFetchConfigParams struct {

	/*Body
	  body of the request

	*/
	Body models.DefaultSelector

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) WithTimeout(timeout time.Duration) *PostRemoteAPIGitProviderFetchConfigParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) WithContext(ctx context.Context) *PostRemoteAPIGitProviderFetchConfigParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithBody adds the body to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) WithBody(body models.DefaultSelector) *PostRemoteAPIGitProviderFetchConfigParams {
	o.SetBody(body)
	return o
}

// SetBody adds the body to the post remote API git provider fetch config params
func (o *PostRemoteAPIGitProviderFetchConfigParams) SetBody(body models.DefaultSelector) {
	o.Body = body
}

// WriteToRequest writes these params to a swagger request
func (o *PostRemoteAPIGitProviderFetchConfigParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	r.SetTimeout(o.timeout)
	var res []error

	if err := r.SetBodyParam(o.Body); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
