module.exports =
  IDELoaded               : 'IDE/Terminal loaded for the first time'
  IDESettingsOpened       : 'IDE/Terminal settings clicked'
  StacksViewed            : 'Stack list viewed'
  VMsViewed               : 'VM list viewed'
  CredentialsViewed       : 'Credential list viewed'
  MyTeamViewed            : 'My Team settings viewed'
  TeamBillingViewed       : 'Team Billing viewed'
  KodingUtilitiesViewed   : 'Koding Utilities viewed'
  MyAccountViewed         : 'My Account information viewed'
