module.exports =
  IDELoaded               : 'IDE/Terminal loaded for the first time'
  CollaborationStarted    : 'Collaboration button clicked for the first time'
  PublicChannelViewed     : 'Viewed #public'
  ChangelogChannelViewed  : 'Viewed #changelog'
  OtherChannelViewed      : 'Viewed other #channel for the first time'
  NewPrivateMessageOpened : 'New Private Message form opened'
  PrivateMessagesViewed   : 'Private Messages viewed for the first time'
  VMSettingsOpened        : 'VM Settings opened'
  WorkspaceSettingsOpened : 'Workspace Settings opened'
  IDESettingsOpened       : 'IDE/Terminal settings clicked'
